### ISSUE TITLE
Make DocValuesIterator public [LUCENE-9203]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10243]
By doing this, we improve extensibility for new formats. Additionally this will improve coherence with the public method already existent in the class.

---
Migrated from [LUCENE-9203](https://issues.apache.org/jira/browse/LUCENE-9203) by juan camilo rodriguez duran, updated Jun 22 2021
Parent: #10276
Linked issues:
 - #10123

**Comment by jpountz** [comment]
Closing.
