### ISSUE TITLE
Lucene web site broken links [LUCENE-9229]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10269]
The new website is live, so I ran a dead-link checker on it to see if anything is broken. Here is the list of dead links. A bunch of them are from JavaDoc or from RefGuide, but some are also missing graphics on the site itself.

Feel free to grab broken links and commit fixes either to lucene-site repo or lucene-solr repo as you see fit. When a link is fixed, please change ❌ into ✔ here so we see progress. Some of the broken links are in legacy changes html, guess we don't need to fix those.
### <http://lucene.apache.org/pylucene/jcc/install.html>

✔ [404] <https://bugs.python.org/setuptools/issue43>
### <http://lucene.apache.org/pylucene/features.html>

✔ [404] <https://svn.apache.org/viewcvs.cgi/lucene/pylucene/trunk/test>
### <http://lucene.apache.org/solr/resources.html>

✔ [0] <http://hrishikesh.karambelkar.co.in/>
 ✔ [404] <http://lucenerevolution.org/past-events/>
 ✔ [404] <http://www.packtpub.com/apache-solr-for-indexing-data/book>
 ✔ [0] <http://www.inkstall.com/>
### <http://lucene.apache.org/pylucene/jcc/features.html>

✔ [0] <https://peak.telecommunity.com/DevCenter/EasyInstall>
### <http://lucene.apache.org/solr/api/changes/Changes.html>

✔ [404] <http://wiki.apache.org/solr/FunctionQuery>.
### <http://lucene.apache.org/solr/api/solr-test-framework/overview-tree.html>

❌ [404] <https://junit.org/junit4/javadoc/4.12/org/junit/rules.TestRule.html?is-external=true>
### <http://lucene.apache.org/solr/api/solr-test-framework/org/apache/solr/util/RevertDefaultThreadHandlerRule.html>

❌ [404] <https://junit.org/junit4/javadoc/4.12/org/junit/runners/model.Statement.html?is-external=true>
### <http://lucene.apache.org/solr/api/solr-test-framework/org/apache/solr/util/SSLTestConfig.html>

❌ [404] <https://junit.org/junit4/javadoc/4.12/org/junit/internal.AssumptionViolatedException.html?is-external=true>
### <http://lucene.apache.org/solr/api/solr-solrj/org/apache/solr/common/util/ByteArrayUtf8CharSequence.html>

❌ [404] <http://download.java.net/java/jdk9/docs/api/java/util/Arrays.html>
### <http://lucene.apache.org/solr/api/solr-solrj/org/apache/solr/client/solrj/SolrQuery.html>

❌ [404] <https://wiki.apache.org/solr/SimpleFacetParameters>
### <http://lucene.apache.org/solr/api/solr-core/org/apache/solr/legacy/BBoxStrategy.html>

✔ [404] <http://geoportal.svn.sourceforge.net/svnroot/geoportal/Geoportal/trunk/src/com/esri/gpt/catalog/lucene/SpatialClauseAdapter.java>
### <http://lucene.apache.org/solr/api/solr-core/org/apache/solr/search/FastLRUCache.html>

❌ [404] <http://wiki.apache.org/solr/SolrCaching>
### <http://lucene.apache.org/solr/api/solr-core/org/apache/solr/util/hll/HLL.html>

✔ [404] <http://guava-libraries.googlecode.com/git/guava/src/com/google/common/hash/Murmur3_128HashFunction.java>
 ✔ [404] <https://github.com/aggregateknowledge/postgresql-hll/blob/master/README.markdown>
 ✔ [404] <https://github.com/aggregateknowledge/postgresql-hll/blob/master/STORAGE.markdown>
### <http://lucene.apache.org/solr/api/solr-core/org/apache/solr/legacy/>

❌ [404] <http://lucene.apache.org/icons/blank.gif>
 ❌ [404] <http://lucene.apache.org/icons/text.gif>
 ❌ [404] <http://lucene.apache.org/icons/folder.gif>
 ❌ [404] <http://lucene.apache.org/icons/back.gif>
### <http://lucene.apache.org/solr/api/solr-core/org/apache/solr/legacy/doc-files/>

❌ [404] <http://lucene.apache.org/icons/image2.gif>

(For RefGuide, please see https://issues.apache.org/jira/browse/SOLR-15497 instead)

---
Migrated from [LUCENE-9229](https://issues.apache.org/jira/browse/LUCENE-9229) by Jan Høydahl (@janhoy), updated Nov 19 2021
Linked issues:
 - #10030

**Comment by janhoy** [comment]
I'll close this old issue. Anyone discovering any new broken links on the site can fix those in new PRs.
