### ISSUE TITLE
There may be can simpler in DefaultIndexingChain [LUCENE-9303]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10343]
In  DefaultIndexingChain.processField()

```java
if (fieldType.stored()) {
  if (fp == null) {
    fp = getOrAddField(fieldName, fieldType, false);
  }
  if (fieldType.stored()) {
    String value = field.stringValue(); 
    ......
    try { 
      storedFieldsConsumer.writeField(fp.fieldInfo, field);
    } catch (Throwable th) {
      ......
    }
  }
}
```

 If there has need to add the second `if`, because `fieldType.stored()` is executed before.

---
Migrated from [LUCENE-9303](https://issues.apache.org/jira/browse/LUCENE-9303) by kkewwei (@kkewwei), updated Dec 21 2020

**Comment by shaikhu** [comment]
Hi @janhoy @kkewwei, I think this issues can be closed now? It looks like the followng [PR ](https://github.com/apache/lucene-solr/pull/2076) fixed the issue on master.
