### ISSUE TITLE
Ensure sub-iterators of ConjunctionDISI are on the same document [LUCENE-9541]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10581]
Not completely sure if this is a bug.

BitSetConjuctionDISI advances based on its lead  – DocIdSetIterator iterator, and doesn't consider that its another component – BitSetIterator may have already advanced passed a certain doc. This may result in duplicate documents.

For example if BitSetConjuctionDISI  _disi_ is composed of DocIdSetIterator _a_ of docs  [0,1] and BitSetIterator _b_ of docs [0,1].  Doing `b.nextDoc()` we are collecting doc0,  doing `disi.nextDoc` we again  collecting the same doc0.

It seems that other conjunction iterators don't have this behaviour, if we are advancing any of their component pass a certain document, the whole conjunction iterator will also be advanced pass this document. 

 

This behaviour was exposed in this [PR](https://github.com/apache/lucene-solr/pull/1903).

---
Migrated from [LUCENE-9541](https://issues.apache.org/jira/browse/LUCENE-9541) by Mayya Sharipova (@mayya-sharipova), updated Oct 06 2020
Pull requests: https://github.com/apache/lucene-solr/pull/1937

**Comment by jpountz** [comment]
This has been merged.
