### ISSUE TITLE
Add .editorConfig [LUCENE-9563]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10603]
I propose adding a ".editorConfig" to the root of the project.  Many text editors and IDEs support this file to declare code style settings such as indentation and more.  In particular, IntelliJ supports this natively and Eclipse has a plugin for it.

https://editorconfig.org

I furthermore propose I simply generate this as an export of my current IntelliJ code style, which is a code style I've been using and was originally imported from the Lucene's former IntelliJ config.

---
Migrated from [LUCENE-9563](https://issues.apache.org/jira/browse/LUCENE-9563) by David Smiley (@dsmiley), 1 vote, updated Oct 14 2021
Linked issues:
 - #10604

Pull requests: https://github.com/apache/lucene-solr/pull/1956

**Comment by msokolov** [comment]
I think we can resolve now that we have automatic tidy-ing
