### ISSUE TITLE
Increase the default value of MAX_DIMENSIONS for Vector Values

### ISSUE THREAD

**Issue by MarcusSorealheis** [apache/lucene#1060]
### Description

I'd like for the team to consider increasing the default limit for MAX_DIMENSIONS. A number of commonly used encoders are optimized for more dimensions than Lucene allows out of the box, limiting the amount of companies that can use Lucene in conjunction with existing tools. Customers that would like to use a higher level of dimensions must be prepared to pay the cost, and we can pursue optimizations to improve the experience for those users if they become very common.

**Comment by msokolov** [comment]
Hi Marcus - we've been discussing this in https://issues.apache.org/jira/browse/LUCENE-10471 it seems to have been controversial. If you can weigh in with some specific use cases for higher dimensions (name the vectors and their dims) that would be helpful

**Comment by MarcusSorealheis** [comment]
Thanks Mike, I will do so.

**Comment by mocobeta** [comment]
Issues should be raised in Jira. Please do not use GitHub issue until the migration will have done.
