### ISSUE TITLE
Remove redundant fieldType.stored() check [LUCENE-9603]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10643]
No need to check fieldType.stored() here because already checked.https://github.com/apache/lucene-solr/blob/5897d14fe4f5dd785a561b18c939ea31186c4971/lucene/core/src/java/org/apache/lucene/index/IndexingChain.java#L587

---
Migrated from [LUCENE-9603](https://issues.apache.org/jira/browse/LUCENE-9603) by Shintaro Murakami (@mrkm4ntr), updated Nov 12 2020
Pull requests: https://github.com/apache/lucene-solr/pull/2076

**Comment by slow-J** [comment]
This can be resolved, it was removed in https://github.com/apache/lucene/commit/d1297e52d91dbbcd83012c438ee0122d96808fa8 .

**Comment by mikemccand** [comment]
Ahh yes this is indeed done -- I'll close this issue.  Thanks @hurutoriya and @slow-J and @mrkm4ntr!
