### ISSUE TITLE
Move Points from a visitor API to a cursor-style API? [LUCENE-9619]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10659]
Points' visitor API work well but there are a couple things we could make better if we moved to a cursor API, e.g.
- Term queries could return a DocIdSetIterator without having to materialize a BitSet.
- Nearest-neighbor search could work on top of the regular API instead of casting to BKDReader https://github.com/apache/lucene-solr/blob/6a7131ee246d700c2436a85ddc537575de2aeacf/lucene/sandbox/src/java/org/apache/lucene/sandbox/document/FloatPointNearestNeighbor.java#L296
- We could optimize counting the number of matches of a query by adding the number of points in a leaf without visiting documents where there are no deleted documents and a leaf fully matches the query.

---
Migrated from [LUCENE-9619](https://issues.apache.org/jira/browse/LUCENE-9619) by Adrien Grand (@jpountz), updated Dec 06 2021
Pull requests: https://github.com/apache/lucene/pull/486

**Comment by jpountz** [comment]
This has been implemented.
