### ISSUE TITLE
Benchmark KNN search with ann-benchmarks [LUCENE-9625]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10665]
In addition to benchmarking with luceneutil, it would be good to be able to make use of ann-benchmarks, which is publishing results from many approximate knn algorithms, including the hnsw implementation from its authors. We don't expect to challenge the performance of these native code libraries, however it would be good to know just how far off we are.

I started looking into this and posted a fork of ann-benchmarks that uses KnnGraphTester  class to run these: https://github.com/msokolov/ann-benchmarks. It's still a WIP; you have to manually copy jars and the KnnGraphTester.class to the test host machine rather than downloading from a distribution. KnnGraphTester needs some modifications in order to support this process - this issue is mostly about that.

One thing I noticed is that some of the index builds with higher fanout (efConstruction) settings time out at 2h (on an AWS c5 instance), so this is concerning and I'll open a separate issue for trying to improve that.

---
Migrated from [LUCENE-9625](https://issues.apache.org/jira/browse/LUCENE-9625) by Michael Sokolov (@msokolov), updated May 20 2022
Pull requests: https://github.com/apache/lucene-solr/pull/2157

**Comment by benwtrent** [comment]
I opened a PR for ann-benchmarks: https://github.com/erikbern/ann-benchmarks/pull/315

I tested PyLucene locally, comparing it to @msokolov's "batch" methodology (writing to disk and spinning up a Java process). PyLucene provided faster numbers in both Batch and iterative on my m1 mac. This indicates that the overhead experienced is acceptable for now. 

There are improvements we can make to PyLucene (native numpy support is a big one). But, it seems prudent to get measurements recorded in ann-benchmarks and iteratively improve our python over time :).

Also, its for Lucene 9.1. I am going to see about getting a newer PyLucene version built hitting the latest release. We can update our benchmark implementation to hit the new version when its available.

@msokolov @jtibshirani IDK if y'all want to review the ann-benchmarks implementation or not. Let me know what you think.

**Comment by jtibshirani** [comment]
Thanks @benwtrent, it's great to see that PyLucene works well and has low overhead! It feels more solid than what we were doing before.

+1 to preparing a new version. As I mentioned on the PR, we made a big correction to the algorithm in Lucene 9.2 (https://issues.apache.org/jira/browse/LUCENE-10527). It would be too bad if results came out and Lucene did much worse than hnswlib because it was missing this fix!

It'd also be great to compare the results against hnswlib as part of the submission. We can double-check that recall is the same for a given set of parameters. This would give confidence we've interpreted all the parameters right in the ann-benchmarks runner. I'm happy to help with this since I have hnswlib set up locally.

**Comment by ovalhub** [comment]
On Mon, 31 Oct 2022, Benjamin Trent wrote:

> I tested PyLucene locally, comparing it to @msokolov's "batch" methodology 
> (writing to disk and spinning up a Java process). PyLucene provided faster 
> numbers in both Batch and iterative on my m1 mac. This indicates that the 
> overhead experienced is acceptable for now.
>
> There are improvements we can make to PyLucene (native numpy support is a 
> big one). But, it seems prudent to get measurements recorded in 
> ann-benchmarks and iteratively improve our python over time :).

What do you mean with "native numpy" ? Are you under the impression that 
PyLucene is a Python implementation of Lucene ? It's not. It's an 
auto-generated CPython wrapper around an auto-generated C++ wrapper 
that calls Java Lucene via JNI and that embeds a Java VM into a Python VM. 
PyLucene _is_ Java Lucene, unchanged, embedded in a Python VM.

Andi..

**Comment by benwtrent** [comment]
@ovalhub `numpy` collections are already native. To use them, I have to pull them into python collections and then cast them to be native again. 

Example:
```
X = X.tolist()
doc.add(KnnVectorField("knn", JArray('float')(X), fieldType))
```
The `.toList()` is weird to me as `X` is already a natively backed float array, just a numpy object. 

Admittedly, I may be misunderstanding how the communication between Python -> `native` -> Java is done. But it SEEMS that calling `tolist` for numpy unnecessarily pulls an already native collection into a generic python list.

**Comment by benwtrent** [comment]
> It'd also be great to compare the results against hnswlib as part of the submission. We can double-check that recall is the same for a given set of parameters. This would give confidence we've interpreted all the parameters right in the ann-benchmarks runner. I'm happy to help with this since I have hnswlib set up locally.

Ah, for sure. That would be useful. We would have to wait for a new version of PyLucene to be built for this though as right now we still have the bug in: https://issues.apache.org/jira/browse/LUCENE-10527

**Comment by ovalhub** [comment]
On Mon, 31 Oct 2022, Benjamin Trent wrote:

> @ovalhub `numpy` collections are already native. To use them, I have to 
> pull them into python collections and then cast them to be native again.
>
> Example: ``` X = X.tolist() doc.add(KnnVectorField("knn", 
> JArray('float')(X), fieldType)) ``` The `.toList()` is weird to me as `X` 
> is already a natively backed float array, just a numpy object.
>
> Admittedly, I may be misunderstanding how the communication between Python 
> -> `native` -> Java is done. But it SEEMS that calling `tolist` for numpy 
> unnecessarily pulls an already native collection into a generic python 
> list.

When you make a JArray with "JArray('float')(X), fieldType))" the 
JArray<float> code in JCC's JArray.h will iterate 'X' "as a sequence", 
calling PySequence_GetItem(sequence, i) and fill a Java float array with the 
values returned.
If native numpy collections are exposed to Python as sequences (ie, ordered 
things that can be accessed with int indexes), then you should not have to 
call .tolist() on it before using it with PyLucene/JCC.
It could also be that numpy's .tolist() just creates a wrapper object around 
the native array to expose it as a Python sequence ? (I don't know numpy).

**Comment by benwtrent** [comment]
While we haven't updated our benchmarks for quite some time, this is done.
