### ISSUE TITLE
Improve encoding of HNSW graph offsets [LUCENE-9845]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#10884]
Today we use a simple `long[]` to encode the offset of each document's array of neighbors in the HNSW graph. Instead we should use a data structure that is optimized for encoding an increasing numeric array, like   monotonic `PackedInts`

---
Migrated from [LUCENE-9845](https://issues.apache.org/jira/browse/LUCENE-9845) by Michael Sokolov (@msokolov), updated Mar 16 2021

**Comment by msokolov** [comment]
Closing because we now have dense/sparse customizations
