### ISSUE TITLE
Make CheckIndex doChecksumsOnly / -fast as default [LUCENE-9984]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11023]
This issue is a spin-off from discussion in https://github.com/apache/lucene/pull/128

Currently _CheckIndex_ defaults to checking both checksum as well as content inside each segment files for correctness, and requires _-fast_ flag to be explicitly passed in to do checksum only. However, this default setting was there due to lack of checksum feature historically, and is slow for most end-users nowadays as they probably only care about their indices being intact (from random bit flipping for example).

This issue is to change the default settings for CheckIndex so that they are more appropriate for end-users. One proposal from @rmuir is the following:
1. Make `-fast` the new default.
1. The previous `-slow` could be moved to `-slower` 
1. The current behavior (checksum + segment file content - slow check) could be activated by `-slow`.

---
Migrated from [LUCENE-9984](https://issues.apache.org/jira/browse/LUCENE-9984) by Zach Chen (@zacharymorn), updated Aug 16 2021

**Comment by slow-J** [comment]
I'll clean up the deprecated CheckIndex params in Lucene 11.
