### ISSUE TITLE
Duplication computation for TieredMergePolicy's numDeletesToMerge [LUCENE-10041]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11079]
In lucene 8.4 (Elasticsearch 7.6.2), all indices are enabled with soft-deletes. We found the **TieredMergePolicy** contains redundant query computation to acquire **numDeletesToMerge** for **findMerges**. According to code from [getSortedBySegmentSize](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/TieredMergePolicy.java#L303) , I think we should reuse the result of numDeletesToMerge which can reduce 3% CPU and some IO overheads.

 
.

![IMG21.jpeg](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10041/IMG21.jpeg)

---
Migrated from [LUCENE-10041](https://issues.apache.org/jira/browse/LUCENE-10041) by Feng Gui, updated Aug 16 2021
Attachments: [IMG21.jpeg](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10041/IMG21.jpeg)

**Comment by dnhatn** [comment]
Fixed in #12339
