### ISSUE TITLE
Remove VectorValues#binaryValue? [LUCENE-10175]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11212]
It's unclear to me why we have VectorValues#binaryValue. This exposes implementation details that I'd rather like to avoid exposing in our higher-level APIs such as the Directory byte order. And I worry that it might be in the way of upcoming features like supporting bfloat16.

---
Migrated from [LUCENE-10175](https://issues.apache.org/jira/browse/LUCENE-10175) by Adrien Grand (@jpountz), updated Dec 15 2021

**Comment by javanna** [comment]
Done in #12101 .
