### ISSUE TITLE
Rename VectorValues#dimension to VectorValues#getNumDimensions? [LUCENE-10177]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11214]
This would make it consistent with PointValues#getNumDimensions.

---
Migrated from [LUCENE-10177](https://issues.apache.org/jira/browse/LUCENE-10177) by Adrien Grand (@jpountz), updated Feb 14 2022

**Comment by msokolov** [comment]
I think we're settled on the current naming at this point
