### ISSUE TITLE
Make TermInSetQuery usable with IndexOrDocValuesQuery [LUCENE-10207]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11244]
IndexOrDocValuesQuery is very useful to pick the right execution mode for a query depending on other bits of the query tree.

We would like to be able to use it to optimize execution of TermInSetQuery. However IndexOrDocValuesQuery only works well if the "index" query can give an estimation of the cost of the query without doing anything expensive (like looking up all terms of the TermInSetQuery in the terms dict). Maybe we could implement it for primary keys (terms.size() == sumDocFreq) by returning the number of terms of the query? Another idea is to multiply the number of terms by the average postings length, though this could be dangerous if the field has a zipfian distribution and some terms have a much higher doc frequency than the average.

@romseygeek and I were discussing this a few weeks ago, and more recently @mikemccand and @gsmiller again independently. So it looks like there is interest in this. Here is an email thread where this was recently discussed: https://lists.apache.org/thread.html/re3b20a486c9a4e66b2ca4a2646e2d3be48535a90cdd95911a8445183%40%3Cdev.lucene.apache.org%3E.

---
Migrated from [LUCENE-10207](https://issues.apache.org/jira/browse/LUCENE-10207) by Adrien Grand (@jpountz), updated Aug 19 2022
Attachments: [LUCENE-10207_multitermquery.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10207/LUCENE-10207_multitermquery.patch)
Pull requests: https://github.com/apache/lucene/pull/435, https://github.com/apache/lucene/pull/1058

**Comment by gsmiller** [comment]
As of #1058, `TermInSetQuery` can now estimate its cost, making it usable with `IndexOrDocValuesQuery` as the index-based query. The already exists `DocValuesTermsQuery` in the sandbox module, which provides a doc-values-based approach that it can be paired with. I've opened #11736 to suggest promoting that functionality out of the sandbox module.

I propose we resolve this issue, capturing the core work of `TermInSetQuery` being able to estimate its cost, which it now does. Let's create spin-off issues (like #11736) for any additional work we'd like to try in this space.
