### ISSUE TITLE
Gradle wrapper validation gh workflow step fails with odd messages [LUCENE-10209]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11246]
I will comment it out for the time being. Don't know what's causing it.

https://github.com/gradle/wrapper-validation-action/issues/46

---
Migrated from [LUCENE-10209](https://issues.apache.org/jira/browse/LUCENE-10209) by Dawid Weiss (@dweiss)

**Comment by dweiss** [comment]
Does not reproduce.
