### ISSUE TITLE
Add support for sparse indexing [LUCENE-10396]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11432]
On Elasticsearch we're more and more leveraging index sorting not as a way to be able to early terminate sorted queries, but as a way to cluster doc IDs that share similar properties so that queries can take advantage of it. For instance imagine you're maintaining a catalog of cars for sale, by sorting by car type, then fuel type then price. Then all cars with the same type, fuel type and similar prices will be stored in a contiguous range of doc IDs. Without index sorting, conjunctions across these 3 fields would be almost a worst-case scenario as every clause might match lots of documents while their intersection might not. With index sorting enabled however, there's only a very small number of calls to advance() that would lead to doc IDs that do not match, because these advance() calls that do not lead to a match would always jump over a large number of doc IDs. I had created that example for ApacheCon last year that demonstrates the benefits of index sorting on conjunctions. In both cases, the index is storing the same data, it just gets different doc ID ordering thanks to index sorting:
![sorted_conjunction.png](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10396/sorted_conjunction.png)

While index sorting can help improve query efficiency out-of-the-box, there is a lot more we can do by taking advantage of the index sort explicitly. For instance `IndexSortSortedNumericDocValuesRangeQuery` can speed up range queries on fields that are primary sort fields by performing a binary search to identify the first and last documents that match the range query. I would like to introduce [sparse indexes](https://en.wikipedia.org/wiki/Database_index#Sparse_index) for fields that are used for index sorting, with the goal of improving the runtime of `IndexSortSortedNumericDocValuesRangeQuery` by making it less I/O intensive and making it easier and more efficient to leverage index sorting to filter on subsequent sort fields. A simple form of a sparse index could consist of storing every N-th values of the fields that are used for index sorting.

 - [x] https://github.com/apache/lucene/pull/13449
 - [x] Add multiple levels to `DocValuesSkipper` to be able to skip many docs at once: https://github.com/apache/lucene/pull/13563
 - [x] Align block boundaries with value changes if possible to have as many constant blocks as possible https://github.com/apache/lucene/pull/13597
 - [x] Take advantage of `DocValuesSkipper` in `SortedSetDocValuesRangeQuery` https://github.com/apache/lucene/pull/13592
 - [ ] #13838

---
Migrated from [LUCENE-10396](https://issues.apache.org/jira/browse/LUCENE-10396) by Adrien Grand (@jpountz), updated Jun 29 2022
Attachments: [sorted_conjunction.png](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-10396/sorted_conjunction.png)
Pull requests: https://github.com/apache/lucene/pull/979

**Comment by bruno-roustant** [comment]
When fields are sorted on numeric values, it could be possible to use a learned-index approach instead of raw binary search, something like the [PGM Index](https://github.com/carrotsearch/hppc/blob/master/hppc/src/main/templates/com/carrotsearch/hppc/KTypePgmIndex.java). It is very compact (something like 0.02% of the indexed values) and 2x to 3x faster than binary search.

**Comment by iverase** [comment]
I am closing this issue as done as most of the items has been done and what is left can be added later.  There are two follow ups:

https://github.com/apache/lucene/issues/13838
https://github.com/apache/lucene/issues/13838
