### ISSUE TITLE
Add fn:fuzzyTerm interval function to flexible query parser [LUCENE-10414]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11450]
Searching for "fuzzy" terms within interval expressions is currently impossible. The Intervals class does expose the necessary low-level machinery to make it happen though.

 

PR: <https://github.com/apache/lucene/pull/668/files>

---
Migrated from [LUCENE-10414](https://issues.apache.org/jira/browse/LUCENE-10414) by Dawid Weiss (@dweiss), updated Feb 10 2022

**Comment by dweiss** [comment]
Merged to 9x and main.
