### ISSUE TITLE
TopN is not being used in getTopChildren() [LUCENE-10538]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11574]
When looking at the overridden implementation getTopChildren(int topN, String dim, String... path) in RangeFacetCounts, I found that the topN parameter is not being used in the code, and the unit tests did not test this function properly. I will create a PR to fix this, and will look into other overridden implementations and see if they have the same issue. Please let me know if there is any question. Thanks!

---
Migrated from [LUCENE-10538](https://issues.apache.org/jira/browse/LUCENE-10538) by Yuting Gan (@Yuti-G), updated May 10 2022

**Comment by gsmiller** [comment]
Let's resolve this out. This issue grew into a few different spin-offs, which are now all resolved. But... it looks like we introduced another case of not properly implementing "top children" with facet sets. I created a specific issue for this to carry it forward: #11742
