### ISSUE TITLE
Weird errors launching gradlew (Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.Object.clone() is applicable for argument types: () values: []) [LUCENE-10548]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11584]
https://bugs.openjdk.java.net/browse/JDK-8285835

I can't reproduce it anywhere, with the same JDK Tobias is using. Seems like clone() is the cause - let's see if we can just get rid of that code and if it helps.

---
Migrated from [LUCENE-10548](https://issues.apache.org/jira/browse/LUCENE-10548) by Dawid Weiss (@dweiss)

**Comment by dweiss** [comment]
Closing, can't reproduce.
