### ISSUE TITLE
Indexing all zero vectors leads to heat death of the universe [LUCENE-10590]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11626]
By accident while testing something else, I ran a luceneutil test indexing 1M 100d vectors where all the vectors were all zeroes. This caused indexing to take a very long time (\~40x normal - it did eventually complete) and the search performance was similarly bad.  We should not degrade by orders of magnitude with even the worst data though.

I'm not entirely sure what the issue is, but perhaps as long as we keep finding hits that are "better" we keep exploring the graph, where better means (score, -docid) >= (lowest score, -docid). If that's right and all docs have the same score, then we probably need to either switch to > (but this could lead to poorer recall in normal cases) or introduce some kind of minimum score threshold?

---
Migrated from [LUCENE-10590](https://issues.apache.org/jira/browse/LUCENE-10590) by Michael Sokolov (@msokolov), updated May 25 2022

**Comment by benwtrent** [comment]
I have confirmed that https://github.com/apache/lucene/pull/12770 fixes this. I used LuceneUtil to index all `0`s and we exit quickly.
