### ISSUE TITLE
Add a Codec class to track merge time of each index part [LUCENE-10670]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11706]
Lucene has applied filter pattern to **Path**, **Codec**, **Reader** etc(FilterPath, FilterCodec, FilterReader) , we should do the same for Writer/Producer/Reader/Consumer/Format(postings, points, doc values, vectors, stored fields, live docs, term vectors) under Codec.

One use case is enabling probe the merge time of different file format by making a FilterCodec that overrides the merge method of each Codec format writer through these filters.

It will allow downstream to add any additional functionality to those classes. 

I have opened up a PR for this use case.  

Any suggestions of different ways to track index parts merge time is welcome.

---
Migrated from [LUCENE-10670](https://issues.apache.org/jira/browse/LUCENE-10670) by Yuan Xiao, updated Aug 12 2022

**Comment by msokolov** [comment]
I think we discussed and decided this approach is not viable. Due to stored fields encoding optimization that relies on instanceof checks we are forbidden from wrapping Codecs.
