### ISSUE TITLE
Issues with Lucene/demo 

### ISSUE THREAD

**Issue by XiaoConstantine** [apache/lucene#11727]
### Description

When I try to run the demo indexer under `lucene/demo/IndexFiles.java` inside IntelliJ, I got following error:
```bash
> Task :lucene:demo:IndexFiles.main() FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module antlr4.runtime not found, required by org.apache.lucene.expressions
29 actionable tasks: 12 executed, 17 up-to-date
```

It's a bit weird to me that seems like `expressions` has proper dependency and module requirments, any pointer would be appreciated, thanks!

### Version and environment details

OS: macos Monterey version 12.5 (Intel Chip)

Java version: 
```bash
❯ java --version
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment Homebrew (build 17.0.4+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.4+0, mixed mode, sharing)
```

**Comment by XiaoConstantine** [comment]
might be the same issue: https://github.com/apache/lucene/issues/11501 (purely from the reported behavior)

**Comment by dweiss** [comment]
I don't think it's a Lucene bug. The module system support is not really shining across IDEs. I can launch that class with no problem if I run via IntelliJ rather than intellij-using-gradle:
![image](https://user-images.githubusercontent.com/199470/187760695-d312427e-5507-4f3a-8364-fe53c3e56d31.png)

**Comment by XiaoConstantine** [comment]
Ah, you are right, after updating my Gradle configuration it works like a charm. Thanks! @dweiss
