### ISSUE TITLE
DV updates files used by a merge could be deleted by other concurrent flushes

### ISSUE THREAD

**Issue by iamorchid** [apache/lucene#11751]
https://github.com/apache/lucene/blob/84cae4f27cfd3feb3bb42d5a9f7ce034f7a31573/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L5075

For merge, I see that the following logic are used to initialize SegmentReader for the merge. Though segments covered in a merge won't be deleted by other concurrent merges, DV updates files could still be overridden by other concurrent flushes and then be deleted after the flush performs IndexFileDeleter#checkpoint(). Though for systems like linux, this won't be a big issue (as an opened file could still be read in process even if it's been deleted). However, for windows, the delete operation would be rejected if the file is still open. So I think a more sensible way is increase the refcount in IndexFileDeleter for the files reference by the merge.
```
      merge.initMergeReaders(
          sci -> {
            final ReadersAndUpdates rld = getPooledInstance(sci, true);
            rld.setIsMerging();
            return rld.getReaderForMerge(context);
          });
```

**Comment by stefanvodita** [comment]
Thanks for the bug report @iamorchid! @guojialiang92 solved this in #13017.
