### ISSUE TITLE
Follow-up refactors to 8-bit quantization change

### ISSUE THREAD

**Issue by jtibshirani** [apache/lucene#11758]
### Description

This issue tracks ideas for refactors as a follow-up to #11613, where we added support for 8-bit vector values:
* We extended `KnnVectorsWriter` to be generic, accepting both `float[]` and `BytesRef` values. It'd be good to explore simplifying the write API to remove these generics.
* We now switch on `VectorEncoding` in several places during graph building and search. Is there a way to encapsulate this better? Maybe there could be a helper class that knows the encoding and can perform distance computations, so that `HnswGraphBuilder` and `HnswGraphSearcher` don't need to know about the encoding.

**Comment by benwtrent** [comment]
There are multiple simplifications now in the quantized byte operations. 

One key thing is that the graph searcher now takes a "vector scorer" object and doesn't care about floats vs bytes.

The API for knn search is cleaner now.

Closing this issue as "done". There are always more simplifications, but we have come a long way in the past year :)
