### ISSUE TITLE
Query optimizer statistics

### ISSUE THREAD

**Issue by patelprateek** [apache/lucene#11765]
### Description

new to lucene usage , I am wondering if there is some internal data structure that lucene maintains to look at filter usage and coverage stats like cpu time it takes to execute the query ?

**Comment by jpountz** [comment]
Lucene has a `QueryProfilerIndexSearcher` that allows to capture some of this information for a given search, but it adds a lot of overhead. The way that Lucene interleaves evaluation of queries doesn't allow tracking statistics in a cheap way.

**Comment by patelprateek** [comment]
@jpountz : After a query runs , i read that lucene uses filter cache where it encodes the posting list using compressed bitmaps (roaring) , is there any api to retrieve these compressed bitmap rather than iterating over the actual document ids ?

My use case is some filters can have possibly large hits (>10 million) and in such scenarios the compressed bitmaps can possibly help for downstream logic . Any recommendations or pointers for any other approaches ? 
For a query is it possible to have a quick dry run to get estimated number of documents it will return ?
