### ISSUE TITLE
KeywordRepeatFilter + OpenNLPLemmatizer Early Exit

### ISSUE THREAD

**Issue by kotman12** [apache/lucene#11771]
### Description

KeywordRepeatFilter + OpenNLPLemmatizer leads to arbitrarily early exit of token stream.

Steps to reproduce: run this [test](https://github.com/kotman12/lucene/blob/illustrate-bug/lucene/analysis/opennlp/src/test/org/apache/lucene/analysis/opennlp/TestOpenNLPLemmatizerFilterFactory.java#L324) and notice how no text below [this line from the test file](https://github.com/kotman12/lucene/blob/illustrate-bug/lucene/analysis/opennlp/src/test-files/org/apache/lucene/analysis/opennlp/data/early-exit-bug-input.txt#L20) gets analyzed.

The root cause appears to be [an extraneous exit condition](https://github.com/kotman12/lucene/blob/illustrate-bug/lucene/analysis/opennlp/src/java/org/apache/lucene/analysis/opennlp/OpenNLPLemmatizerFilter.java#L99) that doesn't play nicely with KeywordRepeatFilter.

This is related to the bug #11735 and is addressed by #11734 

### Version and environment details

latest version of lucene running jdk-17

**Comment by dweiss** [comment]
https://ci-builds.apache.org/job/Lucene/job/Lucene-Check-9.x/3057/

Hmm... this patch applied to 9x fails the tests. Could you take a look at that, @kotman12 ?

**Comment by dweiss** [comment]
I can reproduce those failures with JDK11 but not with JDK17. I didn't look into this deeper.

**Comment by kotman12** [comment]
Very, very interesting .. will take a look

**Comment by kotman12** [comment]
So [this change](https://github.com/apache/lucene/pull/11810/files) seems to fix the test **locally** for me in branch 9x .. Created a PR for the upstream .. not sure how you want to handle the reversion in 9X branch

**Comment by dweiss** [comment]
If this code went in the main branch then it's also a bug there. Comparing strings by reference is a no-no - I should have caught it earlier. I'll do the update on both branches later today.
