### ISSUE TITLE
Fix bugs in HNSW diversity check introduced in LUCENE-10577

### ISSUE THREAD

**Issue by msokolov** [apache/lucene#11782]
### Description

we observed changes in recall that can be traced to these diversity checks done while indexing.

**Comment by msokolov** [comment]
https://github.com/apache/lucene/pull/11781

**Comment by msokolov** [comment]
merged #11781 and cherry-picked to `branch_9x` and `branch_9_4`

**Comment by jtibshirani** [comment]
@msokolov a test case started failing regularly after you merged the change. Here's an example repro line:

```
./gradlew test --tests TestKnnVectorQuery.testFilterWithSameScore -Dtests.seed=1951CEB96E0899ED -Dtests.locale=en-PR -Dtests.timezone=Antarctica/South_Pole -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

**Comment by msokolov** [comment]
Thanks, I had opened https://github.com/apache/lucene/issues/11787. I'm not entirely sure this is unexpected? But maybe the graphs have become sparser somehow??

**Comment by jtibshirani** [comment]
Oh oops, I had missed that. I made a comment on the issue.
