### ISSUE TITLE
cardinality estimation for query filters

### ISSUE THREAD

**Issue by patelprateek** [apache/lucene#11791]
### Description

For large scale data the query filters can take long time to execute and return data . the returned data can also be large like millions of documents . Is there any functionality to be able to get some quick approximate estimate for query filters that can be potentially used to decide whether to run the query or not. 
If not , would like to know any recommendation or ideas on how we can implement or build that functionality ?

**Comment by jpountz** [comment]
The cheapest way to get an estimation of the "cost" of a filter is to run `Weight#scorerSupplier` to retrieve a `ScorerSupplier` and then `ScorerSupplier#cost` to get an estimation of the number of matches of this scorer on the given segment.

**Comment by patelprateek** [comment]
@jpountz : will this work for any query and not just filter ?
Since I am new to lucene , can you please elaborate a bit on how much cheaper would it be relatively to actually running the query or filter on the data ? Also what is the accuracy of this estimation and if you can provide any documentation or pointers to this estimation strategy that will be helpful

**Comment by jpountz** [comment]
Yes, Lucene makes no difference between queries and filters.

It's cheap in the sense that it only performs terms dictionary lookups and quick checks in KD tree indexes but doesn't do more expensive operations like iterating postings or checking KD tree leaves.

**Comment by patelprateek** [comment]
Thanks , that makes sense , will do some benchmarking on my end as well to get better understanding if it fits our sla requirements.
Can you give me some more details on the KD Tree , IIRC KD tree were used for n-dim data points like geo-spatial right  ?

**Comment by patelprateek** [comment]
@jpountz : I do have some question regarding estimation accuracy , usually what i have seen some sketch data structures being used , which have different error bounds based on cardinalities of posting list size. and then on top of that precision degrades on doing set operations (query/filters) . Can you provide me with some pointers or details on is this estimation procedure also probabilistic with different error bounds or this is more accurate (assuming we use non probabilistic sketches like roaring bitmaps) ?

**Comment by jpountz** [comment]
> Can you give me some more details on the KD Tree , IIRC KD tree were used for n-dim data points like geo-spatial right ?

This is correct, we also use them for the 1D case, ie. numeric data.

Cardinality estimation is very inaccurate. For instance for conjunctions (AND), Lucene takes the minimum cost across clauses and for disjunctions (OR), Lucene takes the sum. The only goal it serves in Lucene is figuring out a sensible order in which to evaluate the various clauses of a query. However it's always cheap.
