### ISSUE TITLE
Add FilterDirectory to track write amplification factor

### ISSUE THREAD

**Issue by mdmarshmallow** [apache/lucene#11795]
### Description

I recently opened another issue to lower the allowable delete percentage in `TieredMergePolicy` [here](https://github.com/apache/lucene/issues/11761). One of the concerns that came up in the discussion was the write amplification factor. The goal of this issue is to allow Lucene users to easily track the write amplification factor in their use cases.

**Comment by mdmarshmallow** [comment]
I'm not sure how PR's get automatically linked to the issue, but here is the PR I created: https://github.com/apache/lucene/pull/11796

**Comment by rmuir** [comment]
Closing as the PR has been merged and is in the 9.5.0 section of CHANGES.txt
