### ISSUE TITLE
Add a InterruptedCollector to received thread interrupt request and exit search task early

### ISSUE THREAD

**Issue by caohassl** [apache/lucene#11805]
### Description

hi，

I try to submit a Lucene search task using multiple threads, and when I cancel the search thread, the search task complete normally. But Some search tasks are time-consuming, I wonder if I could exit the search thread early to improve thread utilization.

Expectation:
The expectation is to exit the search thread early when it has been  Interrupted

I have tried {@link TimeLimitingCollector} (https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/TimeLimitingCollector.java) , but the ticksAllowed can not be set too small, so there are some waste of thread utilization still. I wonder if I could add a InterruptedCollector to received interrupt and exit early

**Comment by rmuir** [comment]
no. use of `Thread.interrupt` is not safe because if a thread is blocked on io it will close its file handle in java.

**Comment by uschindler** [comment]
This won't work when the thread is blocked on I/O (e.g. when it reads from IndexInput). Java has the behaviour to close file handles for safety when a thread doing IO was interrupted. When you use this collector the file handle might get closed.
This won't negatively affect MMapDirectory (unless you interrupt at the time of opening the file), but all other implementations will fail.

**Comment by caohassl** [comment]
hi, @uschindler  @rmuir 
Thank you for reply

Yes, we use the MMapDirectory implementation mainly, and Interrupted collect seems to work fine so far.  
I‘m sorry for not considering other implementations
