### ISSUE TITLE
INVALID_SYNTAX_CANNOT_PARSE for at sign (@)

### ISSUE THREAD

**Issue by gcbaptista** [apache/lucene#11800]
### Description

Since release `9.1.0`, Lucene's SyntaxParser have been uncapable to parse `@` in a query, throwing a Syntax Error (`INVALID_SYNTAX_CANNOT_PARSE`).
Version `9.0.0` is the last I tested that still can parse this character.

Two similar examples that throw `INVALID_SYNTAX_CANNOT_PARSE` in `9.1.0`, but not in `9.0.0`:
 - `\\ an@tomy`
 - `\\ @natomy`

Leaving some log dump here:
```
Syntax Error, cannot parse \\ an@tomy:  
INVALID_SYNTAX_CANNOT_PARSE: Syntax Error, cannot parse \\ an@tomy:  
	at org.apache.lucene.queryparser.flexible.standard.parser.StandardSyntaxParser.generateParseException(StandardSyntaxParser.java:2093)
	at org.apache.lucene.queryparser.flexible.standard.parser.StandardSyntaxParser.jj_consume_token(StandardSyntaxParser.java:1961)
	at org.apache.lucene.queryparser.flexible.standard.parser.StandardSyntaxParser.TopLevelQuery(StandardSyntaxParser.java:115)
	at org.apache.lucene.queryparser.flexible.standard.parser.StandardSyntaxParser.parse(StandardSyntaxParser.java:92)
	at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:214)
	at org.apache.lucene.queryparser.flexible.standard.StandardQueryParser.parse(StandardQueryParser.java:280)
        ...
```

### Version and environment details

- JDK: temurin-17.0.3
- OS: MacOS Monterey 12.6 and alpine-java17:latest (docker image)
- Lucene: 9.1.0

**Comment by rmuir** [comment]
not a bug, but related to new features added to the parser. see the associated message in `MIGRATE.txt`:

```
## Minor syntactical changes in StandardQueryParser (Lucene 9.1)

LUCENE-10223 adds interval functions and min-should-match support to StandardQueryParser. This
means that interval function prefixes ("fn:") and the '@' character after parentheses will
parse differently than before. If you need the exact previous behavior, clone the StandardSyntaxParser from the previous version of Lucene and create a custom query parser
with that parser.
```

**Comment by dweiss** [comment]
Also, please note that you can quote the ampersand in terms - this will behave like before. I don't think it's a bug, sorry it caused you trouble but the new functionality is worth it (try it!).

**Comment by gcbaptista** [comment]
Hey again,
So if I want my queries to support `@`, what should be my approach to keep the parsing compatibility from this version on?
If there is no way to parse it right now, how should one escape the character? Would the regular escaping `\\` be enough in this case?

**Comment by dweiss** [comment]
You can escape the at character:
```
am\@zing
```
or you can quote the term:
```
"am\@zing"
```
Or you can set up flexible query parser with your own syntax parser (which you'd source from a previous Lucene version).

**Comment by gcbaptista** [comment]
So why isn't this method escaping `@` then?

https://github.com/apache/lucene/blob/5b24a233bdfd2c1feb177a5de4fc5eb62baf6015/lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParserBase.java#L965-L978

**Comment by dweiss** [comment]
Note this class is in a different package - it's a different query parser. There are many. They all behave differently. It's a project with long history.

**Comment by gcbaptista** [comment]
OK, thank you very much for the clarification 👍
