### ISSUE TITLE
input automaton is too large  for lengthy wildcard query

### ISSUE THREAD

**Issue by taroplus** [apache/lucene#11809]
### Description

Hello, I have a very lengthy string to search with, basically 

```
String term = "very-lengthy-text-contains-dots-and-dashes";
```

When I try to create a WildcardQuery like below, I get java.lang.IllegalArgumentException: input automaton is too large: 1001

```
WildcardQuery query = new WildcardQuery(new Term("field", term + "*"));
```

exception looks like this
```
java.lang.IllegalArgumentException: input automaton is too large: 1001

	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1060)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
```

Actual string I have is below
```
"{group-bm-http-server-02083.node.dm.reg,group-bm-http-server-02082.node.dm.reg,group-bm-http-server-02081.node.dm.reg,group-bm-http-server-02080.node.dm.reg,group-bm-http-server-02079.node.dm.reg,group-bm-http-server-02078.node.dm.reg,group-bm-http-server-02077.node.dm.reg,group-bm-http-server-02076.node.dm.reg,group-bm-http-server-02073.node.dm.reg,group-bm-http-server-02070.node.dm.reg,group-bm-http-server-02067.node.dm.reg,group-bm-http-server-02064.node.dm.reg,group-bm-http-server-02029.node.dm.reg,group-bm-http-server-02028.node.dm.reg,group-bm-http-server-02027.node.dm.reg,group-bm-http-server-02026.node.dm.reg,group-bm-http-server-02025.node.dm.reg,group-bm-http-server-02023.node.dm.reg,group-bm-http-server-02022.node.dm.reg,group-bm-http-server-02021.node.dm.reg,group-bm-http-server-02020.node.dm.reg,group-bm-http-server-02019.node.dm.reg,group-bm-http-server-02018.node.dm.reg,group-bm-http-server-02016.node.dm.reg,group-bm-http-server-02015.node.dm.reg,group-bm-http-server-02014.node.dm.reg,group-bm-http-server-02009.node.dm.reg,group-bm-http-server-02007.node.dm.reg,group-bm-http-server-02004.node.dm.reg,group-bm-http-server-02003.node.dm.reg,group-bm-http-server-02002.node.dm.reg,group-bm-http-server-01311.node.dm.reg,group-bm-http-server-01309.node.dm.reg,group-bm-http-server-01307.node.dm.reg}"
```

i know it's not a ordinal situation, however, I'm not sure why Automaton compilation needs to go that deep when there's no `*` or `?` except the last one.

### Version and environment details

Lucene 8.11.1 / Java 8

**Comment by rmuir** [comment]
not sure it is still an issue for `main` branch as i don't have the full stacktrace. however i would recommend using TermInSetQuery instead of the large regex you have that seems to represent a simple set of string values. It should be more performant.

**Comment by taroplus** [comment]
stacktrace is long
```
java.lang.IllegalArgumentException: input automaton is too large: 1001

	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1066)
        <thousand of this>
	at org.apache.lucene.util.automaton.Operations.isFinite(Operations.java:1049)
	at org.apache.lucene.util.automaton.CompiledAutomaton.<init>(CompiledAutomaton.java:224)
	at org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:108)
	at org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:86)
	at org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:71)
	at org.apache.lucene.search.WildcardQuery.<init>(WildcardQuery.java:56)
```
i'll test with the latest master

**Comment by taroplus** [comment]
Tried with the latest commit, it happens. it's not regex, it's just `*` after a plain text. I'm just trying to run a prefix query (same happens with PrefixQuery too)

**Comment by rmuir** [comment]
ok, thanks for reporting. I will dig more into this.

The problem is that `isFinite` is implemented recursively, so we have a defensive check that you are hitting, due to the length of the string. See https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/automaton/Operations.java#L1056-L1057

For PrefixQuery, we shouldn't even be calculating `isFinite`: its implicitly infinite.
For WildcardQuery, we could avoid calculating `isFinite`: if we ever see `*` operator, its infinite, otherwise its finite.

and of course, it would be great to implement this function without recursion at some point. but i'm not sure its needed to solve your issue.

**Comment by rmuir** [comment]
Thanks for reporting this with easy-to-reproduce testcase @taroplus
