### ISSUE TITLE
Fix Java 19 MR-JAR compilation in IDEs

### ISSUE THREAD

**Issue by uschindler** [apache/lucene#11819]
### Description

After merge of #912 when creating the Eclipse workspace files, it also adds the Java 19 part (`core/src/java19`), which fails to compile with JDK 11 or 17. I think the same will be happing with Intellij and others.

For exclipse we can exclude the source set, but this would mean you can't edit the source files with syntax highlighting and compilation checks (but you still see them). For me this would be fine, when I need to touch the Java 19 imple, I can read the source folder to build path, so maybe excluding is the best option. On the other hand, the failing compilation does not hur functionality of Eclipse. If you don't like it just right-click on the `core/src/java19` folder and select "Build path -> Remove from build path".

I have no idea about Intellij - @dweiss ?

What do other think? Just hide the source sets for Java 19 (and the ones for 20 and 21 coming later?).

**Comment by uschindler** [comment]
Here is the fix for Eclipse: #11823

**Comment by uschindler** [comment]
I merged the Eclipse part. Robert yesterday tried to get hold of IDEA, but it looks like it is "mostly working" if you set the Java versions correctly (to 19). It looks like Idea picks per source folder the correct Java version, but it messed up compilation.

Of course, in both cases you need Java 19 added as IDE in Eclipse and IDEA if you want to edit the Java 19 features.

**Comment by rmuir** [comment]
i tried wrestling with it, but i'm not sure i even held it properly. ultimately i was able to get it to work by setting entire project to java 19. this works for now, because "mr-jar" is not "really" used (there are no duplicate classes)

**Comment by dweiss** [comment]
(away until the next of the week, guys - out of reach). bb on sunday.

**Comment by uschindler** [comment]
I have a solution for Intellij Idea: #11836 
This variant disables compilation of the MR-JAR sourceSets (like in Eclipse).
