### ISSUE TITLE
smoketester needs to run 'gradlew localSettings' first

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11820]
### Description

smoketester runs gradle which generates a `gradle.properties` but it isn't picked up, which causes it to fail. I think if we just ran `gradlew localSettings` first, then it would actually use the `gradle.properties` that it generates?

```
> Task :localSettings

IMPORTANT. This is the first time you ran the build. I wrote some sane defaults (for this machine) to 'gradle.properties', they will be picked up on consecutive gradle invocations (not this one).

Run gradlew :helpLocalSettings for more information.

> Task :missing-doclet:compileJava
> Task :missing-doclet:processResources NO-SOURCE
> Task :missing-doclet:classes
> Task :missing-doclet:jar
> Task :gitStatus

> Task :errorProneSkipped
WARNING: errorprone disabled (skipped on builds not running inside CI environments, pass -Pvalidation.errorprone=true to enable)

> Task :lucene:core:compileJava

> Task :lucene:core:processResources
> Task :lucene:core:classes
> Task :lucene:core:compileMain19Java FAILED
```

**Comment by rmuir** [comment]
To be clear, i set `JAVA19_HOME` env var, but gradle doesn't pick it up because it hasn't "pulled in" the `gradle.properties`, then it fails because it can't find java 19. I have `org.gradle.java.installations.auto-download=false` set in my `~/.gradle/gradle.properties` because i'm not allowing gradle to download JVMs.

**Comment by uschindler** [comment]
Yes, on Github CI jobs we do exactly this: https://github.com/apache/lucene/blob/ac12cd9f176bf50bc80f1d7528f4c35d5ad22adf/.github/workflows/distribution.yml#L37-L44

I agree this should be fixed, but that's not a showstopper. With default settings of gradle all works, it just breaks if auto-provisioning was disabled globally like on your computer.

**Comment by uschindler** [comment]
Let's just add this additional exec before it executes `gradlew` for the first time.

**Comment by uschindler** [comment]
Something like this would be fine:
```python
    validateCmd = './gradlew --no-daemon localSettings'
    print('    run "%s"' % validateCmd)
    java.run_java17(validateCmd, '%s/validate.log' % unpackPath)
```

**Comment by uschindler** [comment]
Anyways we should fix gradlew somehow to make sure the settings file is there and restart itsself. Maybe it should also check for updates of settings. Because once you wrote the gradle.properties file it won't be updated anymore.

**Comment by uschindler** [comment]
I have a simple PR: #11826

We can introduce more advanced solutions like editing gradlew.sh/bat later. This should fix the issue.

**Comment by rmuir** [comment]
thanks @uschindler ! it works now without any hassles.
