### ISSUE TITLE
gradle aggregate coverage report

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11839]
### Description

Currently, when running the build (e.g. `gradlew coverage`) you get a per-module report.

Ideally we'd produce an aggregate report (similar to what black magic jenkins is doing: https://ci-builds.apache.org/job/Lucene/job/Lucene-Coverage-main/lastSuccessfulBuild/jacoco/

It would be great to also print the summary to the console (same as #11837). 

This would be nice, a single artifact of the code coverage for a build. For example, It could eventually be archived as a github action to help us better inspect PRs.

**Comment by zhaih** [comment]
@rmuir I can work on it if you don't want to do it right now?

**Comment by rmuir** [comment]
@zhaih please take it!
