### ISSUE TITLE
Add a FilterIndexOutput

### ISSUE THREAD

**Issue by mdmarshmallow** [apache/lucene#11868]
### Description

We have several subclasses of `IndexOutput` that have delegates, most recently one was added in this PR: https://github.com/apache/lucene/pull/11796. Adding a `FilterIndexOutput`, similar to `FilterDirectory`, to make sure all these delegators get tested properly would be a good idea. (suggested by @mikemccand here: https://github.com/apache/lucene/pull/11796/files#r1000886175).

**Comment by jpountz** [comment]
Let's do `FilterIndexInput` at the same time?

**Comment by mdmarshmallow** [comment]
Sounds good, I just started working on this and will make sure to add `FilterIndexInput` as well.

**Comment by mdmarshmallow** [comment]
Here's the PR: https://github.com/apache/lucene/pull/11958

**Comment by mikemccand** [comment]
I think this issue was closed with the above PR?  Thank you @mdmarshmallow!
