### ISSUE TITLE
ArrayIndexOutOfBoundException

### ISSUE THREAD

**Issue by akhgeek30** [apache/lucene#11864]
### Description

Steps to reproduce
1. Query = abc-ghi
2. Create a synonym file as
Synonym.txt = {
abc,def
ghi,jkl
}

3. Schema to be followed
managed-schema
`
analyzer type="query"

      tokenizer class="solr.WhitespaceTokenizerFactory"

      filter class="solr.LowerCaseFilterFactory"

      filter class="solr.WordDelimiterGraphFilterFactory" types="word_dlimiters.txt" generateNumberParts="0" stemEnglishPossessive="0" splitOnCaseChange="0" preserveOriginal="0" catenateAll="1" catenateWords="1" catenateNumbers="1" protected="protwordsSpecial.txt" generateWordParts="1" splitOnNumerics="0"

      filter class="solr.FlattenGraphFilterFactory"

      filter class="solr.SynonymGraphFilterFactory" expand="true" ignoreCase="true" synonyms="synonyms.txt" 

      filter class="solr.FlattenGraphFilterFactory"

/analyzer
`

Error :
`java.lang.ArrayIndexOutOfBoundsException: 0\r\n\tat org.apache.lucene.util.QueryBuilder.newSynonymQuery(QueryBuilder.java:653)\r\n\tat org.apache.solr.parser.SolrQueryParserBase.newSynonymQuery(SolrQueryParserBase.java:617)\r\n\tat org.apache.lucene.util.QueryBuilder.analyzeGraphBoolean(QueryBuilder.java:533)\r\n\tat org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:320)\r\n\tat org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:240)\r\n\tat org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:524)\r\n\tat org.apache.solr.parser.QueryParser.newFieldQuery(QueryParser.java:62)\r\n\tat org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:1072)\r\n\tat org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:806)\r\n\tat org.apache.solr.parser.QueryParser.Term(QueryParser.java:421)\r\n\tat org.apache.solr.parser.QueryParser.Clause(QueryParser.java:278)\r\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)\r\n\tat org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)\r\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:222)\r\n\tat org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)\r\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)\r\n\tat org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)\r\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:162)\r\n\tat org.apache.solr.parser.QueryParser.Clause(QueryParser.java:282)\r\n\tat org.apache.solr.parser.QueryParser.Query(QueryParser.java:222)\r\n\tat org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:131)\r\n\tat org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:260)\r\n\tat org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:49)\r\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:173)\r\n\tat org.apache.solr.search.ExtendedDismaxQParser.getBoostQueries(ExtendedDismaxQParser.java:566)\r\n\tat org.apache.solr.search.ExtendedDismaxQParser.parse(ExtendedDismaxQParser.java:187)\r\n\tat org.apache.solr.search.QParser.getQuery(QParser.java:173)\r\n\tat org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:159)\r\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:272)\r\n\tat `

**Found Issue in org/apache/lucene/util/QueryBuilder.java**

protected Query newSynonymQuery(Term terms[]) {
    SynonymQuery.Builder builder = new SynonymQuery.Builder(**_terms[0].field()_**);
    for (Term term : terms) {
      builder.addTerm(term);
    }
    return builder.build();
  }
	 

### Version and environment details

Version > 8.0.0

**Comment by romseygeek** [comment]
I think this is a bug in the SolrQueryParserBase, rather than in Lucene?  The callsites within lucene's QueryBuilder all check that they only call `newSynonymQuery` with a non-empty list.  You can report the bug at https://github.com/apache/solr

Having said that, this is a trappy API.  I wonder if we should change the signature of `newSynonymQuery` to take a field and a list of BytesRef (or rather BytesRefAndBoost, given that we allow settings boosts on individual terms now), and also update `SynonymQuery.Builder#addTerm` to take a BytesRef rather than a Term.  Currently we're adding the same field over and over again which adds a bunch of unnecessary ceremony to building the query.

**Comment by akhgeek30** [comment]
@romseygeek It might be possible the bug is present at SOLR but do you think hardcoding the value inside the newSynonymQuery method is feasible if the list is empty? In the method analyzeGraphBoolean method if the terms.length == 0 or terms.length > 1 it goes into an else condition, so if the terms.length == 0, it will definitely throw the error.

**Comment by mmatela** [comment]
Really doesn't look like a problem in SOLR. `QueryBuilder.analyzeGraphBoolean()` creates a `GraphTokenStreamFiniteStrings` (also Lucene class), retrieves a terms list from it and doesn't check if it's empty (there is only an `assert` which turns out to be invalid).

There's more analysis of when this happens in https://github.com/elastic/elasticsearch/issues/46272 and it points to https://github.com/apache/lucene/issues/9763 as a potential way forward.

**Comment by mmatela** [comment]
In my case the exception occurred with filters `WordDelimiterGraphFilter > FlattenGraphFilter > StopFilter`, but it started to work when `StopFilter` was moved before `FlattenGraph`. I wonder if this is a real fix or the problem will resurface for other queries...

`StopFilter` is very simple so it should work fine on a graph, but if it's the `SynonymGraphFilter` causing problems for OP it may be not be a feasible workaround. But still might be worth trying out.

**Comment by akhgeek30** [comment]
@mmatela Initial WDGF > SGF > FGF was present. I thought it would be feasible to flatten the result from WDGF and then push it to SGF. But the result was same.

**Comment by romseygeek** [comment]
Ah, I see what you mean.  I think we can improve the internal API here to not rely on there being a non-empty TermAndBoost array when constructing the synonym query.  I'll open a pull request.  #9763 is a bigger problem, unfortunately.
