### ISSUE TITLE
Refactor and generalize file deleter

### ISSUE THREAD

**Issue by zhaih** [apache/lucene#11885]
### Description

As far as I know there're 2 file deleters inside lucene, one is `IndexFileDeleter` which is package private and only used by `IndexWriter`, another is `ReplicaFileDelter` which is also package private and only used by `ReplicaNode`, and they shares quite a lot of common functionalities but none of them are made available as public use so when I am looking for an option of implemented file deleter the seemingly only one is to fork the `ReplicaFileDeleter` if I don't want to use `nrt` module. (Please suggest if there's a better way!)

I would like to:
1. Generalize those two file deleter into one and make it a public class
2. Probably make a directory wrapper or make it an option in StandardDirectoryReader so that we're able to delete expired index files even when we're not in NRT mode.

**Comment by rmuir** [comment]
would be cool to see what you have in mind. personally i find the `IndexFileDeleter` terrifying: it does have an appropriately scary name, you can't argue with that! We have to proceed with caution here, I think there might be dragons.

I'm still seeing a common test failure of `IndexFileDeleter`'s reference counting, but havent been able to reproduce or open a ticket. Proceed with caution :)
