### ISSUE TITLE
Remove QueryTimeout#isTimeoutEnabled?

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#11914]
I don't understand well why `QueryTimeout` has a `isTimeoutEnabled` method. If the timeout is not enabled, why configure a timeout at all?

**Comment by shubhamvishu** [comment]
I can work on it. But to understand better, I see this being used in `ExitableDirectoryReader` where conditionally the `ExitableXYZ` wrapper is returned for `XYZ` class. Could this be to conditionally turn off the timeout so timeout could be used only if required else it could be turned off or something ?. Just my initial thought from the issue description.

**Comment by jpountz** [comment]
@shubhamvishu Yes, my thinking was to push the responsibility to the caller and only wrap with an `ExitableDirectoryReader` if there is actually a timeout.
