### ISSUE TITLE
Can we improve MMapDir's exceptions for invalid offsets?

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11912]
### Description

For #11905 bug, as an example, the user may get a generic exception "Seek Past EOF".

Can we improve it to include the bogus position? For example, If you can see that offset is negative, it is faster to debug. I think the new MMapDir already has some improvements here. Better error messages would help not just people debugging real world problems, but also developers making new stuff and debugging tests.

cc: @uschindler

**Comment by uschindler** [comment]
Maybe include that in 9.4.3 ?

**Comment by uschindler** [comment]
Will do that tomorrow, PR will come. We can decide to add it to 9.4 branch to make later debugging.of broken code with recent vectors easier.
