### ISSUE TITLE
gradle build uses excessive resources on multi-core machine

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11924]
### Description

on e.g. an 8-core machine, gradle might spin up 4 jvms by default. but each jvm is ergonomically sized for an 8-core machine. so you get `8 * 4 = 32` "threads" or whatever it may be. 

solution, pass: `-XX:ActiveProcessorCount=1` to each jvm we fork, so that it sizes compiler, gc, threadpools appropriately.

on my machine, i've been passing this via `org.gradle.jvmargs` and `tests.jvmargs` for over a year. but we need to default this on. it is still missing from some forked jvms (e.g. javadoc), and when these run, my computer becomes unresponsive because resources are allocated incorrectly.

I opened this issue before, but I don't think I was able to communicate both the issue and how bad it is. Let's fix it this time.

**Comment by rmuir** [comment]
Basically this behavior grows `O(n)^2` where n is the number of cpus. The more you have, the more this is slowing you down.

**Comment by rmuir** [comment]
one important thing when passing this flag, is to also configure the GC too, else you get serialgc on a 1-cpu jvm. But we should always be setting the JVM anyway (to ParallelGC) for builds. G1 is just throwing cpu cycles on the floor.

**Comment by madrob** [comment]
That's a super interesting observation, do you think we should also report it to gradle?

**Comment by dweiss** [comment]
Depends what all those threads are doing... For I/O bound jobs they're idle most of the time. But I agree it's wasteful, it's fine to change the defaults.

**Comment by rmuir** [comment]
Yes, for background I think the flag was added with docker usages in mind: https://bugs.openjdk.org/browse/JDK-8189497

But the idea is the same here. Since we're making the build go parallel with multiple jvms (e.g. 4), let's prevent from overwhelming the machine. For this issue i would suggest adding `-XX:ActiveProcessorCount=1` to:
* `gradle/hacks/turbocharge-jvm-opts.gradle`
* `gradle/testing/defaults-tests.gradle`
* `help/localSettings.txt`

This way, the many forked jvms that we spin up only have smaller number of compiler/gc threads/default threadpool sizes each.   The issue is especially exacerbated by #11925, because we're still enabling things like C2 compiler there, so the many forked error-prone-monkey-patched-javac tasks all waste a ton of cpu for no good reason. But currently I don't have enough gradle kung-fu to figure out how to pass jvm args to the error-prone :)
