### ISSUE TITLE
one-time pass thru error-prone NarrowingCompoundAssignment check

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11932]
### Description

A great overflow issue: https://errorprone.info/bugpattern/NarrowingCompoundAssignment

javac is getting its own checker for this in version 20 so eventually we can switch to that one. But for now, i'd like to try to enable the error-prone version.

in a nutshell, compound assignment operators are totally lenient:
```
jshell> byte x = 0;
x ==> 0

jshell> x = x + Long.MAX_VALUE;
|  Error:
|  incompatible types: possible lossy conversion from long to byte
|  x = x + Long.MAX_VALUE;
|      ^----------------^

jshell> x += Long.MAX_VALUE;
$2 ==> -1
```

**Comment by rmuir** [comment]
There's a fair amount of noise to the check (a lot of code uses these operators to do crazy bit twiddling stuff etc), but it finds some good stuff that we should obviously fix. including at least another overflow in vectors :)

**Comment by rmuir** [comment]
Here's a log of the output from the new check: [overflow.log](https://github.com/apache/lucene/files/10014404/overflow.log)

I think it is too noisy to worry about fixing all the code. I plan to do a single pass through it and fix anything that looks "real". For example places where, `int` accumulator is accidentally used to sum up `long` values with `+=`. In these cases the wrong type was used but java threw away all safety thanks to `+=`.

Example: 
```
/home/rmuir/workspace/lucene/lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsWriter.java:141: warning: [NarrowingCompoundAssignment] Compound assignments from long to int hide lossy casts
        totalCost += sub.values.cost();
                  ^
    (see https://errorprone.info/bugpattern/NarrowingCompoundAssignment)
  Did you mean 'totalCost = (int) (totalCost + sub.values.cost());'?
```
In this case KnnVectorsWriter `totalCost` should simply be a `long` instead of `int`. 

Another similar one:
```
/home/rmuir/workspace/lucene/lucene/core/src/java/org/apache/lucene/util/OfflineSorter.java:302: warning: [NarrowingCompoundAssignment] Compound assignments from long to int hide lossy casts
        sortInfo.lineCount += part.count;
```
In this case we should change `sortInfo.lineCount` to be a `long` instead of `int`.

**Comment by jpountz** [comment]
I'll look into this log.
