### ISSUE TITLE
Remove IOContext from `Directory#openChecksumInput`?

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#11933]
`ChecksumIndexInput` only allows reading files sequentially, so the only `IOContext` that makes sense is `IOContext.READONCE`?

**Comment by uschindler** [comment]
Hi,
I think the idea of IOContext was beyond simple flags like "sequentially reading" or "random IO" (and you can create your own IOContexts). I think we added that to allow full flexibility. For the checkum case it may be predefined, so yes, we could think of removing the argument. 

I am +/-0 for removing it, on the other hand it does not hurt to have it for future extensibility. Do you have something in mind where it may hinder us?

**Comment by uschindler** [comment]
I think we can remove it, but if we keep it maybe it should always use READONCE.

**Comment by mikemccand** [comment]
+1 to remove it.
