### ISSUE TITLE
try to re-enable error-prone checks to happen more often?

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11943]
### Description

Currently this is enabled nightly-only, and it is very slow compared to java compiler. I wonder if we could enable it "more often" somehow. Besides being slow it also has some compatibility issues with different JDK versions I think, or at least it has in the past. So this could be a problem to an actual end-user of lucene...

We sped it up with #11937 and it no longer dominates the whole machine in such a way that you can't move the mouse pointer when it runs.

Maybe it could be sped up more if we disabled additional checks. I feel like the way we denylist checks, new checks sneak in that we may not want on upgrading it, making it slower.

Maybe a compromise would be to enable it just for github actions?

**Comment by dweiss** [comment]
> Maybe a compromise would be to enable it just for github actions?

I'm fine with this. Doesn't bother me to push and do something else while waiting for CI to complete its checks.

**Comment by rmuir** [comment]
Looks like we tend to spin off two "big" jobs in parallel: `gradle test` and `gradle check -x test`. The `gradle test` job tends to run a bit slower already, so it may not hurt overall "throughput" much to enable it on the `gradle check -x test` precommit job. I'll put out a PR.

**Comment by rmuir** [comment]
error-prone is already enabled via ci-detection magic :)

**Comment by dweiss** [comment]
Ahem. Right. Now, where's that facepalm emoji...
