### ISSUE TITLE
Replace custom String constructor from codepoints with constructor within java.lang.String class.

### ISSUE THREAD

**Issue by xtonik** [apache/lucene#11996]
### Description

Custom implementation is neither correct (see below) nor efficient (due to char array reallocation at least). True reason of creation custom implementation is according to related [git commit](https://github.com/apache/lucene/commit/972da5872fabbc0cd12fa2e12171be8e24f665fa)  bugs presence in original implementation, but it seems, that they were already [fixed](https://bugs.openjdk.org/browse/JDK-6588260). Exact related commit message part is _fix sneaky bugs (workaround java's bug in new String(int[], int, int);_ without more specific information about bugs, so this must be verified whether all present bugs have been really fixed.

Examples of incorrectness:
- method argument `offset` is not checked to be positive
- catching exception in normal program flow
- throwing inappropriate exceptions

**Comment by rmuir** [comment]
It's obvious you are a troll and don't know what you are talking about. We add such workarounds because we have to, not for fun. If youd like to be productive on this matter go write some tests for openjdk... They clearly need them

**Comment by xtonik** [comment]
It's obvious you are completely out of reality. Do you think I spend my free time to do such things? If you are so clever, explain what is wrong with original implementation, I have not found any details about mentioned bugs - this should be clearly described in commit message or elsewhere - based on this information it is possible to write test, not so without. And last but not least there is written remark about necessity of verification of my suggestion.
About my comments about incorrectness of custom implementation - it is evident, that I have right on first look to source code.
I went through early whole Lucene project to find something worthy to contribute I really don't realize that I get so much disgusting response, I have prepared some other proposals, but I don't want communicate with other developers in such way so I will not continue to cooperate in this project anymore.
