### ISSUE TITLE
Lucene-facet leaves ThreadLocal that creates a memory leak

### ISSUE THREAD

**Issue by gvaysman-at-github** [apache/lucene#12000]
### Description

When the web application that uses Lucene Facets is shut down (say, from Tomcat Manager app), ThreadLocal<BytesRefBuilder> from UTF8TaxonomyWriterCache (the field bytes) is never cleaned up.

As a result, not only Tomcat complains of possible thread leak, the heap dump confirms this (below).

The code examination (including the latest lucene-facet 9.4.2) shows no bytes.remove() anywhere. Just clearing the BytesRefBuilder internal array is not sufficient.

Tomcat outputs to the console the following:

   SEVERE [Thread-213] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [mh] created a ThreadLocal with key of type [org.apache.lucene.facet.taxonomy.writercache.UTF8TaxonomyWriterCache$1] (value [org.apache.lucene.facet.taxonomy.writercache.UTF8TaxonomyWriterCache$1@4c6f99ab]) and a value of type [org.apache.lucene.util.BytesRefBuilder] (value [Unknown]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Heap dump shows that the web app class loader, with all statics, etc. (unrelated to Lucene), cannot be released because of this leak

 
![LuceneThreadLocalLeak](https://user-images.githubusercontent.com/120044372/206240629-1b9619af-1d3a-4ed1-846c-ec0815ce600b.png)

**Comment by rmuir** [comment]
Thanks @gvaysman-at-github for reporting this. I was unaware of this threadlocal, indeed it looks problematic just from the description in this cache:

```
/** A "cache" that never frees memory, and stores labels in a BytesRefHash (utf-8 encoding). */
public final class UTF8TaxonomyWriterCache implements TaxonomyWriterCache, Accountable {
  private final ThreadLocal<BytesRefBuilder> bytes =
      new ThreadLocal<BytesRefBuilder>() {
        @Override
        protected BytesRefBuilder initialValue() {
          return new BytesRefBuilder();
        }
      };
```

**Comment by rmuir** [comment]
The UTF8TaxonomyWriterCache does have a `public void close() {}` but I'm not sure when/if it gets invoked as I'm not familiar with this cache and will need to look more into it. But one possibility to fix this cache is to replace the ThreadLocal with CloseableThreadLocal, and close it out in `close()`.

**Comment by rmuir** [comment]
A possible workaround for now might be to configure `LruTaxonomyWriterCache` instead of the default `UTF8TaxonomyWriterCache`. The LRU-based implementation doesn't use any threadlocals.

**Comment by vigyasharma** [comment]
> But one possibility to fix this cache is to replace the ThreadLocal with CloseableThreadLocal, and close it out in close()

`DirectoryTaxonomyWriter` does call `cache.close()` when it gets closed (via `closeResources()`), so I think this is a good idea. 

I updated the cache to use CloseableThreadLocal. Don't have a good way to test for a memory leak, but I added a test to atleast verify that threadlocal memory is removed on close.

**Comment by vigyasharma** [comment]
Removed UTF8TaxonomyWriterCache from main, and deprecated it in 9.x. We now default to LruTaxonomyWriterCache. PRs have been merged in. Closing this issue.
