### ISSUE TITLE
Mechanism to interrupt long-running/resource intensive queries

### ISSUE THREAD

**Issue by Bukhtawar** [apache/lucene#12023]
### Description

As a part of https://github.com/opensearch-project/OpenSearch/issues/687 we detected that regex queries can run into tight loops for quite long. Below is the stack trace of the request for a wildcard query which consumed 100% CPU for an hour(although addressed in https://issues.apache.org/jira/browse/LUCENE-9981). 
OpenSearch has a mechanism to cancel task on timeout and one other option that was we were deliberating was to send interrupts to the long running thread if the request is consuming more Memory/CPU or time, independent of query timeout. 
The problem is not all costly executions in Lucene have a check on interrupts much like ExitableDirectoryReader#checkAndThrow

```
private void checkAndThrow() {
      if (queryTimeout.shouldExit()) {
        throw new ExitingReaderException("The request took too long to iterate over point values. Timeout: "
            + queryTimeout.toString()
            + ", PointValues=" + in
        );
      } else if (Thread.interrupted()) {
        throw new ExitingReaderException("Interrupted while iterating over point values. PointValues=" + in);
      }
    }
```

Sharing the stack trace for the request
```
100.2% (500.8ms out of 500ms) cpu usage by thread 'opensearch[917451917ca5731579187db45dd52853][search][T#5]'
     4/10 snapshots sharing following 36 elements
       app//org.apache.lucene.util.automaton.Operations.determinize(Operations.java:780)
       app//org.apache.lucene.util.automaton.Operations.getCommonSuffixBytesRef(Operations.java:1155)
       app//org.apache.lucene.util.automaton.CompiledAutomaton.<init>(CompiledAutomaton.java:245)
       app//org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:110)
       app//org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:87)
       app//org.apache.lucene.search.AutomatonQuery.<init>(AutomatonQuery.java:71)
       app//org.apache.lucene.search.WildcardQuery.<init>(WildcardQuery.java:56)
       app//org.opensearch.index.mapper.StringFieldType.wildcardQuery(StringFieldType.java:158)
       app//org.opensearch.index.query.WildcardQueryBuilder.doToQuery(WildcardQueryBuilder.java:259)
       app//org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:116)
       app//org.opensearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:337)
       app//org.opensearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:321)
       app//org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:116)
       app//org.opensearch.index.query.QueryShardContext.lambda$toQuery$3(QueryShardContext.java:386)
       app//org.opensearch.index.query.QueryShardContext$$Lambda$5010/0x0000000801d4d840.apply(Unknown Source)
       app//org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:398)
       app//org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:385)
       app//org.opensearch.search.SearchService.parseSource(SearchService.java:903)
       app//org.opensearch.search.SearchService.createContext(SearchService.java:740)
       app//org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:442)
       app//org.opensearch.search.SearchService.access$500(SearchService.java:155)
       app//org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:415)
       app//org.opensearch.search.SearchService$2$$Lambda$4889/0x0000000801ce9840.get(Unknown Source)
       app//org.opensearch.search.SearchService$$Lambda$4891/0x0000000801ce9c40.get(Unknown Source)
       app//org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:71)
       app//org.opensearch.action.ActionRunnable$$Lambda$3741/0x00000008011fa440.accept(Unknown Source)
       app//org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:86)
       app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
       app//org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78)
       app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
       app//org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:57)
       app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:774)
       app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:50)
       java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
```

Wanted to gather thoughts on exposing query cancellation controls like interrupts in Lucene for some of the expensive queries

**Comment by Bukhtawar** [comment]
Thanks @rmuir I am aware this has been addressed, this issue was to primarily gather thoughts on other possible queries similar to this that might be expensive or running tight loops but lacking interrupts or a good way to short circuit and ways that to cancel these based on certain heuristics like CPU/memory or time

**Comment by rmuir** [comment]
not going to support Thread.interrupt or any nonsense like that. you already have the exitable reader: use that

**Comment by rmuir** [comment]
And the reason i am short with you, again, is because you still implement a garbage security model (no authentication required by default).

Stop shipping insecure apps and you'll stop needing to worry about situations like this. I'm not going to workaround the insecurity of your application with a ton of complexity to lucene.

**Comment by Bukhtawar** [comment]
Maybe will discuss the security part separately, but agree, one idea is to detect such queries and prevent running these queries in the first place, in this case(not the original issue) it was a bad query from an authenticated user. 
Since this specific case and likes of these cannot be addressed by `ExitableDirectoryReaders` alone where looping over terms aren't involved, we need alternatives to cancel runaway queries if there are other requests which could exhibit the same behaviour

**Comment by msokolov** [comment]
Q: are you aware of https://github.com/apache/lucene/issues/11188? It's a fair question whether `ExitableDirectoryReader` is adequate for catching all runaway queries. There can be cases where there is some tight loop that never visits the index, so it slips through the net, like the regex one. With sledgehammers like `Thread.interrupt` off the table (it has always been questionable and is going away from JDK altogether soonish I think) we have to address these as they arise.

A useful contribution here would be some example queries that have unbounded runtimes and are not handled by the DirectoryReader approach. The example here has already been addressed, but do we have anything else? 

Note: one thing we have done is to use a custom Query whose Scorer checks for timeout. That way if we somehow do a lot of work that advances a docid iterator without reading from the index we can catch and throw an EarlyTerminationException. This isn't really going to be useful in most scenarios but I mention it in case you have some wonky Query execution that might benefit.

**Comment by rmuir** [comment]
> Maybe will discuss the security part separately, but agree, one idea is to detect such queries and prevent running these queries in the first place, in this case(not the original issue) it was a bad query from an authenticated user.
> Since this specific case and likes of these cannot be addressed by `ExitableDirectoryReaders` alone where looping over terms aren't involved, we need alternatives to cancel runaway queries if there are other requests which could exhibit a similar behaviour(tight loops consuming resources)

It isn't separate. Look at the actual regexes: these are not normal user queries, they are malicious, constructed purposefully to cause problems.

That's why the issue is improper security (e.g. authentication, audit logging etc). With these in place, if someone tries to run slow searches you will be able to attribute the malicious action to that human, hang, draw and quarter them, or whatever it is you want to do.

**Comment by Bukhtawar** [comment]
This specific case although the stack trace might appear the same wasn't a regex query but a wildcard and fuzzy query. I will share the redacted request

**Comment by rmuir** [comment]
It is the same bug, the bug is fixed. Don't read further into it.

If you are concerned about these things then don't enable such slow queries on your server! (wildcards, regexes, etc). These are not needed for any serious search application, they are toys.
