### ISSUE TITLE
Add newSetQuery for IntField, LongField, FloatField, DoubleField

### ISSUE THREAD

**Issue by gf2121** [apache/lucene#12028]
### Description

Today `TermInSetQuery` can be rewritten to disjunction BooleanQuery to lazily materialize query result if terms count < 16. This can significantly improve query performance in cases like `selective_clause AND low_cardinality_field in (xxx) `.

 Recently we added IntField, LongField, FloatField, DoubleField to index both with points and doc values (https://github.com/apache/lucene/issues/11199). `xxxField#newExactQuery` now can take advantage of `IndexOrDocValuesQuery` to match with DocValues when there is a selective conjunction clause. I wonder if we can have `xxxField#newSetQuery` that generates disjunction BooleanQuery when points count < 16 ? 
 
 For example:
 
 ```
public static Query newSetQuery(String field, long... values) {
  if (values.length < 16) {
    BooleanQuery.Builder builder = new BooleanQuery.Builder();
    for (long value: values) {
      builder.add(newExactQuery(field, value), Occur.FILTER);
    }
    return builder.build();
  }
  return LongPoint.newSetQuery(field, values);
}
 ```

**Comment by gf2121** [comment]
I benchmarked some queries like `_id = '1' AND cardinality_8_field in (1, 2, 3) ` on 1M docs, here is the result:
```
Benchmark                           Mode  Cnt   Score    Error   Units
fieldSetQuery  thrpt   10  48.025 ± 16.741  ops/ms
pointSetQuery  thrpt   10   5.514 ±  0.159  ops/ms
```
`fieldSetQuery` is using `LongField#newSetQuery` (see the example above) while `pointSetQuery` is using `LongPoint#newSetQuery`.

**Comment by rmuir** [comment]
I don't think it is good to degrade to `BooleanQuery` when using points or doc-values, it will only hurt performance.

Let's add `NumericDocValuesField.newSlowSetQuery()` and `SortedNumericDocValuesField.newSlowSetQuery()` to complement the doc-values based range queries?

Query in fact already exist, but needs to be cleaned up since they have been "hiding" in `lucene/sandbox`.  See PR.

**Comment by javanna** [comment]
Looks like this issue is addressed with the PR above? Can we close it or is there anything left to do that I am missing?

**Comment by gf2121** [comment]
Thanks Robert, nice approach!
