### ISSUE TITLE
ban finalizers in the build somehow (worst-case: use error-prone)

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#12057]
### Description

I was looking at new error-prone checks in #12056 and there's a new check to ban finalizers.

Because the method is in the built-in JDK deprecated list (e.g. https://github.com/policeman-tools/forbidden-apis/blob/main/src/main/resources/de/thetaphi/forbiddenapis/signatures/jdk-deprecated-11.txt#L195), I would expect the check to fail if i override finalize, but it doesn't because in most cases finalizer will not actually CALL object.finalize.

Let's ban finalizers completely, one way or another though, we don't want them to sneak in. We can always enable the error-prone check for it as one solution.

**Comment by rmuir** [comment]
Here's how to reproduce: apply this patch, then run `gradlew check -x test`. I would expect the build to fail, because we added a deprecated finalizer. Maybe forbidden doesn't fail because we don't actually call Object.finalize()? This method is a little special in that overriding it is enough to be bad. Maybe we should try to fix javac or ECJ to fail on deprecated usages instead?


```
diff --git a/lucene/core/src/test/org/apache/lucene/TestDemo.java b/lucene/core/src/test/org/apache/lucene/TestDemo.java
index 6c608e1d0b1..8bcbdc813ee 100644
--- a/lucene/core/src/test/org/apache/lucene/TestDemo.java
+++ b/lucene/core/src/test/org/apache/lucene/TestDemo.java
@@ -46,6 +46,11 @@ import org.apache.lucene.util.IOUtils;
  */
 public class TestDemo extends LuceneTestCase {

+  @Override
+  protected void finalize() {
+    System.out.println("YOLO");
+  }
+
   public void testDemo() throws IOException {
     String longTerm =
         "longtermlongtermlongtermlongtermlongtermlongtermlongtermlong"
```

**Comment by rmuir** [comment]
Confirmed that's the issue, if i add a `super.finalize()` call to my finalizer, then forbidden fails. I will edit the issue.

So we may need to use a different tool (javac, ecj) to ban finalizers. worst-case we just enable the error-prone check for them, but I try to avoid using error-prone if something simpler will do it.

**Comment by rmuir** [comment]
Currently there is no good way with ECJ/javac, unless we fail on all deprecations, which is very noisy at the moment. We can probably do it better with ECJ if we enable all their deprecation options, and clean up codebase (e.g. ensure tests calling deprecated stuff are also themselves deprecated)

* org.eclipse.jdt.core.compiler.problem.deprecation
* org.eclipse.jdt.core.compiler.problem.deprecationInDeprecatedCode
* org.eclipse.jdt.core.compiler.problem.deprecationWhenOverridingDeprecatedMethod

But looking at the code, that's gonna require quite a bit of work, I just wanted to make some progress here and prevent finalizers from slipping in.

Unfortunately the error-prone checker doesn't fail on this case either yet: https://github.com/google/error-prone/pull/3652

**Comment by dweiss** [comment]
Even a simplistic regexp/substring expression added to rat checks would work here, I think? this method is fairly uniquely-named. There are better alternatives but they will add overhead (parsing classes, etc).

**Comment by uschindler** [comment]
Yeah, similar like the LOG statement checks in Solr?

**Comment by rmuir** [comment]
that's true, it is another option. I am still investigating the ECJ one. 

It is a bit sad that we are so messy about deprecations and can't simply use the compiler's support. For example there are many deprecations in `main`, which makes no sense.

As an example, all the big-endian varhandles in `BitUtil` are deprecated, but they are in use across `main`, and from what I can tell, usage is only growing. That's because java uses it internally? So what is the point of the deprecation here? It is doing no good at all and just preventing us from using our compilers properly.
