### ISSUE TITLE
JVM crash - Problematic frame: # v  ~StubRoutines::jint_disjoint_arraycopy

### ISSUE THREAD

**Issue by rafaljelen** [apache/lucene#12061]
### Description

We faced JVM crashes in both our instances in 10 minutes difference. It's hard to determine any common circumstances. 

Signal code BUS_ADRERR was sent which means the memory address does not exist. This can happen on Linux when an mmap'ed file is truncated (e.g. a threading issue where 2 threads access a file at the same time).

Stack slot to memory mapping:
stack at sp + 0 slots: 3758369183 is a compressed pointer to object: java.lang.Class
{0x0000000700214cf8} - klass: 'java/lang/Class'
stack at sp + 1 slots: 0x00007fa8ec135819 is at entry_point+1049 in (nmethod*)0x00007fa8ec135210
stack at sp + 2 slots: 0x00000007abcf3808 is an oop: org.apache.lucene.store.BufferedChecksumIndexInput
{0x00000007abcf3808} - klass: 'org/apache/lucene/store/BufferedChecksumIndexInput'
stack at sp + 3 slots: 0x0 is NULL
stack at sp + 4 slots: 0x0 is NULL
stack at sp + 5 slots: 0x00000007abcf4020 is an oop: org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl
{0x00000007abcf4020} - klass: 'org/apache/lucene/store/ByteBufferIndexInput$SingleBufferImpl'
stack at sp + 6 slots: 0x00007fa89c02b000 is a thread
stack at sp + 7 slots: 0x0 is NULL

StubRoutines::jint_disjoint_arraycopy [0x00007fa8e1f895a0, 0x00007fa8e1f89664[ (196 bytes)

Possibly a thread is trying to access one of these deleted mmapped resources:

7fa8522b4000-7fa8524d5000 r-xp 00000000 103:03 4250214                   /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8524d5000-7fa8526d5000 ---p 00221000 103:03 4250214                   /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8526d5000-7fa8526e9000 rw-p 00221000 103:03 4250214                   /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8526e9000-7fa8526eb000 rw-p 00000000 00:00 0
7fa8526eb000-7fa8526fa000 r-xp 00000000 103:03 4250213                   /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)
7fa85

26fa000-7fa8528f9000 ---p 0000f000 103:03 4250213                   /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)
7fa8528f9000-7fa8528fb000 rw-p 0000e000 103:03 4250213                   /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)

[attached crash log](https://github.com/apache/lucene/files/10336310/node1_hs_err_pid47482.log)

### Version and environment details

apache lucene version: 8.11.1
JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.9.1+1) (build 11.0.9.1+1)

**Comment by rmuir** [comment]
> Possibly a thread is trying to access one of these deleted mmapped resources:

7fa8522b4000-7fa8524d5000 r-xp 00000000 103:03 4250214 /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8524d5000-7fa8526d5000 ---p 00221000 103:03 4250214 /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8526d5000-7fa8526e9000 rw-p 00221000 103:03 4250214 /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64799445249890210256.so (deleted)
7fa8526e9000-7fa8526eb000 rw-p 00000000 00:00 0
7fa8526eb000-7fa8526fa000 r-xp 00000000 103:03 4250213 /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)
7fa85

26fa000-7fa8528f9000 ---p 0000f000 103:03 4250213 /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)
7fa8528f9000-7fa8528fb000 rw-p 0000e000 103:03 4250213 /tmp/libio_grpc_netty_shaded_netty_transport_native_epoll_x86_6417502967125676705981.so (deleted)

DUDE, that is your app, nothing to do with lucene. stop using shaded netty native shit if you dont want that.

**Comment by uschindler** [comment]
Hi,
this is not a bug in Lucene, it can be two possible problems:
- You are closing IndexReaders while queries are still running. Due to limitations of unmapping memory mapped files in Java 11 (no thread safe unmapping), this may cause SIGSEGV or SIGBUS. This is well known. To prevent this consider upgrading to Lucene 9.4 and Java 19 with preview options enabled.
- The code looks like it tries to access Netty files, so it looks like not related to Lucene.

To me this looks like a mixture of using netty and possibly also closing index files while there's still access from other threads.
