### ISSUE TITLE
Enhance XXXField#newRangeQuery

### ISSUE THREAD

**Issue by LuXugang** [apache/lucene#12074]
### Description

Since dim of XXXField's point value is always `1`, should we introduce `IndexSortSortedNumericDocValuesRangeQuery` to `IntFiled#newRangeQuery` and `LongField#newRangeQuery` ? This idea is also mentioned by @jpountz in [LUCENE-10446](https://issues.apache.org/jira/browse/LUCENE-10446).

like :

```java
public static Query newRangeQuery(String field, int lowerValue, int upperValue) {
    PointRangeQuery.checkArgs(field, lowerValue, upperValue);
    Query fallbackQuery = IntPoint.newRangeQuery(field, lowerValue, upperValue);
    return new IndexOrDocValuesQuery(
        new IndexSortSortedNumericDocValuesRangeQuery(field, lowerValue, upperValue, fallbackQuery),
        SortedNumericDocValuesField.newSlowRangeQuery(field, lowerValue, upperValue));
  }
```

If above is possible, we should also need to move `IndexSortSortedNumericDocValuesRangeQuery` from sandbox to core module?

**Comment by jpountz** [comment]
+1
