### ISSUE TITLE
org.apache.lucene.search.uhighlight.TestUnifiedHighlighterTermVec.testFetchTermVecsOncePerDoc fails reproducibly

### ISSUE THREAD

**Issue by cpoerschke** [apache/lucene#12115]
### Description

currently 5 matches in the last few weeks: https://lists.apache.org/list?builds@lucene.apache.org:dfr=2022-1-1|dto=2024-1-1:org.apache.lucene.search.uhighlight.TestUnifiedHighlighterTermVec.testFetchTermVecsOncePerDoc

```
...
Error Message:
java.lang.AssertionError: Should not request TVs for doc more than once.

Stack Trace:
java.lang.AssertionError: Should not request TVs for doc more than once.
	at junit@4.13.1/org.junit.Assert.fail(Assert.java:89)
	at junit@4.13.1/org.junit.Assert.assertTrue(Assert.java:42)
	at junit@4.13.1/org.junit.Assert.assertFalse(Assert.java:65)
...
```

### Gradle command to reproduce

from https://jenkins.thetaphi.de/job/Lucene-main-MacOSX/9238/testReport/junit/org.apache.lucene.search.uhighlight/TestUnifiedHighlighterTermVec/testFetchTermVecsOncePerDoc/

> ./gradlew test --tests TestUnifiedHighlighterTermVec.testFetchTermVecsOncePerDoc -Dtests.seed=B40B463B9510DF27 -Dtests.locale=ff-Latn-SL -Dtests.timezone=Asia/Ulaanbaatar -Dtests.asserts=true -Dtests.file.encoding=UTF-8

from https://lists.apache.org/thread/np5w9kzklskjxflxmthc8r7y59x5934m

> ./gradlew :lucene:highlighter:test --tests "org.apache.lucene.search.uhighlight.TestUnifiedHighlighterTermVec.testFetchTermVecsOncePerDoc" -Ptests.jvms=4 -Ptests.haltonfailure=false "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1" -Ptests.seed=29E42D85ACE838EF -Ptests.multiplier=2 -Ptests.nightly=true -Ptests.badapples=false -Ptests.gui=true -Ptests.file.encoding=US-ASCII # -Ptests.linedocsfile=/home/jenkins/jenkins-slave/workspace/Lucene/Lucene-NightlyTests-9.x/test-data/enwiki.random.lines.txt

**Comment by romseygeek** [comment]
It's a test bug, where we check for the presence of ParallelLeafReader in the stack and skip if it's there.  Recent changes to TermVectors mean we now have an anonymous subclass of Fields in the stack rather than ParallelLeafReader itself so we don't skip.

**Comment by rmuir** [comment]
I think @romseygeek explanation makes sense. Wrapping the reader is not helpful to testing that the highlighter uses it correctly, it just causes complexity?

To me the easiest fix would be to remove the `callStackContains(ParallelLeafReader) stuff from the `AssertOnceTermVecDirectoryReader`, and to replace `newSearcher(ir);` with `newSearcher(ir, false); // don't wrap the reader with Parallel or other wrappers in this test`.
