### ISSUE TITLE
port gradle improvements to Lucene

### ISSUE THREAD

**Issue by risdenk** [apache/lucene#12145]
### Description

Port https://github.com/apache/solr/commit/7a9ce356bc7c90c8237437b1e16ed030e4d67900 and https://github.com/apache/solr/commit/bde8c14bddecc2a417d2fd36abe965675e8e670e to Lucene

**Comment by uschindler** [comment]
Actually the basic changes can simply be cherry-picked cross-repository, so maybe its easy. I can also have a look.

**Comment by tylerbertrand** [comment]
Yeah I tried cherry picking the changes from solr but it looked like there were some small differences between them that required a few changes.

**Comment by uschindler** [comment]
The problem is often that some changes in Lucene were not ported to Solr. It is often advisable to start in Lucene as it often is more modern. I know the problem. It still often works very easy.

**Comment by tylerbertrand** [comment]
Submitted [Gradle Optimizations PR](https://github.com/apache/lucene/pull/12150)

**Comment by risdenk** [comment]
Handled by https://github.com/apache/lucene/pull/12150
