### ISSUE TITLE
*not an issue* Need help/ How to use Hunspell Spell-checker

### ISSUE THREAD

**Issue by aggelako** [apache/lucene#12143]
Hello, 

as mentioned this may not fit here, but thought to give it a try.
I'm trying to create a java-wrapper library to lang-detect and then spell check for the detected languages. I'm currently using Apache Tika as a lang detector and i'm trying to use lucene.analysis.hunspell package for spell-checking, as i've i seen it supports many languages.
My issue is, i cant get good accuracy for some languages that have "special" characters.
e.g in sweedish im checking the word bästa, which is classified as misspelled and the word basta is suggested instead. 
bästa exists in the dictionary, so i think this is some encoding issue.

Any guidance on where i should look, or how i should implement to perform spellchecks would be welcome, as i've hardly found anything :)

**Comment by romseygeek** [comment]
Hi @aggelako, we use this repository for tracking bugs and new functionality for lucene.  For usage questions, please send messages to the `dev@lucene.apache.org` mailing list.
