### ISSUE TITLE
TermAutomatonQuery explain() should return relevant explain output instead of null

### ISSUE THREAD

**Issue by kashkambath** [apache/lucene#12178]
### Description

Hi! This is my first time posting a GitHub issue for Apache Lucene. Please let me know if you need anything further.

https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/TermAutomatonQuery.java#L443-L447

We should return relevant explain output here instead of returning `null` for `TermAutomatonQuery`. This would be helpful for users running document explain on synonym queries leveraging `TermAutomatonQuery`. Otherwise, certain queries that can nest other queries could throw a `NullPointerException` if their weight's `explain()` calls `TermAutomatonQuery#explain()`. 

For example, if a `BooleanQuery` nests a `TermAutomatonQuery`, then `BooleanWeight` throws an NPE here when running `explain()`:

https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/core/src/java/org/apache/lucene/search/BooleanWeight.java#L75

**Comment by MarcusSorealheis** [comment]
Akaash, this looks good. Thanks for opening the issue. Do you feel like #12208 addresses your concerns? It will surely be reviewed soon. There's obviously more we can do, but the first step is to get the functionality there, and then we can build improvements upon it. There's a lot to do in many areas in perpituity.

**Comment by kashkambath** [comment]
@MarcusSorealheis looks reasonable to me, thanks for taking it on!

**Comment by MarcusSorealheis** [comment]
> @MarcusSorealheis looks reasonable to me, thanks for taking it on!

Anytime! Happy to help and more to come. 😁
