### ISSUE TITLE
Add Facets#getSpecificValues (bulk) and bulk path -> ordinal lookup for taxonomy faceting

### ISSUE THREAD

**Issue by gsmiller** [apache/lucene#12180]
### Description

[LUCENE-9476](https://issues.apache.org/jira/browse/LUCENE-9476) added the ability to do bulk ordinal -> path lookups, but we have no bulk lookup in the other direction. I think we can find some efficiency gains if we add bulk lookup for paths, which we could then put behind a `Facets#getSpecificValues` API for retrieving facet values for multiple paths in bulk. There's some nuance down in the depths of MultiTerms, so maybe there's nothing to be gained here, but I think there ought to be (I'll try to look in more detail later, but wanted to open an issue to track the idea in case I forget). A few thoughts:
1. We can seek the terms dictionaries in a single direction if we sort the paths before looking them up.
2. We should be able to reuse postings.

**Comment by uschindler** [comment]
Hi, the commit causes test failures like this from time to time:
```
org.apache.lucene.facet.taxonomy.directory.TestDirectoryTaxonomyReader > testGetPathAndOrdinalsRandomMultithreading FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=276, name=Thread-152, state=RUNNABLE, group=TGRP-TestDirectoryTaxonomyReader]

        Caused by:
        java.lang.IllegalArgumentException: bound must be positive
            at __randomizedtesting.SeedInfo.seed([EB36AAC7E6947189]:0)
            at java.base/java.util.Random.nextInt(Random.java:322)
            at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.Xoroshiro128PlusRandom.nextInt(Xoroshiro128PlusRandom.java:73)
            at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.AssertingRandom.nextInt(AssertingRandom.java:87)
            at org.apache.lucene.facet.taxonomy.directory.TestDirectoryTaxonomyReader.assertGettingPaths(TestDirectoryTaxonomyReader.java:519)
            at org.apache.lucene.facet.taxonomy.directory.TestDirectoryTaxonomyReader$4.run(TestDirectoryTaxonomyReader.java:721)
```

And hundreds of more threads following. Looks like sometimes the ordinals array is initialized by zero length. The followup random then fail because the upper bound passed to `random#nextInt(limit)` must be `limit>=1`.

**Comment by mikemccand** [comment]
OK fixed @uschindler -- sorry!

**Comment by mikemccand** [comment]
And thanks @epotyom!

**Comment by gsmiller** [comment]
Thanks @epotyom! Should we consider a follow up PR that leverages this new bulk lookup by adding something like `Facets#getSpecificValues` that gets facet values for multiple paths at once? What do you think?

**Comment by epotyom** [comment]
@gsmiller yes, I'll be working on that now as well as adding benchmark task for getSpecificValues, as was discussed with Mike in https://github.com/apache/lucene/pull/12769#pullrequestreview-1715024239 .

**Comment by gsmiller** [comment]
@epotyom got it, thanks! Didn't see that earlier conversation.

**Comment by ChrisHegarty** [comment]
Hi,  

I'd like to ask a clarifying question as part of the _9.9.0_ release manager duties, since this currently-unresolved issue is associated with _Milestone 9.9.0_.

It's clear that progress has been made on this issue, with the addition of the new `TaxonomyReader::getBulkOrdinals` method. Is more work planned, or should this issue be closed?  It's fine either way, I just want to ensure that we are clear about the targeted release, if any.

**Comment by mikemccand** [comment]
Thanks @ChrisHegarty -- this one is done.

**Comment by epotyom** [comment]
@mikemccand , @ChrisHegarty ,

Sorry for confusion, but this issue is not fully done yet. This issue includes:
1. [done] Add `TaxonomyReader#getBulkOrdinals` method (#12769)
2. [in review now] Add `Facets#getBulkSpecificValues` method which uses `getBulkOrdinals` to get multiple specific values at once. (#12862)
3. [not started yet] Adding performance test task for the new APIs

**Comment by epotyom** [comment]
@mikemccand ,

> can you open a new issue for the followon tasks?
