### ISSUE TITLE
FieldInfo#attributes should be exposed as variables instead of map

### ISSUE THREAD

**Issue by jeffgan96** [apache/lucene#12193]
### Description

Currently, FieldInfo attributes map only stores PerFieldDocValuesFormat and PerFieldPostingsFormat. It is much costlier to read/write from this map multiple times as compared to if we simply extract them out as variables in the class instead.

Context: We have a use case where there are frequent refreshes and merges and we have seen many times in hot-threads read/write to FieldInfo#attributes. Since there are no other additions to this map apart from these 2, it would be better to just store them individually instead of using a map.

**Comment by jpountz** [comment]
I have never seen a profile where this showed up. Can you tell a bit more about whether there are interesting things you are doing like flushing on every document or every couple ms?

**Comment by jeffgan96** [comment]
not exactly. we have refresh interval set to 1 and high number of updates and indexing . index has >20000 fields

**Comment by rmuir** [comment]
20,000 fields is the problem, not FieldInfo's attributes map.
