### ISSUE TITLE
Add a new static method for KeywordField#newSetQuery to support collections parameter

### ISSUE THREAD

**Issue by slow-J** [apache/lucene#12243]
### Description

Currently, the [KeywordField](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/document/KeywordField.java) class provides a public static method `newSetQuery(String field, BytesRef... values)`. However, this method only supports varargs parameter for values. I would like to propose adding a new static method that allows for a collections parameter for values, as this would provide greater flexibility.

Proposed method signature:
`public static Query newSetQuery(String field, Collection<BytesRef> values)`

I am willing to make the changes and submit a pull request.
Please let me know if there are any concerns or feedback. Thank you!

**Comment by rmuir** [comment]
"flexibility" is usually a dirty word when it comes to apis, is there a better explanation of the use-case?

Especially given that Collection has .toArray already, it seems really easy for the user to use as-is?

**Comment by rmuir** [comment]
and frankly, i have big concerns that this method will somehow warp into something other than calling .toArray to help the user.

database users be database users and this kind of complexity has crept in here before. 

Let's keep it simple with basic arrays.

**Comment by slow-J** [comment]
Thanks for the quick reply @rmuir , I'll try explain the use case better.

Calling the existing [`newSetQuery`](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/document/KeywordField.java#L174-L180) takes the array and constructs: [1](https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java#L89),[2](https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java#L102) TermInSetQueries which both then wrap the array with a list `Arrays.asList(terms)`.

So in the case of having a List of BytesRef, we would first call `.toArray`, and then `TermInSetQuery` immediately calls `Arrays.asList`.
This seems a bit redundant to me, since there are existing `TermInSetQuery` constructors that take the collection parameters [1](https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java#L84), [2](https://github.com/apache/lucene/blob/569533bd76a115e239d8c621d2540462bc12d891/lucene/core/src/java/org/apache/lucene/search/TermInSetQuery.java#L93).

The new `newSetQuery(String field, Collection<BytesRef> values)` method would simply call the `TermInSetQuery` constructors with the collections parameter.

**Comment by mikemccand** [comment]
It is sort of odd to take an ordered collection (`BytesRef[]` currently), since the order of the incoming terms has no meaning/requirement?

Or does `KeywordField` require that the user pre-sort the incoming `BytesRef`s to `newSetQuery`?

**Comment by rmuir** [comment]
I don't think the fact that TermInSetQuery has a Collection ctor should impact this at all. Maybe that should be removed?

**Comment by mikemccand** [comment]
> I don't think the fact that TermInSetQuery has a Collection ctor should impact this at all. Maybe that should be removed?

+1

It's weird to take both array and Collection when the API is just going to do the obvious conversion that a caller would do?  We should somehow be consistent here about such "sugar" APIs.

But if we are going to pick one, shouldn't it be `Collection` for these two cases, since order does not matter?  Taking an array implies that order might be significant, but (I think?) order does not matter for `KeywordField.newSetQuery` nor for `TermInSetQuery` ctor?

I don't feel strongly though (Collection vs array) ... but I do agree we should be consistent.

**Comment by slow-J** [comment]
> > I don't think the fact that TermInSetQuery has a Collection ctor should impact this at all. Maybe that should be removed?
> 
> +1
> 
> It's weird to take both array and Collection when the API is just going to do the obvious conversion that a caller would do? We should somehow be consistent here about such "sugar" APIs.
> 
> But if we are going to pick one, shouldn't it be `Collection` for these two cases, since order does not matter? Taking an array implies that order might be significant, but (I think?) order does not matter for `KeywordField.newSetQuery` nor for `TermInSetQuery` ctor?
> 
> I don't feel strongly though (Collection vs array) ... but I do agree we should be consistent.

Thanks Mike, to progress the discussion I opened a PR to remove the `TermInSetQuery` array ctor and change the `KeywordField.newSetQuery` values param to `Collections`

**Comment by gsmiller** [comment]
+1 to shrinking the API surface of the `TermInSetQuery` ctors and getting rid of the varargs flavors since they're pure syntactic sugar. Looks like #12837 is the related PR, so left a small comment over there. Thanks @slow-J !
