### ISSUE TITLE
In VectorUtil.dotProductScore , the denom should not multiply the array length

### ISSUE THREAD

**Issue by wangyanbn** [apache/lucene#12256]
### Description

in [VectorUtil.dotProductScore](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/util/VectorUtil.java#L268), the `denom` should not multiply the array length:
` float denom = (float) (a.length * (1 << 15));`
` return 0.5f + dotProduct(a, b) / denom;`

When we use float vector with the dot product similarity, we will normalize it to unit length 1, the float dot product score formula is: 
`0.5 + dotProduct(a_float_vec, b_float_vec) / 2`, it is not related to the array length.

When we use byte, we just multiply every item in float vector by 128, and the byte dot product value will be multified by 128*128: 
`dotProduct(a_byte_vec, b_byte_vec)  = dotProduct(128*a_float_vec, 128*b_float_vec)  = 128*128*dotProduct(a_float_vec, b_float_vec)`,  
which is not related to array length. 

To get the same score as float vector, the byte score should be:
 `0.5 + dotProduct(a_byte_vec, b_byte_vec) /(128*128* 2)`, 
which is same as :
`0.5 + dotProduct(a_byte_vec, b_byte_vec) /(float)(1 << 15)`.

So the right `denom` should be: `float denom = (float) (1 << 15)`

I am testing with ElasticSearch 8.7, which uses Lucene 9.5 . My vector length is 256, when use type byte , the scores are all near the value of 0.5 (because 256 is not a small num, the `denom` value will be very big), which are very different from the float type scores. 
If `denom` doesn't multiply the array length, the byte and float scores are similar.

### Version and environment details

Lucene 9.5
JVM:19.0.2

**Comment by msokolov** [comment]
There's no requirement that these scores have any particular values; the only requirement is that they sort the same as the dot-product score. There is no reason to expect that floating point dot product scores would equal dot product scores for bytes.

The reason the scaling is the way it is is to avoid clipping the max values. if both vectors a, b are all -128 (say), then a*b = 128^2 * dim = 2^14 * dim. We want [min, max] score to scale to [-0.5, 0.5] which is why this is the way it is. It also says this is in the comments. Maybe you could suggest better wording to make that clearer?

**Comment by msokolov** [comment]
sorry didn't mean to close in case there's some further discussion, but I don't think it's a bug, anyway.

**Comment by wangyanbn** [comment]
Thanks for your prompt response! 

> There is no reason to expect that floating point dot product scores would equal dot product scores for bytes.

When we choose the byte instead of float value, we only wish to use less memory space, and we do expect the bytes scores are same as float scores. I think this is the common use case for byte vector.

**Comment by wangyanbn** [comment]
> don't think it's a bug, anyway

I didn't find how to change the lable of an issue. 
This may be an **Enhancement Request/Suggestion**.

**Comment by wangyanbn** [comment]
I add a new suggestion:  [Suggestion for VectorUtil.dotProductScore, to make the byte and float vector dotProductScore same](https://github.com/apache/lucene/issues/12263)
This is not a bug. It will be closed. Thanks! @msokolov
