### ISSUE TITLE
MappedByteBufferIndexInputProvider can better throw UndeclaredThrowableException

### ISSUE THREAD

**Issue by drzhonghao** [apache/lucene#12250]
### Description

MappedByteBufferIndexInputProvider has the following code:

 private static BufferCleaner newBufferCleaner(final MethodHandle unmapper) {

...

try {
        unmapper.invokeExact(buffer);
      } catch (Throwable t) {
        throw new IOException("Unable to unmap the mapped buffer: " + resourceDescription, t);
      }

 }
This method rethrow IOException, when calling invokeExact fails. However, other methods throw UndeclaredThrowableException for the same errors. For example, SnowballProgram.find_among is as follows:

protected int find_among(Among v[]) {

 ..,
 
try {
          res = (boolean) w.method.invokeExact(this);
        } catch (Error | RuntimeException e) {
          throw e;
        } catch (Throwable e) {
          throw new UndeclaredThrowableException(e);
        }
}
Another example is AttributeFactory.createInstance

:

 
 protected A createInstance() {
        try {
          // be explicit with casting, so javac compiles correct call to polymorphic signature:
          final AttributeImpl impl = (AttributeImpl) constr.invokeExact();
          // now cast to generic type:
          return (A) impl;
        } catch (Error | RuntimeException e) {
          throw e;
        } catch (Throwable e) {
          throw new UndeclaredThrowableException(e);
        }
      }

   
UndeclaredThrowableException looks more reasonable.  Can this be fixed?

**Comment by uschindler** [comment]
This is not a bug. In reality the throwable is never thrown here because the called method never throws any exception. The catch block is only a safety guard around the stupid MethodHandle.

The same applies to the other two examples.

**Comment by uschindler** [comment]
For mmapdirectory any error in the BufferClean must be treated as IOException, so the code is correct.
