### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by SrikanthMedisetti** [apache/lucene#12259]
### Description

Hello Team,
I have the following use case.
Store/Index data without tokenize (use StringField) and maintain the same string while storing (maintain case sensitivity while storing data). The problem I face is during search. If I store field called name as 'Lucene' and if I try to search with 'lucene', I'm not able to get the store data with 'Lucene'.

I'm trying to use Lucene 9.5.0 

`public class LuceneExample {
    public static void main(String[] args) throws IOException, ParseException {
        // Create index
        KeywordAnalyzer analyzer = new KeywordAnalyzer();
        String indexDirectoryPath = new StringBuilder("/temp/").append("test").toString();
        // create the directory to store the index
        Directory directory = FSDirectory.open(Paths.get(indexDirectoryPath));
        IndexWriterConfig config = new IndexWriterConfig(analyzer);
        IndexWriter writer = new IndexWriter(directory, config);

        Document doc = new Document();
        doc.add(new StringField("name", "John Smith", Field.Store.YES));
        writer.addDocument(doc);
        writer.close();

        // Search index

        // create a reader to read the index
        IndexReader reader = DirectoryReader.open(directory);
        IndexSearcher searcher = new IndexSearcher(reader);
        QueryParser parser = new QueryParser("name", analyzer);
        Query query = parser.parse("john smith");
        TopDocs results = searcher.search(query, 10);
        for (int i = 0; i < results.scoreDocs.length; i++) {
            Document hitDoc = searcher.doc(results.scoreDocs[i].doc);
            System.out.println(hitDoc.get("name"));
        }
    }
}`

Am I missing something here? Could you please help me out.

Thanks in advance!

**Comment by MarcusSorealheis** [comment]
You are. The prescribe method for dealing with this sort of pre-processing is through using the analysis chain.

If you add this line (and associated imports) to the top of this snippet you should be good to go:

`StandardAnalyzer analyzer = new StandardAnalyzer();`

Keep in mind that the standard analyzer does not process things like stop words, so the text should be largely unaffected. If you only want to affect case strictness, you can look into the [LowerCaseFilter](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/analysis/LowerCaseFilter.java) applied at the character level. Be sure to apply at index- and query-time.

**Comment by mkhludnev** [comment]
[SrikanthMedisetti] please use TextField instead. Not an issue.
