### ISSUE TITLE
Maybe rename `DaciukMihovAutomatonBuilder`?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12276]
### Description

Spinoff from [this dev list thread](https://markmail.org/thread/2hf6zgqoxfffmeqe).

This delightful class very efficiently takes a set of terms and produces the already determinized and minimized Automaton matching exactly those terms.

I appreciate that the name comes from the authors of the paper that explained this algorithm (thank you!!), but I would like to name it something more approachable to new users so they get a hint about what this powerful class actually does.

Any suggestions?

**Comment by dweiss** [comment]
StringSetAutomatonBuilder?

**Comment by uschindler** [comment]
I thought this class was already renamed to `MinimizeSchindlerDeterminizer`? 😂

**Comment by mikemccand** [comment]
> StringSetAutomatonBuilder?

Hmm can we remove `Set`?  (It could be a list or array of String too).  Maybe `StringsToAutomaton`?

**Comment by dweiss** [comment]
A list or an array - doesn't matter, conceptually it's a set in the end (in the automaton). But I don't mind any version.

**Comment by gsmiller** [comment]
+1 to `StringsToAutomaton` language. I'd suggest keeping "Builder" in the name.

In general, also +1 to renaming. The algorithm doesn't have to only be applied to strings (e.g., it could directly be applied to binary data, as long as it's sorted). So having something that references "string" in the name feels right to me.
