### ISSUE TITLE
Unnecessary blank lines found in stopwords.txt of SmartChineseAnalyzer

### ISSUE THREAD

**Issue by JerryChin** [apache/lucene#12291]
### Description

Hi team,

This issue is a spin-off from the [java-user list thread](https://markmail.org/thread/jzujraq5jcrodb2b).

The [stopwords.txt](https://github.com/apache/lucene/blob/main/lucene/analysis/smartcn/src/resources/org/apache/lucene/analysis/cn/smart/stopwords.txt) of SmartChineseAnalyzer contains two blank lines at [L56](https://github.com/apache/lucene/blob/223e28ef16acb35cb43c89493855366d171de4f9/lucene/analysis/smartcn/src/resources/org/apache/lucene/analysis/cn/smart/stopwords.txt#L56) & [L58](https://github.com/apache/lucene/blob/223e28ef16acb35cb43c89493855366d171de4f9/lucene/analysis/smartcn/src/resources/org/apache/lucene/analysis/cn/smart/stopwords.txt#L58). As a result, `SmartChineseAnalyzer.getDefaultStopSet()` will produce an empty string stop word, but it makes no sense to have empty string as a stop word.

Maybe we can improve it?

**Comment by tang-hi** [comment]
Good Catch! Could you submit a PR to fix that?

**Comment by mikemccand** [comment]
I think the stoplist loader already ignores comment lines, but, does not ignore empty lines!  Darned empty string rears its head at us again...

**Comment by uschindler** [comment]
Also here: https://github.com/apache/lucene/blob/5d203f8337cb6a2350c1abe5d83e3e103d060645/lucene/core/src/java/org/apache/lucene/analysis/WordlistLoader.java#L119
