### ISSUE TITLE
Async Usage of Lucene Monitor through a Reactive Programming based application

### ISSUE THREAD

**Issue by almogtavor** [apache/lucene#12318]
### Description

I'd like to use Lucene Monitor in a non-blocking IO application, and I'd like to know what is the recommended way of doing that. Currently, I match queries with the `ParallelMatcher` class, but since I'd like to migrate my application to work with Project Reactor, I'm worried about the usage of `BlockingQueue` inside `ParallelMatcher`.

When using the Java `BlockingQueue` implementation, the `put()` method will block if the queue is full, and the `take()` method will block if the queue is currently empty. This can be an effective way to handle cases where producers might produce data faster than consumers can handle it or vice versa. However, when using reactive programming paradigms (such as in Project Reactor), blocking should be avoided as much as possible because it goes against the non-blocking nature of reactive systems. Blocking can lead to thread starvation and ultimately affect the performance and scalability of the application.

I'd like to get some help with understanding if there's another `Matcher` that will fit my async needs, or shall I create one of my own for this? From what I've seen, the `PartitionMatcher` doesn't use `BlockingQueue` but still uses `future.get()`. I'd like to know the following:

1) Is there any `Matcher` that would work well inside a non-blocking IO application? If not, shall we create one?
2) Assuming there is a non-blocking IO `Matcher`, is there any other area where I need to be worried about my usage of Lucene Monitor blocking ( This includes any IO operations, synchronization points, or data structures that can block)?

**Comment by almogtavor** [comment]
@romseygeek I'd really appreciate your response here

**Comment by romseygeek** [comment]
Hi @almogtavor!  I think you're probably best off writing your own Matcher implementation here, and possibly extending Monitor as well, given that `match` is an inherently synchronous method.  The only IO operations happening here are in the internal searches, and the default implementation uses a ByteByfferDirectory in any case.  There are some synchronization points in the QueryIndex for when new queries are registered with the Monitor.

**Comment by almogtavor** [comment]
@romseygeek I see. In general would you say the `match` method is an inherently synchronous method due to Lucene Monitor being a CPU heavy application? e.g. would you say that there's not really a need for making this application part synchronous? In Reactor there's an abillity of executing specific synchronous tasks within another thread pool. Would you say it is preferable to this situation?

**Comment by romseygeek** [comment]
Yes, I'd say `match` is unlikely to do any actual IO unless you're explicitly using an on-disk directory (ie not MMapDirectory or ByteBuffersDirectory) for the query index.  So it will all be CPU-bound and there won't really be any opportunities to hand off to another thread while waiting for disk.

**Comment by almogtavor** [comment]
@romseygeek Oh so that sounds even better than what I thought. In this case, I can treat the `match` operation like a total sync operation and use it in Reactor without bounding the `match` operation to its own thread pool. Similar to the way I treat Jackson's ObjectMapper's string-object operations for example.

**Comment by almogtavor** [comment]
@romseygeek Oh so that sounds even better than what I thought. In the case of `ByteBuffersDirectory` & MMap, I can treat the `match` operation like a total sync operation and use it in Reactor without bounding the `match` operation to its own thread pool. Similar to the way I treat Jackson's ObjectMapper's string-object operations for example. Sounds correct?

And if I'd like to tread the `match` as a low IO operation - would you say it is preferable for me to use  `ParallelMatcher`, or `PartitionMatcher`? In Reactor it is possible to execute the `match` operation on a "parallel scheduler", and therefore to let Reactor parallelize the operation. WDYT?

**Comment by almogtavor** [comment]
@romseygeek Oh so that sounds even better than what I thought. In the case of `ByteBuffersDirectory` & MMap, I can treat the match operation like a total sync operation and use it in Reactor without bounding the match operation to its own thread pool. Similar to the way I treat Jackson's `ObjectMapper`'s string-object operations for example. Sounds correct?

And if I'd like to tread the match as a low IO operation - would you say it is preferable for me to use `ParallelMatcher`, or `PartitionMatcher`? In Reactor it is possible to execute the match operation on a "parallel scheduler", and therefore to let Reactor parallelize the operation. WDYT?

**Comment by almogtavor** [comment]
@romseygeek Oh so that sounds even better than what I thought. In the case of `ByteBuffersDirectory` & MMap, I can treat the match operation like a total sync operation and use it in Reactor without bounding the match operation to its own thread pool. Similar to the way I treat Jackson's `ObjectMapper`'s string-object operations for example. Sounds correct?

And if I'd like to tread the match as a low IO operation - would you say it is preferable for me to use `ParallelMatcher`, or `PartitionMatcher`? In Reactor it is possible to execute the match operation on a "parallel scheduler", and therefore to let Reactor parallelize the operation. WDYT?

**Comment by romseygeek** [comment]
`Parallel` vs `Partition` depends on the types of queries that you're matching against.  `Parallel` hands all candidates to a blocking queue, so the synchronization overhead is per-query - efficient if the queries are heavy, but can be expensive if everything is just a term query and takes very little time to check.  `Partition` collects all candidate queries, then divides them up into blocks and passes each block to a separate thread for checking.  This will work better if all your queries are of a similar weight, but means that if a few heavy queries get pushed into a single partition then you can end up with longer latency.

**Comment by almogtavor** [comment]
I see. Thanks alot for the help
