### ISSUE TITLE
PagingFieldCollector is not able to skip documents for searchAfter value for which no competitive hits are present.

### ISSUE THREAD

**Issue by gashutos** [apache/lucene#12333]
### Description

If we specify ```after``` value for ```PagingFieldCollector``` which is out of min/max values for that field in that segment, ```PagingFieldCollector``` is not able to update its competitiveIterator because ```queueFull``` is never able to set to true.
Code ref - [NumericComparator.java$194](https://github.com/apache/lucene/blob/c188d47a8b3b58748ec88335287da86582290c73/lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java#LL194C1-L194C7)

Due to this, it will spend lot of time comparing large number of hits here [TopFieldCollector.java#264](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/TopFieldCollector.java#LL264C22-L264C22).
Instead it is supposed to short cut right away.

**Comment by gsmiller** [comment]
Thanks for the PR @gashutos! Merged and back-ported under 9.7.
