### ISSUE TITLE
repo.maven.apache.org no has lucene-analyzers-common 9.7.0 version

### ISSUE THREAD

**Issue by startjava** [apache/lucene#12432]
https://repo.maven.apache.org/maven2/org/apache/lucene/lucene-analyzers-common/

**Comment by mkhludnev** [comment]
Here we go https://repo.maven.apache.org/maven2/org/apache/lucene/lucene-analysis-common/9.7.0/
dunno why, really.

**Comment by dweiss** [comment]
The artifact was renamed for 9.x to reflect the directory structure in the repository.

**Comment by startjava** [comment]
how find 9.7.0 version lucene-analyzers-common jar??&nbsp; url ?? thank you !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/lucene"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/lucene] repo.maven.apache.org no has lucene-analyzers-common 9.7.0 version (Issue #12432)





 
The artifact was renamed for 9.x to reflect the directory structure in the repository.

**Comment by dweiss** [comment]
There is no lucene-analyzers-common, it's been renamed to lucene-analysis-common, the JAR is here:
https://repo.maven.apache.org/maven2/org/apache/lucene/lucene-analysis-common/9.7.0/lucene-analysis-common-9.7.0.jar
