### ISSUE TITLE
Switch from MAXSCORE to BS1 with high numbers of clauses

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12439]
### Description

With Elasticsearch, we have been observing that queries with many SHOULD clauses can get multiple times faster with our brute-force BS1 scorer compared to our scorers that support dynamic pruning and get used by default.

I don't think we can reliably predict when BS1 would perform better, but we could run luceneutil with increasing numbers of clauses (2, 4, 8, 16, 32) of various term frequencies and see when BS1 performs better. This would give us a threshold that would likely be imperfect but would also be better than nothing?

**Comment by msokolov** [comment]
I wonder if docfreq of the terms should also be considered? EG perhaps only low-frequency terms should be used for pruning. Just thinking out loud, I have no idea how we'd do that. But are you able to look at statistics of avg/max docfreq across the terms in each query?

**Comment by jpountz** [comment]
Document frequencies have an impact indeed, but the logic would become quite complicated wouldn't it?

Separately, by discussing about this with @jimczi, I realized that we may now be able to bring the BS1 optimization into our `MaxScoreBulkScorer`. I will give it a try as this may help avoid this problem of having to choose between MaxScoreBulkScorer and BooleanScorer entirely.
