### ISSUE TITLE
IndexSearcher.doc(int docID, Set<String> fieldsToLoad) method is so slow？

### ISSUE THREAD

**Issue by zf853109035** [apache/lucene#12441]
### Description

I created a file-related index and ten 1 MB files. When I did not store the file content, I ran the doc(int docID, Set<String> fieldsToLoad) of the IndexSearcher class ten times, and the delay was about 30 ms. When I stored the file content, If the doc(int docID, Set<String> fieldsToLoad) of the IndexSearcher class runs ten times, the delay is about 150 ms to 200 ms. Even if the fieldsToLoad does not contain the content field, the delay is also slow. How can I optimize the delay? Why is it slow if fieldsToLoad does not contain content filed?

**Comment by mkhludnev** [comment]
It's by-design: whole block of records need to be decompressed and iterated through. Perhaps docValues (eg binary) might provide some sort of selectivity.
