### ISSUE TITLE
Allow FilteredDocIdSetIterator.match(doc) to throw IOException

### ISSUE THREAD

**Issue by DaddyWri** [apache/lucene#12492]
### Description

It would be convenient if org.apache.lucene.search.FilteredDocIdSetIterator#match(doc) would throw an IOException. Right now I'd have to catch the IOException coming from a value source, and wrap it in a runtime exception and then possible unpack it elsewhere. All users of #match(doc) however already declare to throw an IOException today.

**Comment by jpountz** [comment]
If you open a PR, I'll be happy to merge it.
