### ISSUE TITLE
Default PostingsFormat lost the SPI extension point in the Codec class

### ISSUE THREAD

**Issue by sabi0** [apache/lucene#12501]
### Description

`Lucene70Codec` had:
```
private final PostingsFormat defaultFormat = PostingsFormat.forName("Lucene50");
```

In the `Lucene80Codec` PostingsFormat instantiation was moved to the constructor. Presumably to pass the additional `fstLoadMode` parameter?
https://github.com/apache/lucene/commit/28e8a30b536a39e5539ac6e8b9407d31724c8857#diff-3a74c1b72ab52e54dfcdc9de142b4331b372c11bcca87842b001c30f89ce58ebR98

In a subsequent commit the code was reverted to the default PostingsFormat constructor:
https://github.com/apache/lucene/commit/651f41e21bd3df98f70d2673295db29506e3d2e6#diff-3a74c1b72ab52e54dfcdc9de142b4331b372c11bcca87842b001c30f89ce58ebR96

But the SPI call `PostingsFormat.forName()` was not restored. And is still missing in `Lucene95Codec`:
https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene95/Lucene95Codec.java#L121

Restore the SPI extension point to allow overriding the PostingsFormat without having to override the Codec?

**Comment by uschindler** [comment]
Hi,
the SPI should only be used when READING indexes. When you create a codec for IndexWriter the codec version hardcodes its postings formats and other subtypes. As you see it is the same for docValuesFormat and other parts.

This allows to read any index, but when you write an index it will use the exact codec as specified.

Basically we made the decission to hardcode the correct classes when writing indexes, but load the codecs dynamically when open an existing index.

**Comment by sabi0** [comment]
I see. Thank you for the explanation.
The commits that change this behavior did not say anything about this.
So it looked like this SPI extension point loss was an unwitting side-effect of a sequence of refactorings.

**Comment by uschindler** [comment]
> So it looked like this SPI extension point loss was an unwitting side-effect of a sequence of refactorings.

No, the SPI fromName does not allow you to change the implementation, as there can only be one "Lucene50" implementation on classpath. If you want to have another codec it must have a new name and therefore for (new) indexes passed via IndexWriterConfig using a new codec.

> private final PostingsFormat defaultFormat = PostingsFormat.forName("Lucene50");

This does not allow you to overwrite the format, you still need to subclass codec, as the name "Lucene50" is part of Lucene core and can't be replaced. So it will always load the hardcoded 5.0 codec.

**Comment by uschindler** [comment]
For the FST loading mode mentioned above, the codec does not need to be changed, you can tell DirectoryReader to use FST load modes using attributes.

**Comment by uschindler** [comment]
The general rule is: If you want to change the index postings format (but nothing else like codec itsself) when writing a new index, you need to subclass default codec. By that it keeps its name and code reading the index will look it up. If you add a completely new postings format, subclass abstract base class, give it a new name and register it in SPI. If you just want to change settings you can reuse the postings format by instantiating it in the codec with different settings.

**Comment by sabi0** [comment]
The codec classes are `final`.
Besides having two implementations (`Lucene84PostingsFormat` in lucene-core and `MyLucene84PostingsFormat`) with the same "Lucene84" name will likely result in a lookup error?

**Comment by uschindler** [comment]
> The postings format classes are `final`. Besides having two implementations (`Lucene84PostingsFormat` in lucene-core and `MyLucene84PostingsFormat`) with the same "Lucene84" name will likely result in a lookup error?

Exactly and because of that its final. Your postings format needs a new name.

If you want to use it as default you can subclass the `Codec` as this is the main entry point: https://github.com/apache/lucene/blob/df8745e59ee65f276ccaefa87480e1fd85facb56/lucene/core/src/java/org/apache/lucene/codecs/lucene95/Lucene95Codec.java#L55

I don't understand what your problem is:
- Write your own postings format with its own name. You can't subclass. But you can use a FilterPostingsFormat to wrap the default postings format
- Subclass https://github.com/apache/lucene/blob/df8745e59ee65f276ccaefa87480e1fd85facb56/lucene/core/src/java/org/apache/lucene/codecs/lucene95/Lucene95Codec.java#L55 and return/inject your codec there, an alternative which is not so statically depending on the exact version is to use `new FilterCodec(Codec.getDefault()) { ... override method returning postingsFormat()... }`

**Comment by sabi0** [comment]
> > Besides having two implementations ... with the same "Lucene84" name will likely result in a lookup error?
> Exactly and because of that its final.

I just do not understand then how your suggestion to "subclass default codec. By that it keeps its name and code reading the index will look it up" would work?
Having the "official" Lucene95Codec and MyCustomCodec sharing the same "Lucene95" name will result in lookup error, won't it?

So I have to give my custom codec a new name. And then "plug" it in using some configuration property, I suppose?
Or find a way to ensure "my" `META-INF/services` appears on the classpath before lucene-core.jar
