### ISSUE TITLE
clarify QueryVisitor.visitLeaf interaction with QueryVisitor.acceptField

### ISSUE THREAD

**Issue by cpoerschke** [apache/lucene#12538]
### Description

`QueryVisitor.visitLeaf` is described as _"Called by leaf queries that do not match on terms"_ and `QueryVisitor.acceptField` is defined as _"Whether or not terms from this field are of interest to the visitor"_ -- javadocs: https://github.com/apache/lucene/blob/releases/lucene/9.7.0/lucene/core/src/java/org/apache/lucene/search/QueryVisitor.java#L54-L69

**Comment by cpoerschke** [comment]
My interpretation of this is that for queries not matching on terms (i.e. those that call `visitLeaf`) then an `acceptField` call is not applicable since there are no _"terms from this field"_ to accept or not accept. However as illustrated by the exploratory link-to-follow pull request there are several `visitor.acceptField` guards for `visitor.visitLeaf` calls.

Would appreciate any insights on this e.g. can the guards be removed and/or can we clarify the `QueryVisitor` javadocs somehow to make it clearer when to (not) call `acceptFields` first? Thanks!

**Comment by romseygeek** [comment]
I would adjust the docs on `acceptField` to just say "Whether or not this field is of interest to the visitor".  It shouldn't be term-specific.
