### ISSUE TITLE
Is it correct for facets to assume positive aggregation values?

### ISSUE THREAD

**Issue by stefanvodita** [apache/lucene#12585]
### Description

In `IntTaxonomyFacets` and `FloatTaxonomyFacets` when we `getTopChildrenForPath` we maintain a priority queue of aggregation values and corresponding ordinals.
If an aggregation value is not positive, we discard it ([code](https://github.com/apache/lucene/blob/8b84f6c0965dda01514c196126ed10e57cb6d01a/lucene/facet/src/java/org/apache/lucene/facet/taxonomy/FloatTaxonomyFacets.java#L219)). If it is not larger than the lowest value in the queue (initially set to 0), we also discard it ([code](https://github.com/apache/lucene/blob/8b84f6c0965dda01514c196126ed10e57cb6d01a/lucene/facet/src/java/org/apache/lucene/facet/taxonomy/FloatTaxonomyFacets.java#L222)).

It looks like the facets assume aggregation results should be positive, but I think we could have negatives or zeroes. I wrote a [unit test to demo this](https://github.com/apache/lucene/commit/d1455fd9447011d1209f7f965afd6c1aa03ad5c1).
The current behavior makes sense for counts. Counts are always non-negative and we probably don't care about counts of 0. But does it make sense for other aggregations?

**Comment by gsmiller** [comment]
Yeah, this is a good callout. I ran into this when adding more flexibility to association faceting a while back (making note that supporting, e.g., "min" would require rethinking these assumptions).

My opinion is that the current assumption makes sense for the faceting support _currently available_, but I know there's conversation going on more generally about improving (rethinking?) aggregation capabilities in Lucene. My preference on this would be to, 1) leave this current behavior in place unless there is a use-case that's immediately blocked by it, but 2) include it in some broader rethinking of Lucene aggregation capabilities. As a side-note on that, I wonder if a successful approach to moving forward with some new aggregation thinking would be to _not_ try to modify the faceting module as-is, but rather spin up a new "aggregations" module under "sandbox" to start sketching out ideas. I think it will be difficult to retrofit more flexible aggregation capabilities into the faceting API that exists today, but maybe I'm wrong? OK, I'm off in the weeds now...

**Comment by stefanvodita** [comment]
> not try to modify the faceting module as-is, but rather spin up a new "aggregations" module

I'm definitely leaning that way too right now. @Shradha26 and I were considering this (#12553). I initially thought faceting can fill most of the gaps we were identifying. What got me to change my mind was seeing how much extra work there is to bring in a new feature when it has to be reimplemented for multiple faceting classes. If we made facets generic, that would already be a significant rework, so maybe we might as well start fresh? There's other things that are difficult to do with facets - arbitrary aggregation groups come to mind, but genericity is the one that convinced me that it's a better strategy to have a dedicated aggregation engine. I'm sure there are counter-arguments as well or maybe I'm overstating the impact of genericity.

**Comment by stefanvodita** [comment]
I thought some more about this issue and it really seems like a bug that I can have a non-positive aggregation value, but I can't return it in top children.
If we were to address it, I can think of three approaches:
1. Choose a magic value that communicates to us that an ordinal was not encountered. This magic value is 0 right now. Maybe `Integer.MIN_VALUE` and `Float.MAX_VALUE` might be better choices, allowing for more valid aggregation values.
2. Store a boolean for each ordinal. This would produce correct results, but cost more memory.
3. Use a map to store the arrays. `IntTaxonomyFacets` already does this in some cases and I [think](https://github.com/apache/lucene/issues/12576#issuecomment-1783545880) this might be appropriate in enough cases that we can always use a map.

**Comment by gsmiller** [comment]
I think I'd be curious if there are many real-world use-cases out there that have a non-positive association between each document and facet label? I would guess it's pretty uncommon. I actually can't really contrive an example either. @stefanvodita have you encountered real-world use-cases that would benefit from this? Apologies if you describe it somewhere and I'm missing it.
