### ISSUE TITLE
ability to run JMH benchmarks from gradle

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#12641]
### Description

Background: I'm having a hard time keeping https://github.com/rmuir/vectorbench up to date, the code has differences with what the integrated vector code in lucene is, I have to copy/paste back and forth to run tests vs microbenchmarks, it is quite tedious and error-prone.

I think it would be better to just have benchmark files that we can run from here? I tried my hand at https://github.com/melix/jmh-gradle-plugin but it didn't seem to play well with things like `apply plugin` conditionally, or our alt-jvm usage. Probably easier to just have a simple JavaExec-type task that launches it the way we want?

IMO: it would be great to just be able to run `./gradlew microbench` or something to run these benchmarks. And to call our actual code, not a copy-paste of it (e.g. VectorUtil.xxxx).

**Comment by dweiss** [comment]
JMH is fairly self-contained, I don't think it should be a big deal to wrap it up into a separate module, without external plugins (which are problematic to debug, in case of problems or conflicts with the existing infrastructure). I may take a look at that towards the end of the week, if nobody beats me to it.

**Comment by dweiss** [comment]
Thanks @risdenk ! I'll be taking a look at this on Thursday.

**Comment by dweiss** [comment]
I filed an initial take on this here:
https://github.com/apache/lucene/pull/12663

Copied just one of your existing benchmarks, Rob. Try if it fits your needs. I mentioned on the PR that there is no specific task to launch a benchmark - this is easy to add, I'm just not sure if it's a good idea to do so... Especially that you can always pipe:

```
gradlew -p lucene/benchmark-jmh assemble && java --module-path lucene/benchmark-jmh/build/benchmarks --module org.apache.lucene.benchmark.jmh
```

or even create a bash alias for it?...

**Comment by dweiss** [comment]
I left just a single benchmark in, @rmuir - if you'd like to move all of them, please do so. If something doesn't work, let me know (it should though).

**Comment by rmuir** [comment]
@dweiss thank you, I will fix and cleanup all the benchmarks and archive https://github.com/rmuir/vectorbench as soon as I can :)

**Comment by rmuir** [comment]
I can also add some stuff from the README there such as how to install the disassembler. It is stuff that you forget easily if you haven't done it in a while.
