### ISSUE TITLE
Make OrdinalMap maps docID to global ordinal directly？

### ISSUE THREAD

**Issue by vsop-479** [apache/lucene#12669]
### Description

OrdinalMap maps segment ordinal to global ordinal. When collecting, we need read segment ordinal by docID, and get global ordinal by segment ordinal.
If OrdinalMap maps docID to global ordinal, we can get global ordinal by docID directly without reading segment ordinal.
It may good to performance, but the global ordinals can not keep monotonic, which may harm to memory.

**Comment by jpountz** [comment]
> the global ordinals can not keep monotonic, which may harm to memory.

The other downside is that you then need to store `maxDoc` global ordinals (one per doc) instead of `valueCount` global ordinals. Combined with the fact that we cannot take advantage of the fact that global ords are monotonic for compression, this would be extremely memory-inefficient.

**Comment by vsop-479** [comment]
> need to store maxDoc global ordinals (one per doc) instead of valueCount global ordinals. 

@jpountz Thanks for remind that. I will close this issue.
