### ISSUE TITLE
MultiSimilarity.MultiSimScorer should sum up scores into a double

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12675]
We generally prefer scores to not depend on the order of clauses, e.g. BM25's multi-term sim scorer, disjunctive and conjunctive queries all sum up scores into a double to reduce accuracy issues. We should do the same in `MultiSimilarity.MultiSimScorer`.

**Comment by shubhamvishu** [comment]
@jpountz I have raised a PR #12682 with the fix to `MultiSimilarity.MultiSimScorer` and some other candidate scorers I could find with similar issue.

**Comment by KunalSanghvi** [comment]
@jpountz Hi, I was thinking of solving this error, just wanted to know if it is solved?

**Comment by jpountz** [comment]
Thas has been addressed by #12682. Thanks @KunalSanghvi for contributing and @benwtrent for merging!

**Comment by shubhamvishu** [comment]
@jpountz I think we can close this now?

**Comment by jpountz** [comment]
@shubhamvishu Yes indeed!
