### ISSUE TITLE
`IndexOrDocValuesQuery` does not support query highlighting

### ISSUE THREAD

**Issue by harshavamsi** [apache/lucene#12686]
### Description

While working with the `IndexOrDocValuesQuery` in https://github.com/opensearch-project/OpenSearch/issues/7057, I noticed that highlighting was broken. This is potentially caused by the extract function that does not check if the query is indexordocvalue.

https://github.com/apache/lucene/blob/main/lucene/highlighter/src/java/org/apache/lucene/search/highlight/WeightedSpanTermExtractor.java#L128

### Version and environment details

Lucene version 9.8.0

**Comment by prudhvigodithi** [comment]
Hey @harshavamsi the PR to support the `IndexOrDocValuesQuery` for query highlighting is now merged.
Thanks.
@getsaurabh02 @msfroh

**Comment by harshavamsi** [comment]
Thanks @prudhvigodithi!
