### ISSUE TITLE
Should we handle negative scores due to floating point arithmetic errors?

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#12700]
### Description

VectorSimilarityFunction might return negative scores in extreme circumstances.

This could happen if `VectorUtil#cosine` returns something like `-1.0000001` instead of just `-1` for antipodal vectors. Then the similarity score would be `-0.0000005` (this numbers are made up, and don't reflect a scenario I have actually seen).

We already know that the floating point error compounds on larger vectors and using Panama. 

Should we snap vector scores to `0` to ensure this doesn't happen? Or rely on users of the library to do such?

Here is a related ES bug: https://github.com/elastic/elasticsearch/issues/100975

NOTE: That bug is over 1536 dims, not the Lucene limit of 1024. However, it seems to me that this is a possibility even over 1024 dimensions.

I am fine if the consensus is "library users just handle it". But it seems like something every user would be potentially concerned about.

**Comment by jpountz** [comment]
We made changes to similarities to guarantee monotonicity with tf and norm (e.g. https://github.com/apache/lucene/issues/9063) despite floating-point rounding errors. I think we should do the same here.
