### ISSUE TITLE
FSTCompiler's NodeHash should fully duplicate `byte[]` slices from the growing FST

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12714]
### Description

To share suffixes, for creating as minimal an FST as we can, `FSTCompiler` uses `NodeHash` to record the most recently used/shared suffixes.  But it stores the values (the nodes themselves) by referencing slices in the `BytesStore` of the growing FST.

But we would like to move to a fully off-heap FST while building, i.e. we append the FST bytes to disk as it grows.  In order to do this, we need to duplicate the `byte[]` slices for the common suffix nodes into the `NodeHash`.  (We briefly considered being able to read the bytes from the still writing file, to avoid this duplication, but this is not really a viable option -- see the [dev list discussion](https://lists.apache.org/thread/xfjjpkbwfbf6c0qg00msow0dt3odtqqw)).

One exciting option raised on that thread is to use a standard NIO file (sidestepping Lucene's Directory abstraction) just for building the FST.  FSTCompiler would append its bytes to this file, and NodeHash would randomly read from it (OS would keep it all hot, most likely) and after it's all done, copy the FST bytes through Directory to the actual target.  I think this option may be compelling, but it'd require the user/app to be aware that e.g. Lucene will directly open `tmp` files NOT through `createTempFile` abstraction.

Before we consider that "direct to NIO" option, let's explore fully copying the `byte[]` slices into `NodeHash` and see how bad the wasted RAM is?  Maybe the resulting curve of RAM vs minimality is acceptable?  Failing that, we can explore the "direct to NIO" option?

**Comment by mikemccand** [comment]
I think we can use `ByteBlockPool` to store the `byte[]` slices, just appending a new `byte[]` slice when we store a new suffix.  We never delete individual suffixes, but rather discard the entire "secondary" hash map in the double barrel cache, so we could just drop/recycle the `ByteBlockPool` at that point too.

**Comment by mikemccand** [comment]
I made a quick hackity change, just to measure the number of additional bytes we'd "typically" have to copy in order to duplicate suffix bytes from the growing (forced append-only) FST, and the results are kinda depressing :)

```
on fallback: 41394190 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 37687027 bytes would be copied; ramBytesUsed=16777216                                                                                                
on fallback: 23689680 bytes would be copied; ramBytesUsed=16777216                                                                                                
on fallback: 29950030 bytes would be copied; ramBytesUsed=16777216                                                                                                
on fallback: 30583201 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 27922501 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 27712324 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 29407790 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 31510848 bytes would be copied; ramBytesUsed=16777218                                                                                                
on fallback: 31530558 bytes would be copied; ramBytesUsed=16777217                                                                                                
on fallback: 30333984 bytes would be copied; ramBytesUsed=16777217                                                                                                
on fallback: 33169962 bytes would be copied; ramBytesUsed=16777217                                                                                                
on fallback: 29209248 bytes would be copied; ramBytesUsed=16777217    
```

This is just printing the number of bytes we'd have to duplicate out of the FST's growing `byte[]`, each time one half of the double-barrel LRU cache is full (fallback).  Net/net it'd result in about 3X more RAM usage in the `NodeHash`, to achieve the same minimal FST as today, sigh.

But a more glass-half-full outlook is that it would allow us to directly append the growing FST bytes to disk, instead of holding them indefinitely growing in RAM, and so net/net the two changes combined would necessarily mean less RAM used to build a given FST.  It's just that we are shifting the RAM budget away from holding the full FST, to only holding the necessary suffix nodes bytes, and that is tunable by the provided RAM budget.  Net/net it's still a win.

Here's the change I tested -- only to measure the added RAM needed, not actually implementing the copying yet:

```
diff --git a/lucene/core/src/java/org/apache/lucene/util/fst/NodeHash.java b/lucene/core/src/java/org/apache/lucene/util/fst/NodeHash.java
index 04c1be414c2..762be55bf10 100644
--- a/lucene/core/src/java/org/apache/lucene/util/fst/NodeHash.java
+++ b/lucene/core/src/java/org/apache/lucene/util/fst/NodeHash.java
@@ -19,6 +19,7 @@ package org.apache.lucene.util.fst;
 import java.io.IOException;
 import org.apache.lucene.util.packed.PackedInts;
 import org.apache.lucene.util.packed.PagedGrowableWriter;
+import org.apache.lucene.util.ByteBlockPool;
 
 // TODO: any way to make a reverse suffix lookup (msokolov's idea) instead of more costly hash?
 // hmmm, though, hash is not so wasteful
@@ -51,6 +52,8 @@ final class NodeHash<T> {
   private final FST.Arc<T> scratchArc = new FST.Arc<>();
   private final FST.BytesReader in;
 
+  private int lastNodeNumBytes;
+
   /**
    * ramLimitMB is the max RAM we can use for recording suffixes. If we hit this limit, the least
    * recently used suffixes are discarded, and the FST is no longer minimalI. Still, larger
@@ -110,13 +113,22 @@ final class NodeHash<T> {
         node = getFallback(nodeIn, hash);
         if (node != 0) {
           // it was already in fallback -- promote to primary
-          primaryTable.set(pos, node);
+          primaryTable.set(pos, node, lastNodeNumBytes);
         } else {
           // not in fallback either -- freeze & add the incoming node
 
+          long posStart = fstCompiler.bytes.getPosition();
+
           // freeze & add
           node = fstCompiler.addNode(nodeIn);
 
+          long posEnd = fstCompiler.bytes.getPosition();
+
+          // make sure i get the order right:
+          assert posEnd > posStart;
+
+          int numBytesToCopy = Math.toIntExact(posEnd - posStart);
+
           // we use 0 as empty marker in hash table, so it better be impossible to get a frozen node
           // at 0:
           assert node != 0;
@@ -124,7 +136,7 @@ final class NodeHash<T> {
           // confirm frozen hash and unfrozen hash are the same
           assert hash(node) == hash : "mismatch frozenHash=" + hash(node) + " vs hash=" + hash;
 
-          primaryTable.set(pos, node);
+          primaryTable.set(pos, node, numBytesToCopy);
         }
 
         // how many bytes would be used if we had "perfect" hashing:
@@ -144,6 +156,7 @@ final class NodeHash<T> {
           // time to fallback -- fallback is now used read-only to promote a node (suffix) to
           // primary if we encounter it again
           fallbackTable = primaryTable;
+          System.out.println("on fallback: " + fallbackTable.numBytesCopied + " bytes would be copied; ramBytesUsed=" + ramBytesUsed);
           // size primary table the same size to reduce rehash cost
           // TODO: we could clear & reuse the previous fallbackTable, instead of allocating a new
           //       to reduce GC load
@@ -210,6 +223,8 @@ final class NodeHash<T> {
     return h;
   }
 
+  // nocommit explain side effect setting lastNodeNumBytes
+  
   /**
    * Compares an unfrozen node (UnCompiledNode) with a frozen node at byte location address (long),
    * returning true if they are equal.
@@ -255,6 +270,7 @@ final class NodeHash<T> {
 
       if (scratchArc.isLast()) {
         if (arcUpto == node.numArcs - 1) {
+          lastNodeNumBytes = Math.toIntExact(address - in.getPosition());
           return true;
         } else {
           return false;
@@ -274,6 +290,8 @@ final class NodeHash<T> {
     private PagedGrowableWriter entries;
     private long count;
     private long mask;
+    private long numBytesCopied;
+    private ByteBlockPool copiedNodes;
 
     // 256K blocks, but note that the final block is sized only as needed so it won't use the full
     // block size when just a few elements were written to it
@@ -282,6 +300,7 @@ final class NodeHash<T> {
     public PagedGrowableHash() {
       entries = new PagedGrowableWriter(16, BLOCK_SIZE_BYTES, 8, PackedInts.COMPACT);
       mask = 15;
+      copiedNodes = new ByteBlockPool(new ByteBlockPool.DirectAllocator());
     }
 
     public PagedGrowableHash(long lastNodeAddress, long size) {
@@ -290,16 +309,25 @@ final class NodeHash<T> {
               size, BLOCK_SIZE_BYTES, PackedInts.bitsRequired(lastNodeAddress), PackedInts.COMPACT);
       mask = size - 1;
       assert (mask & size) == 0 : "size must be a power-of-2; got size=" + size + " mask=" + mask;
+      copiedNodes = new ByteBlockPool(new ByteBlockPool.DirectAllocator());
     }
 
     public long get(long index) {
       return entries.get(index);
     }
 
+    /*
     public void set(long index, long pointer) throws IOException {
       entries.set(index, pointer);
       count++;
     }
+    */
+
+    public void set(long index, long pointer, int numBytesToCopy) throws IOException {
+      entries.set(index, pointer);
+      count++;
+      numBytesCopied += numBytesToCopy;
+    }
 
     private void rehash(long lastNodeAddress) throws IOException {
       // double hash table size on each rehash

```

**Comment by dungba88** [comment]
If we are to move to value-based LRU cache and no longer fall back to reading FST when items are not in the map, I'm wondering why wouldn't we just use LinkedHashMap (or any doubly-linked link based LRU map)? It sounds to me that we could write through to such map (write to both the map and the main FST), and evict the node of least-recently write or read?

Concretely, we could add a Node struct like

```
class CacheNode {
    long address;
    UnCompiledNode<T> node;
}
```

And then use `LinkedHashMap<CacheNode>`.

**Comment by dweiss** [comment]
I'd check whether there's much gain from the switch first. Fill-up-then-discard caches often perform quite well and allow for much easier/faster implementation (both in terms of GC overhead and complexity of cache maintenance).

**Comment by dungba88** [comment]
I ran a small test to see what RAM would be needed for some sample dictionary using a simple `LinkedHashMap<UnCompiledNode, Long>`:

6MB Cache size
62457 items
977KB FST size

The reported RAM might be a bit under-estimated, and it seems cache size is 6x the FST size. Using byte-array representation would be more efficient than naive UnCompiledNode (maybe down to 3x like Mike has reported). The benefit is simple implementation & maintenance.

Perhaps instead of UnCompiledNode, we could encode it as byte-array (could take the same format as the FST-encoded binary, but the FST operation works on absolute address value thus would need some modification). In any case, this binary-encoded could use doubly linked list for LRU cache as well. I'm unsure what double barrel cache would bring, as they (at worst) would only have 1/2 normal capacity.

**Comment by mikemccand** [comment]
> Perhaps instead of UnCompiledNode, we could encode it as byte-array (could take the same format as the FST-encoded binary, but the FST operation works on absolute address value thus would need some modification).

+1 my plan here is to simply take the `byte[]` slice encoding of that one node, clone it into an appending `ByteBlockPool` (one for each of the two hash sets in the double-barrel cache), and use that for the exact value comparison to an incoming `UnCompiledNode`.  It's the same is is done today, it's just that the `byte[]` comes from our copy instead of the appending FST.

> And then use LinkedHashSet<UnCompiledNode, Long>.

Yeah this is the obvious way to implement an LRU cache in Java, but the RAM overhead is just astounding compared to the double-barrel hash set we use now, I suspect.

**Comment by dungba88** [comment]
I think that makes sense.

I attempted to implement the copy bytes (not optimizing though, and there are lots of non-optimal bytes read/write).

With the same FST as above, it uses 513KB cache size, while with the address-based it's 150KB, so it's aligned with the 3x number reported by Mike.

There are some quirks I found while implementing:
- As the ByteBlockPool seem to merely a very long byte array (which was divided into multiple byte array), we still need to record and map the FST real address to the offset of the copied bytes (unless there's already a tracking mechanism that I'm unaware of). Maybe we can use an additional PagedBytesWriter?
- As FST operations acts on the real, absolute address, I created a new layer of `ReverseBytesReader` which does the mapping automatically.
- The implementation first copy the node bytes from BytesStore into a new temporary byte[], and then write this byte[] into the primary table ByteBlockPool. We could directly from BytesStore into ByteBlockPool.

I could put a draft and gradually improve it.

**Comment by dungba88** [comment]
An updated statistics based on the new implementation.

RAM Limit | Actual cache size | Cached nodes | FST size
---|---|---|---
No limit | 1.4MB | 62457 | 977KB
1MB | 443KB | 9964 | 1014KB
512KB | 213MB | 4466 | 1054KB

Interestingly the cache does not take up the maximum memory.
