### ISSUE TITLE
Should we ban Random#nextInt(int, int)?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12771]
### Description

Spinoff from backporting #12506 which was using the [Random#nextInt(int, int) method](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/random/RandomGenerator.html#nextInt(int,int)), but that's not available in JDK 11.

While doing this I read its javadocs and this part kinda scared me:

```
Implementation Requirements:

The default implementation checks that origin and bound are positive ints. Then invokes nextInt(), limiting the result to be greater that or equal origin and less than bound. If bound is a power of two then limiting is a simple masking operation. Otherwise, the result is re-calculated by invoking nextInt() until the result is greater than or equal origin and less than bound.
```

Specifically the `Otherwise, the result is re-calculated by invoking nextInt() until the result is greater than or equal origin and less than bound.`.

I think the impl favors "true-ish" randomness over performance?  But I think it means if you ask for a small range it might have to run a great many iterations to finally find a random number in bounds.

Maybe we should ban that?  Seems like a performance trap for our tests.  And anyways we have other ways to get random ints in a range (`TestUtil.nextInt`, randomizedtesting's `RandomNumbers.randomIntBetween`).

**Comment by mikemccand** [comment]
@rmuir pointed out `nextLong(long, long)` has the same warning.  I'll open a PR to ban both.

**Comment by dungba88** [comment]
I think [nextInt(int)](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/random/RandomGenerator.html#nextInt(int)) and [nextLong(long)](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/random/RandomGenerator.html#nextLong(long)) have the same problem as well?

**Comment by mikemccand** [comment]
Indeed, the javadocs have the same terrifying explanation -- thanks @dungba88!: `If bound is a power of two then limiting is a simple masking operation. Otherwise, the result is re-calculated by invoking nextInt() until the result is greater than or equal zero and less than bound.`

Fortunately, thanks to @rmuir digging into OpenJDK sources, it looks like this is a false alarm: these methods first pre-mask to the "next largest power of 2" fully containing the requested range, and iteratively pull random numbers in that range, until finding one within the requested (not necessarily power of 2) range.  So the number of iterations of that loop is "typically" very low (1 or 2).  I cancelled the PR (#12772) and forgot to close this issue -- closing now.
