### ISSUE TITLE
Unroll or vectorize Math.max in CompetitiveImpactAccumulator.addAll?

### ISSUE THREAD

**Issue by vsop-479** [apache/lucene#12788]
### Description

Does it worth to make Math.max in CompetitiveImpactAccumulator.addAll unrolled or vectorized?
Maybe scalar can be auto vectorized by JIT, but there is some speed up with unrolled on my computer(mac m2).
What i can't figure out is vectorized implementation get the worst performance, maybe the cpu architecture? because i measure the performance use dotProduct too,  vectorized implementation is also the worst.

Max | ns | diff
-- | -- | --
scalar | 26041 | -
unrolled | 23625 |  +9.2%
vectorized | 888084 | -

# unrolled
````
for (int i = 0; i < 256; i += 8) {
      a[i] = Math.max(a[i], b[i]);
      a[i + 1] = Math.max(a[i + 1], b[i + 1]);
      a[i + 2] = Math.max(a[i + 2], b[i + 2]);
      a[i + 3] = Math.max(a[i + 3], b[i + 3]);
      a[i + 4] = Math.max(a[i + 4], b[i + 4]);
      a[i + 5] = Math.max(a[i + 5], b[i + 5]);
      a[i + 6] = Math.max(a[i + 6], b[i + 6]);
      a[i + 7] = Math.max(a[i + 7], b[i + 7]);
    }
````

# vectorized
````
for (; i < SPECIES.loopBound(a.length); i += SPECIES.length()) {
      IntVector vectorA = IntVector.fromArray(SPECIES, a, i);
      IntVector vectorB = IntVector.fromArray(SPECIES, b, i);
      IntVector vectorC = vectorA.max(vectorB);
      vectorC.intoArray(a, i);
    }
````

**Comment by vsop-479** [comment]
@jpountz Please take a look when you get a chance!

**Comment by jpountz** [comment]
Oh, it's sad that this loop doesn't get auto-vectorized automatically. Out of curiosity, are you seeing it show up in some benchmarks?

**Comment by rmuir** [comment]
> Oh, it's sad that this loop doesn't get auto-vectorized automatically. Out of curiosity, are you seeing it show up in some benchmarks

I don't believe that, there is code to do it on x86 and arm. try the latest JDK and print the assembler.

there is not really a need to do crazy unrolling and stuff except for floating point. it is needed because compiler won't do it for us there since it changes results.

**Comment by vsop-479** [comment]
> To benchmark then use the benchmark-jmh Gradle module. This will enable vectorization if all is sane.

Thanks for your explanation. I will try it.

> are you seeing it show up in some benchmarks?

> try the latest JDK and print the assembler.

Sorry, I just measure them in a demo class with main method, and there may be some mistake.
I will try the latest JDK and print the assembly code to figure out it.

**Comment by vsop-479** [comment]
> To benchmark then use the benchmark-jmh Gradle module

I measured max with scalar, unroll, vector  implementation by benchmark-jmh: 
  

    Benchmark                      (size)   Mode  Cnt   Score   Error   Units
    VectorUtilBenchmark.maxScalar     256  thrpt   15  51.056 ± 0.310  ops/us
    VectorUtilBenchmark.maxUnroll     256  thrpt   15  12.799 ± 0.036  ops/us
    VectorUtilBenchmark.maxVector     256  thrpt   15  53.381 ± 3.112  ops/us

Assembly code indicates that: 
Scalar get auto-vectorized, and auto-unrolled. @jpountz 
Unroll doesn't get auto-vectorized.
Vector get auto-unrolled.


# Assembly code sample

````
//  for scalar and vector.
smax  v16.4s, v16.4s, v17.4s 
add   w10, w2, #0x10  // 4 times smax, 1 add.

// for unroll.
cmp   w12, w11
csel  w11, w12, w11, gt // cmp, csel. 
````
