### ISSUE TITLE
Grow arrays up to a given limit to avoid overallocation where possible

### ISSUE THREAD

**Issue by stefanvodita** [apache/lucene#12839]
### Description

`ArrayUtils` provides methods to grow arrays, overallocating exponentially, with the possibility of requesting a minimum size.
Sometimes we have an upper limit to the number of elements that would go into that array. In those situations, it would be nice to have a method that grows up to a limit.
For example, `DirectoryTaxonomyReader.getBulkOrdinals` dynamically grows an array pointing to ordinals missing from the cache ([code](https://github.com/apache/lucene/blob/981339be0413730598631c1f578ba8a6493061b9/lucene/facet/src/java/org/apache/lucene/facet/taxonomy/directory/DirectoryTaxonomyReader.java#L354)). But we know ahead of time there can't be more missing ordinals than there are ordinals in the taxonomy. We can limit the array growth to avoid overallocating.
This pattern might be applicable in multiple places. `TermsAutomatonScorer` seems to use a [similar pattern](https://github.com/apache/lucene/blob/981339be0413730598631c1f578ba8a6493061b9/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/TermAutomatonScorer.java#L294).

The API could look like this:
```
public static int[] growInRange(int[] array, int minLength, int maxLength)
```

**Comment by jpountz** [comment]
If I'm not mistaken, the `NeighborArray` class we use for vector search may have similar needs (it should probably not size its data structure to `maxSize` i the constructor?).

**Comment by stefanvodita** [comment]
Thank you for the pointer @jpountz! I'll put together a PR.

**Comment by stefanvodita** [comment]
I added the new method and used it for `DirectoryTaxonomyReader` and `NeighborArray` (#12844). There might be other places where it makes sense to use, but I thought it best to get some feedback before going and hunting down more of those cases.
