### ISSUE TITLE
Reproducible failure of TestParentBlockJoinByteKnnVectorQuery.testScoringWithMultipleChildren

### ISSUE THREAD

**Issue by gsmiller** [apache/lucene#12896]
### Description

Saw this test fail a couple times in automated builds (e.g., [here](https://jenkins.thetaphi.de/job/Lucene-main-Windows/13501/testReport/junit/org.apache.lucene.search.join/TestParentBlockJoinByteKnnVectorQuery/testScoringWithMultipleChildren/)).

I was able to reproduce locally against `main` with: `./gradlew test --tests TestParentBlockJoinByteKnnVectorQuery.testScoringWithMultipleChildren -Dtests.seed=98B9F347D87BF07E`

### Version and environment details

Reproduced on the `main` branch

**Comment by zhaih** [comment]
Oh probably not, the test is just using the default merge policy (TMP)

**Comment by msokolov** [comment]
I think it's simply that the test writer chooses to flush randomly, creating two segments instead of one. I was able to fix by adding a call to forceMerge(1). Opened https://github.com/apache/lucene/pull/12928 so GH can do the precommit checks for me
