### ISSUE TITLE
Improve BWC tests to reveal #12895 and confirm its fix

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12901]
### Description

Spinoff from #12895 where we inadvertently introduced read-time exceptions in `MultiTermQueries` (e.g. `WildcardQuery` `*fo*`) in 9.9.0 when reading pre-9.9.0 written indices.

Our `TestBackwardsCompatibility` test should have caught this but clearly did not.

Let's:
  1. Make a test revealing #12895 
  2. Confirm the test (and all other tests) pass when applying the proposed PR fix #12900
  3. Merge the new test case
  4. Merge the fix in #12900 

Hopefully in that order?

We could simply snapshot the `wikibigall` index into BWC zip files, but, that's way too massive.  Can we instead make a randomized test that indexes fewer-ish terms and reveals the bug?  With "just so" set of terms, the bug should reproduce with a tiny index.  We could maybe iterate to "just so" by tweaking the set of terms' prefixes until the on-disk file pointers of each block share the last 6 bits of their respective pointers?

**Comment by jpountz** [comment]
IMO one thing to improve here is that we changed file formats for the MSB vlong optimization by bumping the file format version number, changing the writer to write the new version and adding version checks to the reader. But we sometimes also change file formats by forking the code, like we did with `Lucene90PostingsFormat` -> `Lucene99PostingsFormat`. A benefit of the latter approach is that we keep existing tests in place, specifically `BasePostingsFormatTestCase` which has pretty good coverage, probably more than what `TestBackwardsCompatibility` will ever be able to check? We should look into more systematically forking the code when we do a file format change, or figuring out other ways to keep testing prior formats with version bumps, e.g. by retaining version checks on the write side and making sure there is a separate `BasePostingsFormatTestCase` impl for every version number?

**Comment by jpountz** [comment]
> A benefit of the latter approach is that we keep existing tests in place, specifically BasePostingsFormatTestCase

Actually, it seems like we lost the test as part of refactorings, I'm adding it back in #12904.

**Comment by mikemccand** [comment]
> We should look into more systematically forking the code when we do a file format change, or figuring out other ways to keep testing prior formats with version bumps, e.g. by retaining version checks on the write side and making sure there is a separate `BasePostingsFormatTestCase` impl for every version number?

+1 -- normally forking/duplicating code is a bad thing, but for BWC testing, and for code clarity and our sanity keeping track of code changes that correspond to our on-disk format changes, it is the lesser evil (to fork).

And I think #12908 is a case-in-point showing how risky it is to try to add the right `if` statements on the write side -- the `precommit` failures there are subtle and I think maybe due to a missing `if` statement somewhere in the code changes...

**Comment by jpountz** [comment]
Agreed, I didn't want to go the forking route for `FST`, which I'm not too familiar with, but ideally we'd version it like other file formats: FST90, FST99, etc.

**Comment by mikemccand** [comment]
I have a smallish failing test case here!  (~49 KB .zip file)

I created it by first extracting all ~5.8 M unique terms from a `wikibigall` index, creating a tool that randomly picks a sequential slice of length [1_000..100_000) of those terms, indexing that, then a read-time test that tries to run random two-letter ascii `WildcardQuery`.  It ran multiple iterations until it tickled the bug.  I'll post this test-case-discovery-scaffolding code here in case we need to do such things to find future exotic test cases ... and I'll work up a PR to add this "special" index to our BWC tests and confirm it's failing in 9.9.x.

**Comment by mikemccand** [comment]
OK  this is done -- I pushed the new BWC test case (@Ignore'd) to 9.9.x, 9.x and main.

Actually I can un-@Ignore at least in main.  I'll go do that.

**Comment by mikemccand** [comment]
> Actually I can un-@ignore at least in main. I'll go do that.

D'oh!  No, I cannot -- it will still fail in main, 9.x and 9.9.x until we get the fix (#12900) in.
