### ISSUE TITLE
jenkins dump file traversal exceptions ("no matches found within 10000")

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#12907]
### Description

These stack traces at the end of jenkins runs are super annoying:
```
...
Archiving artifacts
hudson.FilePath$ValidateAntFileMask$1Cancel
        at hudson.FilePath$ValidateAntFileMask$1.isCaseSensitive(FilePath.java:3300)
        at org.apache.tools.ant.DirectoryScanner.lambda$isIncluded$3(DirectoryScanner.java:1374)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
...
        at hudson.FilePath$ValidateAntFileMask.hasMatch(FilePath.java:3313)
Caused: hudson.FilePath$FileMaskNoMatchesFoundException: no matches found within 10000
```

This is a weird path traversal limit in jenkins (to dodge circular link structure, I guess) that is configurable via system properties -

https://www.jenkins.io/doc/book/managing/system-properties/#hudson-filepath-validate_ant_file_mask_bound

I don't think we can tweak it but we can change the default path traversal patterns to be more restrictive:
```
No artifacts found that match the file pattern "**/*.events,heapdumps/**,**/hs_err_pid*". Configuration error?
```

The `*.events` is no longer used (used to be emitted from the custom runner in ant). I don't think we can limit the scanning pattern to not exceed the limit but I think we can add a test finalization task to gradle that will scan only those folders that can contains hs_err_pid* files and perhaps copy them over to one top-level directory, then add a much simpler pattern to include anything present in that folder?

**Comment by dweiss** [comment]
I though changing the pattern to lucene/**/build/hs_err_pid* would help but there's way too many files/folders in there so it'll eventually hit that threshold anyway. Unless we set the threshold to MAX_VALUE, which then bypasses the entire "early exit" logic:

https://github.com/jenkinsci/jenkins/blob/f9a777bc682963de4640303b2f28ac488f9b93ef/core/src/main/java/hudson/FilePath.java#L3295-L3299

Now I see that there is even a hardcoded timeout condition placed in there if traversal bound is provided. So strange.

**Comment by uschindler** [comment]
If you set the bound to `Integer#MAX_VALUE` then it uses default directory scanner without time-based limutations: https://github.com/jenkinsci/jenkins/blob/f9a777bc682963de4640303b2f28ac488f9b93ef/core/src/main/java/hudson/FilePath.java#L3295

I will pass this in the Policeman Jenkins init file.

**Comment by uschindler** [comment]
Hi I found the problem, /etc/default/jenkins is no longer interpreted by jenkins systemd. I moved the stuff to override file (and deleted the defaults file). Now looks fine on Policeman:

```
jenkins  2465142       1 99 17:24 ?        00:00:50 /usr/local/bin/java -XX:+UseG1GC -Xms8g -Xmx8g -XX:MaxPermSize=512m -Dhudson.model.DirectoryBrowserSupport.CSP= -Djava.awt.headless=true -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Dhudson.FilePath.VALIDATE_ANT_FILE_MASK_BOUND=2147483647 -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8095 --httpListenAddress=127.0.0.1
```

**Comment by dweiss** [comment]
Thanks, Uwe! The problem is on ASF infrastructure - that's where I see those exceptions most in my emails/ log messages. I don't know if there is a way to tweak it just for Lucene workers. Do you think it's worth asking infra? Seems like it's a single Jenkins instance all across the board.

**Comment by uschindler** [comment]
This is a global option, you can only change it for the main jenkins. The workers are started remotely and get the same flag over the wire on startup.

**Comment by uschindler** [comment]
Looks like you can't pass sysprops to individual workers. There are different types of workers (I use shell script launcher as this works better with Virtualbox), but the default launchers with SSH or JNDI can't pass properties, only env args.

**Comment by uschindler** [comment]
I figured out: The stack trace is only printed when it works remotely. The master agent does not print stack trace. Too bad. On Policeman Jenkins Windows and Jenkisn Mac logs you also see the message. It should have disappeared now, give it a minute to finish first build.

**Comment by uschindler** [comment]
On Policeman Jenkins the stack traces are gone and the message, too @ Main, Mac, Win

**Comment by dweiss** [comment]
https://ci-builds.apache.org/job/Lucene/job/Lucene-Check-9.x/7134/consoleText

So, is the trick you found out applicable to Apache's CI? Could infra help us with that somehow?

**Comment by dweiss** [comment]
I asked Infra, here: https://issues.apache.org/jira/browse/INFRA-25269

**Comment by uschindler** [comment]
I don't understand the problem they'd like to solve. The DirectoryScanner class of ant is able to find those loops. Otherwise Gradle or Ant would have the same problem.

See: https://github.com/apache/ant/blob/12cbc24f63f495cafed7c3fdd1dcbb8b759f42b3/src/main/org/apache/tools/ant/DirectoryScanner.java#L1814

I have no idea why Jenkins has that code.

**Comment by dweiss** [comment]
I agree, I think it's a poor solution to something that is probably not a problem in the first place...

**Comment by dweiss** [comment]
Apache Infra has bumped the default for us to 60k. Let's see if these stack traces still show up. 
https://issues.apache.org/jira/browse/INFRA-25269

**Comment by dweiss** [comment]
Answering myself - yes, still a thing, https://ci-builds.apache.org/job/Lucene/job/Lucene-Check-main/10935/
```
Caused: java.lang.InterruptedException: hudson.FilePath$FileMaskNoMatchesFoundException: no matches found within 60000
```
It's a bit insane that so many files are there and need to be scanned through. Maybe this pattern can be tweaked to something more reasonable?

**Comment by uschindler** [comment]
I don't think the setting is live yet. You need to restart everything.

**Comment by dweiss** [comment]
The exception message would indicate it's live though, right? They bumped it to 60k.
https://github.com/apache/infrastructure-p6/pull/1747/files

**Comment by uschindler** [comment]
Yes. The file mask cannot be improved. It counts all files it sees. Look at the other code. Unless the path starts with a fixed path it needs to go through all files. It's like with Lucene wildcards. A star at begin introduces linear scan.

**Comment by dweiss** [comment]
Looks like this shouldn't be an issue anymore, yay.
https://issues.apache.org/jira/browse/INFRA-25269
