### ISSUE TITLE
Require bundled FSTs to be on the current FST version

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12911]
### Description

In Lucene 9.9 we bumped the FST version, but we did not re-generate our bundled FSTs such as the ones that are used by our Kuromoji analyzer. IMO we should systematically re-generate such dictionaries when bumping the FST version. Can we fail the build if the version of these dictionaries gets out-of-date?

Note: I don't think it is a bug (at least it should not cause bugs), it's more about making sure our dictionaries get any improvement we make to FSTs immediately.

**Comment by mikemccand** [comment]
Since we will respin shortly 9.9.1, should we do this specifically for 9.9.1 now?  And leave this issue open for failing the (some) build when the generated FSTs are stale?

Hmm is there a top-level `gradle` target to do this ...

**Comment by mikemccand** [comment]
> Hmm is there a top-level `gradle` target to do this ...

Yes, yes there is: `./gradlew regenerate`.

**Comment by mikemccand** [comment]
I'll open a PR shortly with the regenerated FSTs ... seems only `kuromoji` and `nori` build FSTs.

**Comment by mikemccand** [comment]
Hmm this is a bit of a spooky crab.  If I use OpenJDK 17 (`openjdk full version "17.0.9+8"`) to `./gradlew regenerate` on current `branch_9_9_0` I get this horrifying failure:

```
/s1/l/99x/gradle/generation/extract-jdk-apis/ExtractJdkApis.java:192: error: illegal character: '\ufffd'
    public void visitPermittedSubclass???(String c) {
                                      ^
```

The error does not happen with OpenJDK 21.

**Comment by dweiss** [comment]
./gradlew regenerate regenerates everything, everywhere. I think you can be more selective by passing -p (project path).

**Comment by dweiss** [comment]
https://github.com/apache/lucene/blob/main/help/regeneration.txt#L64-L76

**Comment by mikemccand** [comment]
Thanks @dweiss -- I regenerated everything, but only the two dicts were `git diff`, which I took to be a good sign (we haven't missed to regenerated any of the other many things).

But the scary `\UFFFD` error when using JDK 17 on 9.9.x was weird.  Maybe @uschindler has an idea?  Did we maybe generate very new Unicode characters into that method name that JDK 17 can't understand?

**Comment by uschindler** [comment]
> Hmm this is a bit of a spooky crab. If I use OpenJDK 17 (`openjdk full version "17.0.9+8"`) to `./gradlew regenerate` on current `branch_9_9_0` I get this horrifying failure:
> 
> ```
> /s1/l/99x/gradle/generation/extract-jdk-apis/ExtractJdkApis.java:192: error: illegal character: '\ufffd'
>     public void visitPermittedSubclass???(String c) {
>                                       ^
> ```
> 
> The error does not happen with OpenJDK 21.

This code is actually never ran on the Gradle JDK, so it can't be the cause.

Can you post in which exact task name this happened?

Uwe

**Comment by uschindler** [comment]
I checked that file, there's no such special characters? Or do I miss something. I only checked main branch....

**Comment by mikemccand** [comment]
> Can you post in which exact task name this happened?

Thanks @uschindler.  It happened when I ran `./gradlew regenerate` on 9.9.x branch with OpenJDK 17 (`openjdk full version "17.0.9+8"`) as the `java` on my exe path.  If others cannot repro it must be a PBKAC situation ;)

**Comment by uschindler** [comment]
I regenrated locally, no issues: 
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
```

All 3 tasks (Java 19, 20, 21) autogenerated its file and no changes deteected.

Full log:

```
>gradlew :lucene:core:regenerate
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :lucene:core:generateJdkApiJar19
Transforming 31 class files...
Writing 26 visible classes...
Writing stub for class: java/lang/foreign/AbstractLayout
Writing stub for class: java/lang/foreign/Addressable
Writing stub for class: java/lang/foreign/FunctionDescriptor
Writing stub for class: java/lang/foreign/GroupLayout
Writing stub for class: java/lang/foreign/Linker
Writing stub for class: java/lang/foreign/MemoryAddress
Writing stub for class: java/lang/foreign/MemoryLayout
Writing stub for class: java/lang/foreign/MemoryLayout$PathElement
Writing stub for class: java/lang/foreign/MemorySegment
Writing stub for class: java/lang/foreign/MemorySession
Writing stub for class: java/lang/foreign/SegmentAllocator
Writing stub for class: java/lang/foreign/SequenceLayout
Writing stub for class: java/lang/foreign/SymbolLookup
Writing stub for class: java/lang/foreign/VaList
Writing stub for class: java/lang/foreign/VaList$Builder
Writing stub for class: java/lang/foreign/ValueLayout
Writing stub for class: java/lang/foreign/ValueLayout$OfAddress
Writing stub for class: java/lang/foreign/ValueLayout$OfBoolean
Writing stub for class: java/lang/foreign/ValueLayout$OfByte
Writing stub for class: java/lang/foreign/ValueLayout$OfChar
Writing stub for class: java/lang/foreign/ValueLayout$OfDouble
Writing stub for class: java/lang/foreign/ValueLayout$OfFloat
Writing stub for class: java/lang/foreign/ValueLayout$OfInt
Writing stub for class: java/lang/foreign/ValueLayout$OfLong
Writing stub for class: java/lang/foreign/ValueLayout$OfShort
Writing stub for class: java/nio/channels/FileChannel
Referenced classes not included: [java/nio/channels/ScatteringByteChannel, java/nio/channels/GatheringByteChannel, java/nio/channels/SeekableByteChannel, java/nio/channels/spi/AbstractInterruptibleChannel, java/lang/AutoCloseable, java/lang/Object]

> Task :lucene:core:installMoman
Download https://github.com/jpbarrette/moman/archive/497c90e34e412b6494db6dabf0d95db8034bd325.zip

> Task :lucene:core:generateJdkApiJar20
Transforming 224 class files...
Writing 55 visible classes...
Writing stub for class: java/lang/foreign/Arena
Writing stub for class: java/lang/foreign/FunctionDescriptor
Writing stub for class: java/lang/foreign/GroupLayout
Writing stub for class: java/lang/foreign/Linker
Writing stub for class: java/lang/foreign/Linker$Option
Writing stub for class: java/lang/foreign/Linker$Option$CaptureCallState
Writing stub for class: java/lang/foreign/MemoryLayout
Writing stub for class: java/lang/foreign/MemoryLayout$PathElement
Writing stub for class: java/lang/foreign/MemorySegment
Writing stub for class: java/lang/foreign/PaddingLayout
Writing stub for class: java/lang/foreign/SegmentAllocator
Writing stub for class: java/lang/foreign/SegmentScope
Writing stub for class: java/lang/foreign/SequenceLayout
Writing stub for class: java/lang/foreign/StructLayout
Writing stub for class: java/lang/foreign/SymbolLookup
Writing stub for class: java/lang/foreign/UnionLayout
Writing stub for class: java/lang/foreign/VaList
Writing stub for class: java/lang/foreign/VaList$Builder
Writing stub for class: java/lang/foreign/ValueLayout
Writing stub for class: java/lang/foreign/ValueLayout$OfAddress
Writing stub for class: java/lang/foreign/ValueLayout$OfBoolean
Writing stub for class: java/lang/foreign/ValueLayout$OfByte
Writing stub for class: java/lang/foreign/ValueLayout$OfChar
Writing stub for class: java/lang/foreign/ValueLayout$OfDouble
Writing stub for class: java/lang/foreign/ValueLayout$OfFloat
Writing stub for class: java/lang/foreign/ValueLayout$OfInt
Writing stub for class: java/lang/foreign/ValueLayout$OfLong
Writing stub for class: java/lang/foreign/ValueLayout$OfShort
Writing stub for class: java/nio/channels/FileChannel
Writing stub for class: jdk/incubator/vector/AbstractVector
Writing stub for class: jdk/incubator/vector/ByteVector
Writing stub for class: jdk/incubator/vector/DoubleVector
Writing stub for class: jdk/incubator/vector/FloatVector
Writing stub for class: jdk/incubator/vector/IntVector
Writing stub for class: jdk/incubator/vector/LongVector
Writing stub for class: jdk/incubator/vector/ShortVector
Writing stub for class: jdk/incubator/vector/Vector
Writing stub for class: jdk/incubator/vector/VectorMask
Writing stub for class: jdk/incubator/vector/VectorOperators
Writing stub for class: jdk/incubator/vector/VectorOperators$Associative
Writing stub for class: jdk/incubator/vector/VectorOperators$Binary
Writing stub for class: jdk/incubator/vector/VectorOperators$Comparison
Writing stub for class: jdk/incubator/vector/VectorOperators$Conversion
Writing stub for class: jdk/incubator/vector/VectorOperators$Operator
Writing stub for class: jdk/incubator/vector/VectorOperators$Ternary
Writing stub for class: jdk/incubator/vector/VectorOperators$Test
Writing stub for class: jdk/incubator/vector/VectorOperators$Unary
Writing stub for class: jdk/incubator/vector/VectorShape
Writing stub for class: jdk/incubator/vector/VectorShuffle
Writing stub for class: jdk/incubator/vector/VectorSpecies
Writing stub for class: jdk/internal/vm/vector/VectorSupport
Writing stub for class: jdk/internal/vm/vector/VectorSupport$Vector
Writing stub for class: jdk/internal/vm/vector/VectorSupport$VectorMask
Writing stub for class: jdk/internal/vm/vector/VectorSupport$VectorPayload
Writing stub for class: jdk/internal/vm/vector/VectorSupport$VectorShuffle
Referenced classes not included: [java/nio/channels/SeekableByteChannel, java/lang/Object, java/nio/channels/ScatteringByteChannel, java/nio/channels/GatheringByteChannel, java/nio/channels/spi/AbstractInterruptibleChannel, java/lang/AutoCloseable, java/lang/Enum]

> Task :lucene:core:generateJdkApiJar21
Transforming 28 class files...
Writing 26 visible classes...
Writing stub for class: java/lang/foreign/AddressLayout
Writing stub for class: java/lang/foreign/Arena
Writing stub for class: java/lang/foreign/FunctionDescriptor
Writing stub for class: java/lang/foreign/GroupLayout
Writing stub for class: java/lang/foreign/Linker
Writing stub for class: java/lang/foreign/Linker$Option
Writing stub for class: java/lang/foreign/MemoryLayout
Writing stub for class: java/lang/foreign/MemoryLayout$PathElement
Writing stub for class: java/lang/foreign/MemorySegment
Writing stub for class: java/lang/foreign/MemorySegment$Scope
Writing stub for class: java/lang/foreign/PaddingLayout
Writing stub for class: java/lang/foreign/SegmentAllocator
Writing stub for class: java/lang/foreign/SequenceLayout
Writing stub for class: java/lang/foreign/StructLayout
Writing stub for class: java/lang/foreign/SymbolLookup
Writing stub for class: java/lang/foreign/UnionLayout
Writing stub for class: java/lang/foreign/ValueLayout
Writing stub for class: java/lang/foreign/ValueLayout$OfBoolean
Writing stub for class: java/lang/foreign/ValueLayout$OfByte
Writing stub for class: java/lang/foreign/ValueLayout$OfChar
Writing stub for class: java/lang/foreign/ValueLayout$OfDouble
Writing stub for class: java/lang/foreign/ValueLayout$OfFloat
Writing stub for class: java/lang/foreign/ValueLayout$OfInt
Writing stub for class: java/lang/foreign/ValueLayout$OfLong
Writing stub for class: java/lang/foreign/ValueLayout$OfShort
Writing stub for class: java/nio/channels/FileChannel
Referenced classes not included: [java/nio/channels/ScatteringByteChannel, java/nio/channels/GatheringByteChannel, java/nio/channels/SeekableByteChannel, java/nio/channels/spi/AbstractInterruptibleChannel, java/lang/AutoCloseable, java/lang/Object]

> Task :lucene:core:generateForUtil
Checksums consistent with sources, skipping task: :lucene:core:generateForUtilInternal

> Task :lucene:core:generateStandardTokenizer
Checksums consistent with sources, skipping task: :lucene:core:generateStandardTokenizerInternal

> Task :lucene:core:utilGenLev
Checksums consistent with sources, skipping task: :lucene:core:utilGenLevInternal

> Task :lucene:core:utilGenPacked
Checksums consistent with sources, skipping task: :lucene:core:utilGenPackedInternal

BUILD SUCCESSFUL in 33s
```

**Comment by mikemccand** [comment]
And you're right -- I don't see any special characters here: https://github.com/apache/lucene/blob/main/gradle/generation/extract-jdk-apis/ExtractJdkApis.java#L192

Not sure what I did wrong...

> I regenrated locally, no issues:

Hrmph, OK thanks for testing @uschindler -- I'll try to debug WTF is going on on my dev box...

**Comment by uschindler** [comment]
I can explain why you see a difference with Java 17 vs 21. Did the job fail on `:lucene:core:generateJdkApiJar21`. If yes the following happened:

All those three tasks are run with an automatically downloaded Java version (Gradle Autoinstall). So when you run with Java 17, it may download (and cache the downloads) for 19, 20, 21.

If you run the task with Gradle on Java 21, it will of course use the actual JVM and not execute a separately downloaded one to extract API signatures. So the difference for you is that With Java 21 it did not use the downloaded Java 21 version and instead your Gradle runtim VM.

**Comment by uschindler** [comment]
This is where it configures the language version: https://github.com/apache/lucene/blob/e0f4321b40fd06a556ff4a11f137a3fc0f67b5bb/gradle/generation/extract-jdk-apis.gradle#L46-L48

**Comment by mikemccand** [comment]
> may be a zero-width space character

on `main` and `branch_9_9`.

**Comment by mikemccand** [comment]
OK I gotta drop off ... will try to root cause this later today.

**Comment by uschindler** [comment]
> Hmm actually I think there may be a zero-width space character U+200B on this line before the opening (? https://github.com/apache/lucene/blob/branch_9_9/gradle/generation/extract-jdk-apis/ExtractJdkApis.java#L192

I created a hexdump with my editor for just the 2 characters (the one before bracket and the bracket), this produces this one; so you may be correct:

```
    public void visitPermittedSubclas73E2808B28String c) {
```

**Comment by uschindler** [comment]
Let me commit a fix for that file to all 3 branches. It really has a hidden character.

And there's a second problem: When invoking the JVM it does not pass a character set for the java source file. So it may fail in *some* configurations.

**Comment by uschindler** [comment]
OK, I fixed the file and also enforced UTF-8 when executing the JDK version. The general problem was: If I enforce locally another charset than UTF-8 (see the sysprops passed to the java version), it fails with a similar error message. It looks like depending on java version it may refuse wrong character depedning on compiler version.

The main issue here is that the generation java file is not tidied by code formatting (as it is treated as a script and never compiled).

```diff
 gradle/generation/extract-jdk-apis.gradle              | 3 ++-
 gradle/generation/extract-jdk-apis/ExtractJdkApis.java | 2 +-
 2 files changed, 3 insertions(+), 2 deletions(-)

diff --git a/gradle/generation/extract-jdk-apis.gradle b/gradle/generation/extract-jdk-apis.gradle
index 6a7b333aaa3..a24496db7fa 100644
--- a/gradle/generation/extract-jdk-apis.gradle
+++ b/gradle/generation/extract-jdk-apis.gradle
@@ -62,7 +62,8 @@ configure(project(":lucene:core")) {
       classpath = configurations.apiextractor
       mainClass = file("${resources}/ExtractJdkApis.java") as String
       systemProperties = [
-        'user.timezone': 'UTC'
+        'user.timezone': 'UTC',
+        'file.encoding': 'UTF-8',
       ]
       args = [
         jdkVersion,
diff --git a/gradle/generation/extract-jdk-apis/ExtractJdkApis.java b/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
index 7121374850b..58c7d2ec584 100644
--- a/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
+++ b/gradle/generation/extract-jdk-apis/ExtractJdkApis.java
@@ -189,7 +189,7 @@ public final class ExtractJdkApis {
     }
     
     @Override
-    public void visitPermittedSubclass​(String c) {
+    public void visitPermittedSubclass(String c) {
     }
 
   }
```

I will commit an push the change to 3 branches.

**Comment by uschindler** [comment]
Fixed in 10387f136ffa88ad9e86c526aa52908829a01ad3.

**Comment by uschindler** [comment]
Sorry for this.... My fault, looks like while copypasting Stackoverflow code I introduced the hidden character.....

**Comment by uschindler** [comment]
To come back to the original issue: There is no easy way to fail the build, because the FST files are heavy to generate and stay in the resources folder. It is hard to detect a problem if you don't regenerate them, which we won't do by default (as it needs to download external files).

At some point in the past we throught about a jenkins job that just calls "gradlew regenerate" and complains if the repo is not clean after that. Maybe we should investigate that again.

As our FSTs have a version number in the file older versions must be able to read it correctly. If tests pass we have an implicit test that our FST format is backwards compatible :-)

**Comment by jpountz** [comment]
> There is no easy way to fail the build, because the FST files are heavy to generate and stay in the resources folder. It is hard to detect a problem if you don't regenerate them, which we won't do by default (as it needs to download external files).

I wonder if we could do it in the code rather than in the build, e.g. by checking that `version == VERSION_CURRENT` on `FSTMetadata` for all FSTs that we load from a Lucene JAR?

**Comment by uschindler** [comment]
> > There is no easy way to fail the build, because the FST files are heavy to generate and stay in the resources folder. It is hard to detect a problem if you don't regenerate them, which we won't do by default (as it needs to download external files).
> 
> I wonder if we could do it in the code rather than in the build, e.g. by checking that `version == VERSION_CURRENT` on `FSTMetadata` for all FSTs that we load from a Lucene JAR?

That's not a bad idea. +1

**Comment by dweiss** [comment]
> Sorry for this.... My fault, looks like while copypasting Stackoverflow code I introduced the hidden character.....

Maybe apache rat check should actually scan for those, it's a known (pseudo?) security problem where the patches you receive are not what you think they are...

**Comment by mikemccand** [comment]
> So it may fail in _some_ configurations, e.g. when your default characterset is not fitting the encoding of that special character.

Argh!  I was worried about this.  I must have a crappy (non-UTF-8) default charset.  How is this even possible anymore ... let alone achieved by me by accident!

**Comment by mikemccand** [comment]
> > Sorry for this.... My fault, looks like while copypasting Stackoverflow code I introduced the hidden character.....
> 
> Maybe apache rat check should actually scan for those, it's a known (pseudo?) security problem where the patches you receive are not what you think they are...

+1, I'll open a spinoff issue for this.  It's crabs all the way down...

**Comment by uschindler** [comment]
> > Sorry for this.... My fault, looks like while copypasting Stackoverflow code I introduced the hidden character.....
> 
> Maybe apache rat check should actually scan for those, it's a known (pseudo?) security problem where the patches you receive are not what you think they are...

We have the source patterns check task for this. Just add another Regen with Unicode classes.

**Comment by mikemccand** [comment]
> I will commit an push the change to 3 branches.

Thanks @uschindler.

And thank you @rmuir for helping me fix my home dev box to put the default charset back to UTF-8.

**Comment by mikemccand** [comment]
> > There is no easy way to fail the build, because the FST files are heavy to generate and stay in the resources folder. It is hard to detect a problem if you don't regenerate them, which we won't do by default (as it needs to download external files).
> 
> I wonder if we could do it in the code rather than in the build, e.g. by checking that `version == VERSION_CURRENT` on `FSTMetadata` for all FSTs that we load from a Lucene JAR?

I'll try this approach.  I'm not sure how to do it at such a low level as "loading resources from Lucene jar that look like FSTs" ... I'll start just checking the two known binary FSTs we ship today (Nori, Kuromoji).

**Comment by uschindler** [comment]
> > > There is no easy way to fail the build, because the FST files are heavy to generate and stay in the resources folder. It is hard to detect a problem if you don't regenerate them, which we won't do by default (as it needs to download external files).
> > 
> > 
> > I wonder if we could do it in the code rather than in the build, e.g. by checking that `version == VERSION_CURRENT` on `FSTMetadata` for all FSTs that we load from a Lucene JAR?
> 
> I'll try this approach. I'm not sure how to do it at such a low level as "loading resources from Lucene jar that look like FSTs" ... I'll start just checking the two known binary FSTs we ship today (Nori, Kuromoji).

You can't add such special checks without adding a specific method to load from jar files. But this must be avoided, as it is caller sensitive regarding module system. So please do not add utility methods to load fsr from classpath as it could be module resources.

So just check after loading that version is the expected one.
