### ISSUE TITLE
[Minor] Regeneration investigation

### ISSUE THREAD

**Issue by slow-J** [apache/lucene#12923]
### Description

ForUtil generated from the gradle task is out of sync with spotless, forcing a run of ./gradlew tidy.
This is not a large issue, but the code should be consistent in my opinion.

Repro:

```
rm lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForUtil.java
./gradlew generateForUtilInternal
```
```
git diff
```
[ForUtil_git_diff.patch](https://github.com/apache/lucene/files/13647284/ForUtil_git_diff.patch)

```
./gradlew tidy && git status
```
```
nothing to commit, working tree clean
```

---

Also: ```./gradlew regenerate``` does not seem to work either..... meaning the `[ andThenTasks: ["spotlessJava", "spotlessJavaApply"] ` does not apply.

**Comment by slow-J** [comment]
An actual valid nuance related to regeneration:
running `./gradlew regenerate`
will modify 
```
	modified:   lucene/analysis/kuromoji/src/resources/org/apache/lucene/analysis/ja/dict/TokenInfoDictionary$fst.dat
	modified:   lucene/analysis/nori/src/resources/org/apache/lucene/analysis/ko/dict/TokenInfoDictionary$fst.dat
```

**Comment by dweiss** [comment]
I think it's because of changes in the fst code. So seems legitimate.

**Comment by slow-J** [comment]
> I think it's because of changes in the fst code. So seems legitimate.

Thanks @dweiss, does this mean that we should regenerate these 2 `TokenInfoDictionary`? 
Or does it simply mean that is being getting regenerated (needlessly) on my side due to the recent change?

**Comment by dweiss** [comment]
See https://github.com/apache/lucene/pull/12924 - I think it's something that fixes your problem. Also, take a look at:
https://github.com/apache/lucene/blob/main/help/regeneration.txt unless you have already - the internal tasks are not supposed to be called directly.

**Comment by slow-J** [comment]
> See #12924 - I think it's something that fixes your problem. Also, take a look at:
> https://github.com/apache/lucene/blob/main/help/regeneration.txt unless you have already - the internal tasks are not supposed to be called directly.

Ah the fix is already out, thanks for the link!
And yes I realised that I was doing something wrong called the internal task. Thanks for the help.
