### ISSUE TITLE
Should we clean up the few remaining references to `Lucene/Solr`?

### ISSUE THREAD

**Issue by slow-J** [apache/lucene#12934]
### Description

I was looking at a very old issue for a failing unit test with an ant test command. When I tried to run it in gradle (incorrectly), I was greeted with a message that stood out to me:
```
This is an experimental Lucene/Solr gradle build.
```

Searching the Lucene codebase ([github search](https://github.com/search?q=repo%3Aapache%2Flucene%20Lucene%2FSolr&type=code)), we find 18 usages of `Lucene/Solr`, all in comments/readmes/print messages in tools, most of these can be switched to just `Lucene`

Should we clean this up? If yes, I am happy to do it :)

**Comment by dweiss** [comment]
Please do, thank you!
