### ISSUE TITLE
Can we ban `Thread.sleep`?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12946]
### Description

Spinoff from #12912.

`Thread.sleep` should ideally never appear in our main and test sources.  Let's add it to forbidden APIs?

**Comment by msokolov** [comment]
I agree with the idea, but we do have a lot of these now. EG SleepingLockWrapper, although I see this in its javadocs "this is not a good idea" LOL

**Comment by msokolov** [comment]
+1 this does seem to be shaking out a lot of dust

**Comment by rmuir** [comment]
we can still ban it and just use `@SuppressWarnings` before SleepingLockWrapper or any other exceptional cases? It prevents any new sleeps from creeping in without someone thinking twice about it

**Comment by dweiss** [comment]
+1.

**Comment by shubhamvishu** [comment]
Opened a PR  #13001 to address this (I liked the PR id, first one in the 13k range :)). Thanks!
