### ISSUE TITLE
Test failure in TestKnnGraph.testMultiThreadedSearch

### ISSUE THREAD

**Issue by vsop-479** [apache/lucene#12940]
### Description

@msokolov Please take a look when you get a chance!

### Gradle command to reproduce

./gradlew test --tests TestKnnGraph.testMultiThreadedSearch -Dtests.seed=15C41D6B3378DF2B -Dtests.locale=qu-Latn-PE -Dtests.timezone=CST6CDT -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by msokolov** [comment]
Thanks @vsop-479, it reproduces for me as well, both on main and 9x branches. The same test passes on 9.8.0 release. I'll try `git bisect` ... and it blames this commit: 

[a47ba3369f402690ea9418b6f9c4c0cf367eab8d] Refactoring HNSW to use a new internal FlatVectorFormat (#12729)

**Comment by benwtrent** [comment]
https://github.com/apache/lucene/pull/12943

@msokolov LOL

**Comment by benwtrent** [comment]
We both figured it out at the same time.

**Comment by msokolov** [comment]
I can see that in this test run we are using a quantizing scorer, but I don't think the test case explicitly calls for that. I wonder if we beefed up the test framework to randomly use quantization and it is introducing "rounding" errors or something here?

**Comment by msokolov** [comment]
ah, thanks @benwtrent I'll check your fix then

**Comment by benwtrent** [comment]
> I can see that in this test run we are using a quantizing scorer, but I don't think the test case explicitly calls for that. I wonder if we beefed up the test framework to randomly use quantization and it is introducing "rounding" errors or something here?

Your instincts are correct :)
