### ISSUE TITLE
TestDocumentsWriterStallControl.assertState() does not do what it appears it would

### ISSUE THREAD

**Issue by sabi0** [apache/lucene#13061]
### Description

Both 'if' and 'else' branches here end with a `break;`
https://github.com/apache/lucene/blob/main/lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterStallControl.java#L178

So the `while (true)` loop is redundant as it will run just once.
And without it doubling the `millisToSleep *= 2;` as well as this check `if (millisToSleep < 60000)` are redundant too.

I am not sure though what's the proper way to fix this?
Maybe remove this `break;` at the end of the 'if' branch?
https://github.com/apache/lucene/blob/main/lucene/core/src/test/org/apache/lucene/index/TestDocumentsWriterStallControl.java#L190

CC @s1monw

**Comment by s1monw** [comment]
oh I wish I knew what I was thinking back then 12 years ago 🤣  I think that code tries to break out only of the for loop which needs a label I guess to go back to the while loop. Do you wanna take a stab at it and fix it. I think we need to make sure that the for loop runs through at one point and then step out of the outer while loop. Tricky... @mikemccand do you recall exactly what we tried to test back then

**Comment by sabi0** [comment]
I think the idea was to wait for the blocked threads for up to 2 minutes. And then fail the test if there are still blocked threads.
The progressive sleep time build-up is likely to avoid the test taking too long if the threads are unblocked quickly.

Currently however it just sleeps for 100 ms and then exits.

The fix is then to remove the `break` on line 190.

**Comment by s1monw** [comment]
I opened a pr for this.. thanks

**Comment by sabi0** [comment]
You were faster :-)
