### ISSUE TITLE
Expose the linedocsfile (enwiki) as a zstd compressed archive

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#13074]
### Description

@mikemccand could you recompress the enwiki file you're kindly providing using zstd? Here's what I did:
```
curl https://home.apache.org/~mikemccand/enwiki.random.lines.txt.bz2 -o - | bunzip2 | zstd -19 --threads=24 > enwiki.random.lines.txt.zst
```
this results in a file size of 727M, compared to 848M of the bz2 archive. But the main benefit is when you want to decompress the thing:
```
$ time zstdcat enwiki.random.lines.txt.zst | wc -c
3038178822

real    0m4.054s
user    0m4.437s
sys     0m2.686s
```
compared to (yes, it's not a typo):
```
$ time bzcat enwiki.random.lines.txt.bz2 | wc -c
3038178822

real    1m22.141s
user    1m21.562s
sys     0m2.218s
```

**Comment by mikemccand** [comment]
Wow, that is an amazingly fast decompression!  And also an awesome improvement in compression ratio.  Yup, I'll do this shortly.

**Comment by mikemccand** [comment]
OK, done!

https://home.apache.org/~mikemccand/enwiki.random.lines.txt.zst

I downloaded and confirmed the `wc -c` gives the same count as above.

Thanks @dweiss -- great idea.

**Comment by dweiss** [comment]
Thank you, Mike! I'll create a follow-up issue to change the gradle task to download and unpack the zstd-compressed file.
