### ISSUE TITLE
java.lang.AssertionError in backward compat tests ("failed to parse ... as date")

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#13073]
### Description

These failures do reproduce but you need the linedocsfile. I'll take a look.

**Comment by dweiss** [comment]
The embedded "linedocsfile" (europarl) has a different date field format compared to the "large" enwiki used on jenkins. 
```
(1)	2004-03-30	Istituzioni europee proteggerlo in tutti i campi.   [...]
```
```
APL (codepage)	11-JAN-2010 16:54:37.000	 languages.  From a user's standpoint
```

After #13046, TestIndexSortBackwardsCompatibility tries to parse the date and fails because it only recognizes "yyyy-MM-dd". 

I wonder what the best fix here should be - make the test recognize both date format or correct the test-resource-creation script and make dates there more consistent?

I think correcting the test will be simpler...

**Comment by dweiss** [comment]
@s1monw - some of those assertions added in #13046 only hold for the built-in europarl. I fixed date parsing but I'm not sure how to deal with the problem that the line resource can be different. Thoughts?

**Comment by dweiss** [comment]
There was actually just a single assertion that caused the problems. I've just remove it since it seems to be duplicated anyway with a term (body:the) that exists in both data sets. There is a marginal possibility of these tests failing in the future if the test resources change. Don't know if it's worth considering.

**Comment by s1monw** [comment]
> @s1monw - some of those assertions added in https://github.com/apache/lucene/pull/13046 only hold for the built-in europarl. I fixed date parsing but I'm not sure how to deal with the problem that the line resource can be different. Thoughts?

@dweiss These tests never ran with the nightly provided line docs. I think the fix is ok for this purpose since the we just now started to run tests against current version. We can add a check on top if the version we are testing is the current version and only then allow the leniency. WDYT?

**Comment by dweiss** [comment]
I'm not sure what you're referring to. :) Please feel free to tweak - I just wanted jenkins to quiet down because it started failing.
