### ISSUE TITLE
[Suggestion] Short circuit check for queued flushes in preUpdate() when checkPendingFlushOnUpdate is disabled

### ISSUE THREAD

**Issue by CaptainDredge** [apache/lucene#13079]
### Description

`numQueuedFlushes()` is a blocking function which gets called in `DocumentWriter#preUpdate()` to check if there are any queued flushes. If `checkPendingFlushOnUpdate` is disabled i.e. its false then the overall condition `flushControl.numQueuedFlushes() > 0 && config.checkPendingFlushOnUpdate` could be short circuited if we reverse the check to `config.checkPendingFlushOnUpdate && flushControl.numQueuedFlushes() > 0`. This will prevent a blocking call.
Code pointer: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java#L387

Currently while benchmarking I can see this particular issue significantly contributing to locking of write threads which is increasing indexing latency.

<img width="917" alt="Screenshot 2024-02-06 at 12 58 51 PM" src="https://github.com/apache/lucene/assets/20185657/05e6a52d-0811-443b-8637-43e47c67dc6c">

**Comment by CaptainDredge** [comment]
cc: @mgodwan, @backslasht

**Comment by uschindler** [comment]
Should we add changes entry?

**Comment by mikemccand** [comment]
> Should we add changes entry?

Ahh good catch @uschindler -- @CaptainDredge do you want to draft a quick PR with the CHANGES.txt entry?  Be sure to place it in the 9.11.0 section.  Thanks!

**Comment by CaptainDredge** [comment]
Thanks for merging @mikemccand I've raised the PR with `changes.txt` entry here
https://github.com/apache/lucene/pull/13118
