### ISSUE TITLE
Merge rate limiting should allow for some bursting?

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#13193]
### Description

(Spinoff from tricky discussions on https://github.com/apache/lucene/pull/13190).

Lucene's `ConcurrentMergeScheduler` allows users to set a `mbPerSec` rate limit on bytes written for each merge.  It's a complex feature to implement, and the [new intra-merge concurrency coming shortly](https://github.com/apache/lucene/pull/13190) makes it even  trickier (see above PR).  It is also best effort since separate threads writing bytes during merging "check in" only periodically after enough bytes have been written on their private thread.

However, there is one known bug that I would call a bug (and not a "best effort" limitation): it uses a naive instant measure of the IO rate, meaning it simply looks at the time of the last "check-in" from a writing thread, versus the current time and the current number of bytes written, and decides whether to pause.  This is somewhat brutal as IO writes can be bursty: merging things like postings might mean quite a bit of CPU effort in between writes, sometimes, and other times, not (e.g. merging a large postings list).  The instant approach we take today gives no credit for a longish period of time when no/few bytes were written.

It's sort of like telling a runner in a race that they get not credit from running slowly for a while, to get their wind back, and are not allowed to then sprint.

This means that if you were to sum up total bytes written by total time taken, the net `mbPerSec` is likely far below the specified limit.

A better model would be something like how AWS (and likely other cloud providers) handles IOPs limits on an EC2 instance using a "burst bucket" ("Burst IOPS is a feature of Amazon Web Services (AWS) EBS volume types that allows applications to store unused IOPS in a burst bucket and then drain them when needed" -- thank you Gemini for the summary).  It would have some state, allowing a burst after a period of not much IO, and would more closely throttle to the overall target rate, while allowing some bursting to catch up for a lull.

We could maybe run some benchmarks to see in practice whether Lucene's IO during merging is smooth enough that this lack of burstiness isn't really hurting things much ...

Alternatively, we could remove this complex and tricky-to-implement and best-effort-with-known-bugs feature of Lucene?  IO devices have only become more performant (many use cases store the Lucene index on SSDs now), machines have more RAM for the OS to cache writes and gradually spool them to disk, etc.  This feature is also likely to be mis-used, and make users think Lucene cannot keep up with merging ...

**Comment by jpountz** [comment]
> The instant approach we take today gives no credit for a longish period of time when no/few bytes were written.

My mental model is that the goal of merge throttling is to prevent merges from starving searches from IOPS. So the current approach makes sense from this perspective: if we gave merges credits that would allow them to max out IOPS from time to time, then this could temporarily starve searches from IOPS, which could be extremely disruptive to searches?

But then, I don't recall ever seeing indexing/merging max out I/O on a modern drive, so your second suggestion of removing I/O throttling makes sense to me, and I wouldn't mind removing all the complexity around I/O throttling. Presumably, we would still want to have some mechanisms to prevent merges from using all CPU for use-cases when indexing/merging and search are co-located on the same host?

**Comment by mikemccand** [comment]
> > The instant approach we take today gives no credit for a longish period of time when no/few bytes were written.
> 
> My mental model is that the goal of merge throttling is to prevent merges from starving searches from IOPS. So the current approach makes sense from this perspective: if we gave merges credits that would allow them to max out IOPS from time to time, then this could temporarily starve searches from IOPS, which could be extremely disruptive to searches?

Yeah that is a good point -- the instant IOPS throttle we use today might better protect concurrent searching, at the harm of slower merging.

Though, with the OS typically doing readahead (on the N files currently being read for merging), and write buffering, these OS level caching operations do "soak up" the time when the merge thread is not doing IO, and so the OS can get ahead of the merge CPU threads that are consuming / producing the bytes?  And so maybe in practice the OS is already "preparing" for the merge credits effectively and it wouldn't really hurt concurrent searching?  And, on a box doing concurrent searching, those bytes being read for merge may already be hot since those merging segments are lit for searching?  I dunno, it's complex ;)

> But then, I don't recall ever seeing indexing/merging max out I/O on a modern drive, so your second suggestion of removing I/O throttling makes sense to me, and I wouldn't mind removing all the complexity around I/O throttling. Presumably, we would still want to have some mechanisms to prevent merges from using all CPU for use-cases when indexing/merging and search are co-located on the same host?

I suspect merging is mostly CPU bound these days?  Except probably the "bulk copy merge" that we can sometimes do for merging stored fields?  And if that's the case, can't the application limit CPU consumption for merging by limiting number of merges / number of merge threads?

Hmm I forgot that CMS's "auto IO throttle" is enabled by default ... we could also explore disabling it by default (maybe for 10.0) and noting that in `MIGRATE.md`.
