### ISSUE TITLE
Find more classes in main branch that can be converted to record classes

### ISSUE THREAD

**Issue by uschindler** [apache/lucene#13207]
### Description

This is an overview issue about all classes in current Lucene's main branch to be ported over to `record` classes. Record classes are fine for immutable data structures which have no functionality and are not part of class hierarchy (they have no superclass).

Records offer several simplifications for implementing them:
- equals, hashCode and toString are autogenerated by an invokedynamic, so we can't forget to handle it correctly
- it is also immutable
- all parameter checking logic can be moved to some special constructor without any parameters (this is new syntax since Java 17)
- In later java versions they will have an optimized internal layout and arrays of record classes may no longer be pointer arrays (see Project Valhalla with a first preview of it in Java 22). In future they will also not have identity anymore (I don't understand the impact yet).

The first PR #13205 already added support for record classes in our Javadoc linter (`missing-doclet` plugin).

The following classes are candidates (please add more here and add link to PR):
- [x] `IOContext`, `MergeInfo`, `FlushInfo`: #13205
- [x] `BooleanClause` #13261
- [ ] `FieldInfo` ?
- [x] All the various`FieldEntry` classes used by codecs internally: #13296
- [ ] All the various `FieldMetaData`/`FSTMetadata`/`DirectMonotonicReader.Meta` classes used by codecs internally.
- [ ] More classes: #13328

**Comment by jpountz** [comment]
Lucene 10 is out, I'm closing.
