### ISSUE TITLE
MIGRATE.md doesn't mention the transition from Collector to CollectorManager

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#13218]
### Description

Spinoff from [this downstream issue](https://github.com/wardle/hermes/issues/63).

This API migration confused this user (understandably!), and I thought MIGRATE.md really should spell it out, but I looked quickly (at `main`/10.0 `lucene/MIGRATE.md`) and couldn't find any mention?

Let's fix this before 10.0.0 release!

**Comment by mikemccand** [comment]
Hmm is there some way to mark issues as blocker for release?  I want to make sure we address this for 10.0.0.

**Comment by jpountz** [comment]
FWIW I plan on treating all issues that have their milestone set to 10.0 as needing discussion if we want to exclude them from 10.0.

**Comment by mikemccand** [comment]
> FWIW I plan on treating all issues that have their milestone set to 10.0 as needing discussion if we want to exclude them from 10.0.

Awesome, thanks @jpountz.

**Comment by zacharymorn** [comment]
Thanks @mikemccand for catching this! I've opened a PR to add it https://github.com/apache/lucene/pull/13238

**Comment by Priyanshu-Madhup** [comment]
is this for 10.0.0

**Comment by mikemccand** [comment]
> is this for 10.0.0

This is for 10.0.0, yes, but is also helpful when upgrading to 9.x since these APIs are deprecated there (and removed in 10.0).

@zacharymorn -- I think we can close this now?  #13238 resolves this issue?

**Comment by javanna** [comment]
Addressed by #13238
