### ISSUE TITLE
Lucene index modeling - Why are skiplists used instead of B+ Tree?

### ISSUE THREAD

**Issue by IcanDoItL** [apache/lucene#13309]
### Description

Lucene index modeling - Why are skiplists used instead of B+ Tree?

**Comment by jpountz** [comment]
This is actually not Lucene-specific, skip lists are the traditional approach for skipping in search engines. You can check out IR literature such as https://nlp.stanford.edu/IR-book/html/htmledition/faster-postings-list-intersection-via-skip-pointers-1.html.
