### ISSUE TITLE
Test failure in TestBlockMaxConjunction.testRandom.

### ISSUE THREAD

**Issue by vsop-479** [apache/lucene#13396]
### Description

Test failure in `TestBlockMaxConjunction.testRandom`.

### Gradle command to reproduce

gradlew test --tests TestBlockMaxConjunction.testRandom -Dtests.seed=991AA33DE6046153 -Dtests.locale=fr-LU -Dtests.timezone=America/Porto_Velho -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by jpountz** [comment]
Thanks, I had started looking into #13371 but this one was easier to debug and I could figure out the problem. I'll open a PR shortly.
