### ISSUE TITLE
Add support for reloading the SPI for KnnVectorsFormat class

### ISSUE THREAD

**Issue by navneet1v** [apache/lucene#13393]
## Description
Lucene uses SPI to get the instance for various classes like Codec, KNNVectorsFormat etc. 

Currently Codec class provide a way to reload the SPIs by providing an interface which takes a ClassLoader and reload the SPIs. Ref: https://github.com/apache/lucene/blob/branch_9_10/lucene/core/src/java/org/apache/lucene/codecs/Codec.java#L126-L137

but similar functionality is not present in the KNNVectorsFormat.(I checked main branch and branch_9_10 too). Ref: https://github.com/apache/lucene/blob/branch_9_10/lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsFormat.java

I am not sure if this is a miss or there is some other way to reload the SPI of KNNVectorsFormat class.

## Solution
What I am looking for here is to add the support for reload SPI function in KNNVectorsFormat class too so that external libraries/application can load their own KNNVectorsFormat. 

I am willing to pick up this issue and contribute back.
 

@benwtrent please let me know your thoughts on this

**Comment by navneet1v** [comment]
I have raised a PR for the fix: https://github.com/apache/lucene/pull/13394

**Comment by benwtrent** [comment]
My only concern is why is this necessary?

Is feature parity the only reason?

**Comment by navneet1v** [comment]
> My only concern is why is this necessary?
> 
> Is feature parity the only reason?

Currently in my application I want to extend the KNNVectorsFormat just like Codec, to plug in a completely different implementation of Vector Search Algorithm(which not in Java).

As KNNVectorsFormat is part of Codec which allows applications on top of Lucene to extend the codec and their format. But due to lack of support of reloading of SPI in KNNVectorsFormat this not possible.

@benwtrent please let me know if you have further questions.

**Comment by benwtrent** [comment]
I still don't understand.

If the SPIs are there, it should work. If the SPI extension didn't work, none of the current formats would work either as they all rely on it.

Why doesn't your application work?

**Comment by navneet1v** [comment]
That correct if the classes are in the main application it will work.

but in my case during runtime I need to load some other jars(consider them as plugin) which has the KNNVectorFormat classes. And these classes as they are getting loaded at runtime the SPI is failing for VectorsFormat defined in these jars. Hence I am adding this functionality to reload spi with classpath.


This is the same thing present for Codec and DocValuesformat too as I have referenced in description.

**Comment by ChrisHegarty** [comment]
The dynamic addition of formats from other class loaders seems reasonable, though I don't have a use case for it myself.  Maybe I'm missing something but before adding a new API, is it not possible to implement the functionality through the existing `Codec` and reload ( possibly using `FilterCodec` ). And/or `PerFieldKnnVectorsFormat`.  OR is it a more straightforward way that is being suggested?

**Comment by ChrisHegarty** [comment]
Thanks for the explanation - sounds like a reasonable idea.

**Comment by navneet1v** [comment]
@benwtrent , @ChrisHegarty as we are not inclined that this is a valid usecase, can you guys please review the PR https://github.com/apache/lucene/pull/13394

**Comment by uschindler** [comment]
Thanks for bringing this up.

Unfortunately we have no way to automatically enforce this for our NamedSPI provides (as it is static methods), but we should keep all of them in sync.

At moment there's also missing the getter for list of names. I argued about this in the other PR already. The testframework uses expensive extra walk though ServiceLoader to do get those. This should be also brought in line with the other codec/analysis components. I will open a PR for this. The code in test-framework is inconsistent and a duplicates existing logic in a different way (the one that randomly chooses a KNN format).

**Comment by uschindler** [comment]
see #13428 

This also fixed the concern in other PR with SPI named similarity functions

**Comment by navneet1v** [comment]
> At moment there's also missing the getter for list of names.

@uschindler, when raising the PR I saw this and thought is it needed or not. To ensure the scope of the PR was minimal I didn't add the getter method. I see that you have raised the PR.
