### ISSUE TITLE
Remove Scorer#getWeight.

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#13410]
### Description

I've been working on some refactorings recently, and the fact that `Scorer` has a `getWeight` method is very annoying as it requires every simple `Scorer` implementation, e.g. for testing purposes, to also be able to return its `Weight`.

This method doesn't have strong use-cases, so I suggest that we remove it for 10.0.

**Comment by romseygeek** [comment]
+1

I'd also look at removing Scorable.getChildren() which we use in a few tests in tandem with getWeight().  We now have several composite scorer implementations that don't advance all subscorers for performance reasons, and we also have QueryVisitor and Matches APIs for getting information about sub-queries, so I don't think this API is very useful anymore.

**Comment by jpountz** [comment]
@navneet1v Since a `Scorer` must be created from a `Weight`, callers would be expected to keep track of the `Weight` that created the `Scorer` if they need it instead of relying on Lucene to do this.
