### ISSUE TITLE
How to speedup concurrent merge

### ISSUE THREAD

**Issue by hanqiushi** [apache/lucene#13432]
### Description

Hi, I have encountered a problem when using lucene in windows.
When I run IndexWriter.commit(), I may wait several minutes for doing background index merge.
The amount of data is about 20k+ items, not too much.
So what can I do to improve background index merging performance, aiming to reduce merge time?
Thanks for your advice.

**Comment by jpountz** [comment]
What version are you using? Lucene 9.11 introduced concurrent merging to help speed up merging, see #13124.

**Comment by msokolov** [comment]
When this is happening (you are waiting for merge) are you continuing to index new documents, or do you commit() and then during that time not submit any new docs (ie with IndexWriter.addDocuments or updateDocuments)?

**Comment by hanqiushi** [comment]
> When this is happening (you are waiting for merge) are you continuing to index new documents, or do you commit() and then during that time not submit any new docs (ie with IndexWriter.addDocuments or updateDocuments)?

Just wait for commit() to finish, not submit any new docs

**Comment by hanqiushi** [comment]
> What version are you using? Lucene 9.11 introduced concurrent merging to help speed up merging, see #13124.

Now I'm using 9.9.1 version, I'll check this 9.11 version, thanks

**Comment by msokolov** [comment]
I see you closed the issue, yet I'm still curious - did upgrading to 9.11 fix the problem you saw?
