### ISSUE TITLE
Remove the @Deprecated methods from TopScoreDocCollector and TopFieldCollector

### ISSUE THREAD

**Issue by slow-J** [apache/lucene#13499]
### Description

These methods were deprecated in https://github.com/apache/lucene/pull/240 which is part of Lucene 10.0.

Since they are not marked for deprecation in Lucene 9.x, they will not be removed with Lucene 10.0 release (unless we want to deprecate them in 9.x in another backport commit?), but I still think we should remove the internal usage so it will be quicker to remove the methods when the time comes.

I'll submit a PR for a 1:1 change to remove the usages.

**Comment by javanna** [comment]
Thanks for opening this issue, and the corresponding PR. I do think that we want to remove these methods in the main branch once we have no leftover usages. They have been already deprecated in the 9.x branch too.

**Comment by slow-J** [comment]
Sure, I can remove the methods too after we remove their use. Thanks, I didn't know that they were already deprecated in 9.x.

**Comment by parastooGit** [comment]
what is the replacement for create method?

**Comment by javanna** [comment]
@parastooGit you need to create collector managers instead of collectors. There is not static create method any longer, you need to create the collector managers using their constructor.

**Comment by parastooGit** [comment]
Hello,
Thank you for response,

I have some code that are not mine but deprected:

var collector = TopScoreDocCollector.create(1, Integer.MAX_VALUE);
indexSearcher.search(query, new PositiveScoresOnlyCollector(collector));
return collector.getTotalHits();

I changed it to :

var collectorManager = new TopScoreDocCollectorManager(1, (ScoreDoc)null, Integer.MAX_VALUE, false).newCollector();
indexSearcher.search(query, new PositiveScoresOnlyCollector(collectorManager));
return collectorManager.getTotalHits();

but still search is deprecated, I do not want to change the functionality, wondering how to relace search ?!

Regards,


________________________________

**Comment by javanna** [comment]
You need to call the other variant of search that takes the collector manager as an argument, rather than the one that takes a Collector.
