### ISSUE TITLE
Query matching difference in Lucene 2 and Lucene 4

### ISSUE THREAD

**Issue by roykyle8** [apache/lucene#13522]
### Description

I'm trying to upgrade my Lucene setup from 2 to 4(can't go to latest at this point) however I noticed that a simple query run with Lucene 2 & 4 gives different result.

**Lucene 2:**

```
        Analyzer queryAnalyzer = new FrenchAnalyzer();
        QueryParser queryParser = new MultiFieldQueryParser(new String[]{"name"}, queryAnalyzer);
        Query query = queryParser.parse("name:(\"+salle +manger\")");

        Directory directory = new RAMDirectory();
        IndexWriter writer = new IndexWriter(directory, queryAnalyzer, true, IndexWriter.MaxFieldLength.LIMITED);
        String value = "salle à manger";

        org.apache.lucene.document.Field f = new org.apache.lucene.document.Field("name", value, Field.Store.NO, Field.Index.ANALYZED_NO_NORMS);
        Document doc = new Document();
        doc.add(f);
        writer.addDocument(doc);
        writer.close();

        IndexReader reader = IndexReader.open(directory);
        IndexSearcher searcher = new IndexSearcher(reader);
        TopDocs results = searcher.search(query, 5);
        System.out.println("docs matched: " + results.totalHits);
```
**Prints:** `docs matched: 1`

**Lucene 4:**

```
        Analyzer queryAnalyzer = new FrenchAnalyzer();
        QueryParser queryParser = new MultiFieldQueryParser(new String[]{"name"}, queryAnalyzer);
        Query query = queryParser.parse("name:(\"+salle +manger\")");

        Directory directory = new RAMDirectory();
        IndexWriterConfig config = new IndexWriterConfig(Version.LUCENE_4_10_3, queryAnalyzer).setOpenMode(IndexWriterConfig.OpenMode.CREATE);
        IndexWriter writer = new IndexWriter(directory, config);
        String value = "salle à manger";

        Field f = new Field("name", value, Field.Store.NO, Field.Index.ANALYZED_NO_NORMS);
        Document doc = new Document();
        doc.add(f);
        writer.addDocument(doc);
        writer.close();

        IndexReader reader = IndexReader.open(directory);
        IndexSearcher searcher = new IndexSearcher(reader);
        TopDocs results = searcher.search(query, 5);
        System.out.println("docs matched: " + results.totalHits);
```
**Prints:** `docs matched: 0`

### Version and environment details

Lucene 2.4.1 & 4.10.4

**Comment by jpountz** [comment]
Your phrase query has `salle` immediately followed by `manger`, while your indexed document has `à` in-between, so the phrase doesn't match. You can get the original behavior back by setting `setEnablePositionIncrements(false)` on your `StopFilter`.

**Comment by roykyle8** [comment]
@jpountz setting `queryParser.setEnablePositionIncrements(false);` still does not work.

**Comment by jpountz** [comment]
Can you inspect the parsed queries to make sure that they are equivalent?

**Comment by krawlnet** [comment]
Parsed query shows: **name:"sale mang"**

<img width="542" alt="image" src="https://github.com/apache/lucene/assets/96465216/1dc4955d-67df-4df2-899e-d209552abea8">

**Comment by roykyle8** [comment]
@jpountz do you mean parsedQuery.toString()?

It shows `name:"sale mang"`

**Comment by jpountz** [comment]
Sorry, I got misleaded. The problem with the position increment is not on the query-parsing side, since you don't include `à` there anyway. It's on the indexing side, where FrenchAnalyzer now introduces a position gap between `salle` and `manger`.

**Comment by roykyle8** [comment]
Hi @jpountz alright. How do fix it then? I can't see any option to set `enablePositionIncrements` false on FrenchAnalyzer. I tried writing custom FrenchAnalyzer and setting `enablePositionIncrements` on the stop filter however it fails throwing following error. 
`throw new IllegalArgumentException("enablePositionIncrements=false is not supported anymore as of Lucene 4.4 as it can create broken token streams");`
