### ISSUE TITLE
Merge on Commit: No merges if new data is flushed (but not committed)

### ISSUE THREAD

**Issue by ameyakarve** [apache/lucene#13537]
https://github.com/apache/lucene/blob/f4cd4b46fc1ccb497624c5c5454785078aca6501/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L2361

Please see https://gist.github.com/ameyakarve/693a2a57f8836c9bce4e3eb59e85ec31 for a UT to reproduce:

I was working on something that uses the merge-on-commit feature. I noticed a place where the behavior was not per (my) expectation - if we try to perform a commit when the latest data is already flushed, then the merge never gets invoked.

This attached Gist reproduces the behavior. Commenting out `indexWriter.flush();` fixes the test.
I will be happy to dive into the behavior and fix if needed

**Comment by jpountz** [comment]
What version are you using? We fixed a similar problem in version 9.9, I wonder if the problem that you are reporting is the same one or a new one: https://github.com/apache/lucene/pull/12549.

**Comment by ameyakarve** [comment]
I think we're running on 9.4

Let me quickly try with the latest and reconfirm

**Comment by ameyakarve** [comment]
Yeah this works on 9.9

Thanks for pointing it out. I'll close this issue
