### ISSUE TITLE
Are we properly accounting for `NeighborArray.rwlock`?

### ISSUE THREAD

**Issue by msokolov** [apache/lucene#13580]
### Description

Really three issues:
1. `OnHeapHnswGraph.ramBytesUsed` has a complicated job - it's hard to tell whether it takes into account the probably quite significant RAM usage of the `ReentrantReadWriteLock` that gets created for every node in the graph.
2. We create these locks even in the case where we are flushing (via `HnswGraphBuilder`) and don't ever use them. We only need locks available when merging
3. We could hash the node ids and share a smaller pool of locks among them and thus save a bunch of allocations

**Comment by msokolov** [comment]
I also found we are acquiring these locks for writing in `HnswGraphBuilder.addDiverseNeighbors` even in the single-threaded case where it is not needed.

**Comment by benwtrent** [comment]
@msokolov related: https://github.com/apache/lucene/issues/12732

**Comment by msokolov** [comment]
ooh thanks @benwtrent I had forgotten about that. I'm working up a new version based on (3) above that I hope will reduce this usage and only require it for concurrent mergers.
