### ISSUE TITLE
TestHnswFloatVectorGraph.testReadWrite fails on branch 9x

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#13653]
### Description

TestHnswFloatVectorGraph.testReadWrite fails due to a mismatched number of connections. 

`java.lang.AssertionError: arcs differ for node 3 expected:<[2, 52, 6]> but was:<[2, 52, 6, 13]>`

This is caused by commit: https://github.com/apache/lucene/pull/13648

I have confirmed that this failure is not occurring on main, only on 9x.

### Gradle command to reproduce

```
./gradlew test --tests TestHnswFloatVectorGraph.testReadWrite -Dtests.seed=118030F93FB3695D -Dtests.locale=eu -Dtests.timezone=Indian/Cocos -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

**Comment by msokolov** [comment]
I'm suspecting this may have something to do with the connectComponents changes - I'll dig

**Comment by msokolov** [comment]
OK I'll mark this fixed now since we seem to have gone ~24h without any more failures from automated builds that I can see
