### ISSUE TITLE
Operations#sameLanguage has true negatives?

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#13709]
### Description

The following test fails, even though both automata accept the same language and are determinized. Looking at the implementation, it looks like it may assume that both automata are not only determinized but also minimal?

```java
  public void testSameLanguage() {
    // automaton that accepts [ab]* with 2 states
    Automaton a = new Automaton();
    int state0 = a.createState();
    int state1 = a.createState();
    a.setAccept(state0, true);
    a.setAccept(state1, true);
    a.addTransition(state0, state1, 'a');
    a.addTransition(state1, state0, 'b');

    // automaton that accepts [ab]* with a single state
    Automaton b = new Automaton();
    state0 = b.createState();
    b.setAccept(state0, true);
    b.addTransition(state0, state0, 'a');
    b.addTransition(state0, state0, 'b');
    
    assertTrue(Operations.sameLanguage(a, b));
  }
```

Here are what these two automata look like:
a
![automaton](https://github.com/user-attachments/assets/a150ae74-7393-4516-90da-355c9cc8a472)
b
![automaton2](https://github.com/user-attachments/assets/159d018a-052d-435f-bcef-96650272c714)

**Comment by rmuir** [comment]
doesn't look like they accept the same language to me.
for example the automaton "b" accepts string `aa` but not automaton "a".

**Comment by jpountz** [comment]
Lol, this is embarrassing. Sorry for the noise.

**Comment by rmuir** [comment]
no worries, somewhat related to this, you may indeed find bugs if you have assertions disabled due to the smelliness of sameLanguage, please see https://github.com/apache/lucene/pull/13708
