### ISSUE TITLE
Significant performance regression with search after

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13856]
When verifying the Lucene 10.0.0 release candidate builds we observe a significant (10x) performance regression with _search after_, when querying on a mostly (but not all) sorted data. We've narrowed down the change to #13221, and observe very "heavy" behaviour on some datasets.

The luceneutil benchmarks don't show the issue that we see in the Elasticsearch benchmarks, as it seems that there is no coverage for _search after_. Also, the issue we see is very dependent on the actual dataset, and the target competitive range based on the _after_ value. 

For reference, the query is similar to:
```
TopFieldCollectorManager manager =
  new TopFieldCollectorManager(
    new Sort(new SortedNumericSortField("geoid", SortField.Type.LONG)),
    10,
    new FieldDoc(Integer.MAX_VALUE, 0.0f, new Long[] {searchAfter}),
    10);
TopDocs topDocs = searcher.search(new MatchAllDocsQuery(), manager);
```
.. with several million docs, mostly indexed with the `geoid` sorted. This kind of mostly-but-not-all sortedness we see in a number of datasets, e.g. the `timestamp` field in http_logs [1], the `geoid` in Genomes [2]. And not all that uncommon. I'll include some graphs to help visualise the impact:

![Screenshot from 2024-10-04 12-25-54](https://github.com/user-attachments/assets/5bc8fd91-55e1-4f9f-a3b9-586f7a9d9382)
![Screenshot from 2024-10-04 12-26-27](https://github.com/user-attachments/assets/f9d4bcfe-ccdf-4539-a3a9-a726f787e104)
![Screenshot from 2024-10-04 12-27-19](https://github.com/user-attachments/assets/10a460bb-d245-4097-be80-e04faf0c244e)

Ultimately, given where we are in the Lucene 10 release cycle, and the complexity of this area of code, the most responsible approach I can think of is to revert the changes in 13221, allow the Lucene 10 RC process to continue without it. While continuing to work on a fix the underlying issue, with a view to resolving it in 10.x. The changes are implementation only, so can be applied in a minor release.

@original-brownbear @iverase have more details on the specifics and working towards a fix. 

relates #13221

[1] https://elasticsearch-benchmarks.elastic.co/#tracks/http-logs/nightly/default/90d
[2] https://elasticsearch-benchmarks.elastic.co/#tracks/geonames/nightly/default/90d

**Comment by javanna** [comment]
The revert targeted branch_10_0 specifically, in the effort of unblocking the Lucene 10 release. I believe that the lucene nightly benchmarks target main only, in which case I wonder if we should consider reverting in main (and branch_10x) as well. I am not too sure what the best approach is, opinions are welcome.

**Comment by javanna** [comment]
cc @gf2121 as you made some changes to this area. We reverted #13221 in `branch_10_0` , and we are debating what to do in `main` and `branch_10x` . It would also make sense to forward port #13498 to `branch_10_0` and to any branch that sees #13221 reverted.

**Comment by mikemccand** [comment]
> The luceneutil benchmarks don't show the issue that we see in the Elasticsearch benchmarks, as it seems that there is no coverage for _search after_. Also, the issue we see is very dependent on the actual dataset, and the target competitive range based on the _after_ value.

Hrpmh that is an annoying gap ... I'll open a luceneutil issue to add coverage for `searchAfter` so we don't lose track.

**Comment by javanna** [comment]
There has been little activity on this issue, I am leaning towards applying the revert of the change that caused the regression to branch_10x and main as well. I am anxious that we will forget and end up in the same situation as we were with the Lucene 10.0 release.

**Comment by javanna** [comment]
I opened https://github.com/apache/lucene/pull/13971
