### ISSUE TITLE
Added capability to auto force merge as much as possible to reduce the number of segments

### ISSUE THREAD

**Issue by kkewwei** [apache/lucene#13925]
### Description

In our product, for small index (about 20g-), the frequency of writing/updating is not high, we have to frequently execute forceMerge segment to reduce the segments, to improve query performance. As `lucene` support `TieredMergePolicy`, which just merges segments of approximately equal size.

If we can support another MergePolicy, which can auto merge as much as possible to reduce the number of segments.

**Comment by msokolov** [comment]
Have you tried writing a custom merge policy? This is a supported API and designed for users to customize/extend
