### ISSUE TITLE
Should we avoid allocating a byte[] upfront for binary doc values

### ISSUE THREAD

**Issue by iverase** [apache/lucene#13929]
When generating binary doc values in Lucene90DocValuesProducer we are allocating a byte array upfront. The length of the array is set to the length of the biggest doc value in the segment. 

This can be an issue if you add one document with a big binary doc value in your index, then in high throughput scenarios, the index can become unusable because allocating that array whenever reading the binary doc values for that segment creates lot of churn in the GC due to humongous allocations.

I wonder if we should avoid allocating that array upfront and instead using something like BytesRefBuilder, even though this can slow down reading binary doc values. This can be the first step to move to a more streaming API like proposed here: https://github.com/apache/lucene/issues/12459

**Comment by rmuir** [comment]
I don't think we should optimize for abusive cases that are storing entire novels in this structure. We should be optimized for real use-cases that use a couple bytes.
