### ISSUE TITLE
Absolutely horrible Lucene performance with JDK 23 (Lucene 9.11.1 and 10.0.0)

### ISSUE THREAD

**Issue by derreisende77** [apache/lucene#13959]
### Description

I am using Lucene in my app for several years happily with JDKs up to 22.
My use case searches through film data and Lucene can return fairly huge result sets to my app - which as of now never was a problem. 
I upgraded my app to JDK 23.0.1 on my MacBook Air macOS 15.01 16GB RAM.

```
openjdk version "23.0.1" 2024-10-15
OpenJDK Runtime Environment (build 23.0.1+13)
OpenJDK 64-Bit Server VM (build 23.0.1+13, mixed mode, sharing)
```

and started to notice **horrible** Lucene performance.
With the following code snippet I do query my results:

```java
var reader = DirectoryReader.open(list.getLuceneDirectory());
final var searcher = new IndexSearcher(reader);
final var docs = searcher.search(finalQuery, list.size());
final var hit_length = docs.scoreDocs.length;

var storedFields = searcher.storedFields();
// the for loop takes ages with JDK23...
for (final var hit : docs.scoreDocs) {
	var docId = hit.doc;
	//storedFields.prefetch(docId); //<-- doesn't change anything
	var d = storedFields.document(docId, INTEREST_SET); //<-- this takes ages
	//filmNrSet.add(Integer.parseInt(d.get(LuceneIndexKeys.ID)));
}
```

In the explored use case Lucene always returned the expected 558333 hits out of 802k documents.
99% of the app runs take **5.7 seconds** to get the result. However when I am lucky *1% of the app runs* do get the same result back in **756 milliseconds**.
If Lucene is delivering fast, it will stay fast, if it is slow it will remain slow. I have no idea how this is triggered.

I moved from `NRTCachingDirectory` to `MMapDirectory` but the performance remained bad. Tried some other stuff from internet - same result.

I switched back to JDK 22.

```
openjdk version "22.0.2" 2024-07-16
OpenJDK Runtime Environment (build 22.0.2+11)
OpenJDK 64-Bit Server VM (build 22.0.2+11, mixed mode, sharing)
```

The same source which performed just horrible with JDK23 was **consistently fast** with JDK 22:

```
Search took: 763.8 ms
```

I am using the following flags for the JVM:
```
-ea
-XX:+UseShenandoahGC
-XX:ShenandoahGCHeuristics=compact
-XX:+UseStringDeduplication
-XX:MaxRAMPercentage=50.0
--enable-native-access=ALL-UNNAMED
--add-modules jdk.incubator.vector
```

I removed `--enable-native-access=ALL-UNNAMED` and `--add-modules jdk.incubator.vector` for testing purposes but the performance remained bad with JDK23.

I made the same tests with JDK23 on my Windows 11 AMD Ryzen 4900H 16GB RAM laptop. There I get the results back in **13.63 seconds** with JDK 23. JDK 22 does the same consistently in **2.1 seconds**.

Switching between Lucene `9.11.1` and `10.0.0` made no difference, always shitty performance with JDK 23 both on macOS and windows. Consistent performance with JDK 22.

### Version and environment details

macOS 15.01
MacBook Air 16GB RAM

Windows 11 23H2 / Ubuntu Linux 24.10
AMD Ryzen 4900H 16GB RAM

Lucene 9.11.1
Lucene 10.0.0

JDK 23.0.1
JDK 22.0.2

**Comment by derreisende77** [comment]
I made some tests with Ubuntu 24.10:
JDK 23: 9.9 seconds
JDK 22: 1.4 seconds

**Comment by benwtrent** [comment]
@derreisende77 do you have profiling of the two different runs? Maybe through async-profiler? It would be interesting to see where the time is being spent.

**Comment by derreisende77** [comment]
@benwtrent I have JProfiler but I am not really experienced in using it - or profiling at all.
I made two runs on macOS and made screenshots from the hotspot page.

JDK23:
![jdk23](https://github.com/user-attachments/assets/d2753b47-1f68-49c8-9455-daf761956d96)

JDK22:
![jdk22](https://github.com/user-attachments/assets/6292f639-9550-4e46-8e05-c13ac688f21f)

The highlighted line in JDK22 image marks the function from where I posted the code snippet at the beginning. 
The `StoredFields.document` ine above corresponds to the `var d = storedFields.document(docId, INTEREST_SET);` line.

What I have seen during the profile run:
- `ArrayUtil.growExact` takes a lot more time on JDK23 than on JDK 22.
- `UnicodeUtil.UTF16toUTF8` calls were created during the index creation phase and take almost the same time on JDK 22 and 23.

HTH

**Comment by derreisende77** [comment]
@benwtrent I made several tests on macOS with JDK 23 and 23.0.1 from Liberica and Azul. I always ran into the performance problem.
I switched from Shenandoah GC to ZGC with
```
-XX:+UseZGC
-XX:+ZGenerational
-XX:ZUncommitDelay=5
-XX:+ZUncommit
-XX:SoftMaxHeapSize=4g
```
and so far was unable to trigger the performance problem. Lucene behaves as performant as before with JDK 23

**Comment by jpountz** [comment]
Is there also no regression if you use the default garbage collector? If so, this looks like a regression with Shenandoah.

**Comment by derreisende77** [comment]
I have no problem with default GC as well.
I downloaded a Windows Amazon Corretto 23 nightly build from today and I don't have a problem with Shenandoah anymore. So I guess it is a Shenandoah problem in JDK 23 and 23.0.1 that will be fixed in a later 23 release.
