### ISSUE TITLE
KnnFloatVectorQuery#toString should show the filter

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#13983]
I was looking at the `toString()` of a `KnnFloatVectorQuery` and got surprised that it was not pre-filtered, when I later discovered that it actually was, `toString()` was just omitting to display the pre-filter.

**Comment by viswanathk** [comment]
Seems like a good first issue -  I can contribute this @jpountz.

**Comment by benwtrent** [comment]
This is now fixed: https://github.com/apache/lucene/pull/13990
