### ISSUE TITLE
Strange javac "automatic module" warning for `benchmark-jmh`

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#13992]
### Description

I suddenly noticed this warning when running top-level `./gradlew jar` in Lucene `main`:

```
/s1/l/trunk/lucene/benchmark-jmh/src/java/module-info.java:20: warning: requires directive for an automatic module
  requires jmh.core;
              ^
1 warning
```

I think it is related to java modules but I'm not sure how to fix/suppress it :)

**Comment by viswanathk** [comment]
@mikemccand gave it a shot at #13997
