### ISSUE TITLE
Taxonomy counts are incorrect due to ordinal sorting

### ISSUE THREAD

**Issue by paulk-asert** [apache/lucene#14008]
### Description

The following line implicitly sorts in `ordinal` array (for efficiency reasons I presume):
https://github.com/apache/lucene/blob/main/lucene/facet/src/java/org/apache/lucene/facet/taxonomy/TaxonomyFacets.java#L326

But the following line is needing the original ordinal values:
https://github.com/apache/lucene/blob/main/lucene/facet/src/java/org/apache/lucene/facet/taxonomy/TaxonomyFacets.java#L333

This is giving me incorrect count values in the `labelValues` returned when I call `TaxonomyFacetIntAssociations#getTopChildren`

### Version and environment details

I am using JDK21, Lucene 10.0.0.

**Comment by stefanvodita** [comment]
Thank you for finding this bug @paulk-asert! We're using our API incorrectly by referencing `ordinals` after `getBulkPath`.

**Comment by stefanvodita** [comment]
Checking and it looks like I introduced that bug together with the `createFacetResult` method in #12966, which I also backported to 9x in #13358. Sorry about this.
