### ISSUE TITLE
IndexInput.isLoaded seems to return false for mmap index inputs on Windows

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#14050]
### Description

There is a check added to BaseDirectoryTest case in #13998 which has been failing since that PR was merged (nearly all Windows builds failing on jenkins):
```
        var loaded = in.isLoaded();
        if (FilterDirectory.unwrap(dir) instanceof MMapDirectory
            // direct IO wraps MMap but does not support isLoaded
            && !(dir.getClass().getName().contains("DirectIO"))) {
          assertTrue(loaded.isPresent());
          assertTrue(loaded.get());
        } else {
          assertFalse(loaded.isPresent());
        }
```

The isLoaded optional has a value of false, even though it is a mmap directory. Seems like isLoaded in MemorySegment always returns false on Windows?

**Comment by dweiss** [comment]
Here is an example build failure:
https://jenkins.thetaphi.de/job/Lucene-main-Windows/14859/

These only happen on Uwe's machine but can be reproduced on any Windows machine.

**Comment by dweiss** [comment]
Right. Seems like it's always false on Windows.

https://github.com/openjdk/jdk21/blob/890adb6410dab4606a4f26a942aed02fb2f55387/src/java.base/windows/native/libnio/MappedMemoryUtils.c#L34-L44

**Comment by dweiss** [comment]
While the test can be fixed easily (bypass the check on Windows), I wonder if it's a good fix. In essence, this method lies on Windows... What are the side-effects of this always returning false?

**Comment by rmuir** [comment]
The method returns `Optional` which means its not a boolean but a quadrillean or something instead, on windows we could return empty-optional or even null to say "don't know" ?

**Comment by dweiss** [comment]
Yep, I think I understand the reason it returns Optional - a missing value would indicate "don't know", so it's a tri-state knob: yes, no, don't know. The problem is that on Windows it returns "no" and that logic in BaseDirectoryTest assumes that if it's a mmapdir, it should always be a hard "true".

**Comment by rmuir** [comment]
yeah, i'm suggesting adding this to the code:
```
if (Constants.WINDOWS) {
  return DONT_KNOW;
}
```

**Comment by dweiss** [comment]
This was my initial guess too. But if we hardcode it and then they fix the JDK with some magic Windows API that returns the right value? Should we try to detect if isLoaded returns true  on Windows and return the detected value?

**Comment by rmuir** [comment]
It seems the commented-out code with hardcoded `false` is also in the JDK master? I think we should at least report the bug since it is impacting us.

I am not sure it needs a magic windows API, just looks like maybe the wrong one (VirtualQuery) was attempted instead of e.g. `QueryWorkingSetEx`

**Comment by rmuir** [comment]
the `git blame` for the commented-out code shows it is at least 17 years old. The `QueryWorkingSetEx` was not even around at that time.

**Comment by rmuir** [comment]
At least not everywhere: `Minimum supported server: Windows Server 2008`. So maybe this one can be revisited in 2024 and fixed...

**Comment by dweiss** [comment]
I've peeked at the flags returned by QueryWorkingSetEx - just wondering if it'd be possible to query it directly using ffi. :) But I can't tell which of these flags would correspond to the loaded/ swapped out state. Fun.

https://learn.microsoft.com/en-us/windows/win32/api/psapi/ns-psapi-psapi_working_set_ex_block

But I agree - reporting back to JDK is probably a saner idea, I'm sure they have better win32 api experts there.

**Comment by rmuir** [comment]
I think it won't return flags at all in that case.

**Comment by dweiss** [comment]
I don't have access to openjdk's Jira, maybe @ChrisHegarty or Uwe (or you?) can file an issue there?

**Comment by ChrisHegarty** [comment]
Oops! Sorry, clearly I added this test and didn't noticed it fail on Windows.  For Lucene, I'm perfectly fine with returning "don't know" for all Windows.   Lemme look into why this is not working in the JDK.

**Comment by dweiss** [comment]
Thanks, Chris. The only Windows tests running at the moment are on Uwe's vbox. Github's Windows testing is so slow as to be almost unusable. The results from Uwe's box are sent to this list -
https://lists.apache.org/list.html?builds@lucene.apache.org

**Comment by uschindler** [comment]
Hi,
I would do it like the following on Windows:
- if windows returns `true`, `return Optional.of(Boolean.TRUE)`
- if windows returns `false`, `return Optional.empty()`
- once the bug is fixed in some future JDK feature version, add a `version.feature()>=...` check to return the unfiltered variable.

Not sure if the test needs to be adapted.
Uwe
