### ISSUE TITLE
Is there any API which two segments can be manually merged? 

### ISSUE THREAD

**Issue by junneyang** [apache/lucene#14055]
### Description

1、now the documentation says that it can be automatically merged by policy (eg: tiered)
2、if i need to merge two segments manually, is this supported?
looking forward to your reply, thanks ~

**Comment by mkhludnev** [comment]
Hi, 
Github issues is not a way to ask nor discuss such questions. Please join java-user mailing list see https://lucene.apache.org/core/discussion.html#Java%20User%20List
With regards to the question, I couldn't find the proper API for this. The probable hack is:
- inject pair of segements into the custom merge policy
- call `IndexWriter.maybeMerge()` 
- custom merge policy yields the desired pair of segments via `MergePolicy#findMerges()` and forget them.  

NB: It requires thorough implementation, I never done anything like this.
