### ISSUE TITLE
Threads leaking from ForkJoinPool.commonPool (randomization in RandomCodec)

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#14066]
### Description

#14049 added randomization of codec params but as part of that it may spin up new threads when ForkJoinPool.commonPool is started. We have no control over these threads but they do cause test failures as in here:

![image](https://github.com/user-attachments/assets/9729047e-3dd0-4813-9513-fe5560309c01)

I think we can safely assume common pool's threads surviving the test's scope are not interesting for us to detect and any leftover threads/ runnables will just eventually complete and die (?). I feel tempted to ignore those threads by adding them to QuickPatchThreadsFilter. If we want to ensure nothing survives the test's scope, we could add a rule to LuceneTestCase that would wait (after the suite completes) until the active count of workers in the common pool is zero.

**Comment by dweiss** [comment]
Hmm... Interesting that I can't reproduce this locally. Also, ForkJoinWorkerThread should be demon threads, which are ignored by the default set of filters... Headscratch.

**Comment by dweiss** [comment]
This only happens with coverage tests. There is a difference in how these are started - they run without the security manager. Turns out ForkJoinPool's default factory has different settings for running with and without the security manager, resulting in system threads being either part of the test group or not. This is the direct reason why these tests pass in normal runs (most of those use the security manager) and fail with coverage runs (no security manager).

**Comment by rmuir** [comment]
thanks for debugging this: good find, since security manager won't be around forever...

**Comment by dweiss** [comment]
Thanks. If I read David Delabassee's e-mail correctly, JDK 24 effectively removes it internally.

I've committed a quick patch to QuickPatchThreadsFilter to ignore those daemon threads. Sorry I didn't push it as a PR for review - seemed like a trivial change with no clear alternatives. If you'd like to run through the full cycle, I can revert and push a PR.

**Comment by rmuir** [comment]
no need for a hassle, thanks for fixing it. I will take care of the tidy.

**Comment by dweiss** [comment]
Damn. I'll do it, no problem. Sorry for the noise.

**Comment by dweiss** [comment]
Oh, you're fast. Thank you.

**Comment by msokolov** [comment]
Thank you all for jumping on this! It didn't fail for me in many iterations, beasting, etc. I guess the multithreaded merging of HNSW graphs was never tested before :(

**Comment by dweiss** [comment]
It fails right away if you run without the security manager, @msokolov This option is not randomized on gradle runs - perhaps it should be (?).

**Comment by msokolov** [comment]
I see, that explains why i didn't see it. I don't have a strong opinion about SM, although I think others may, but given it has been deprecated for a while and is disabled in the latest JVM, perhaps it's finally time to drop support for it from Lucene? At least it would reduce the complexity of test options a bit.

**Comment by dweiss** [comment]
Don't feel bad about it. Those randomization failures are exactly what this was designed for - something nobody could expect. Who'd know worker threads are created in a different way based on the presence of security manager. It's fun debugging. :)
