### ISSUE TITLE
Nightly build failed (missing unsupported index for 9.12.1)

### ISSUE THREAD

**Issue by dweiss** [apache/lucene#14068]
### Description

A bunch of tests failed last night in:
https://ci-builds.apache.org/job/Lucene/job/Lucene-NightlyTests-main/1514/

![image](https://github.com/user-attachments/assets/4fe52cd3-63fe-468e-ad23-c6454cdd9b7a)

Is the process of how these indexes should be added documented somewhere? All I found in releaseWizard.yaml is this note, which is hilarious. ;)

![image](https://github.com/user-attachments/assets/d1e60a44-2564-4f4d-9a7a-5af982f433bb)

**Comment by ChrisHegarty** [comment]
I did merge the 9.12.1 bwc indices, but maybe I missed something! Argh!!!

**Comment by ChrisHegarty** [comment]
Hmm.. I didn't add 9.x bwc tests to _main_, since there is no compat from main/11 with 9. Maybe these go elsewhere ?

**Comment by dweiss** [comment]
To be honest, I'm not sure myself how these are supposed to work.

**Comment by ChrisHegarty** [comment]
@dweiss Thanks for forward porting the 9.12.1 backward compat indices. Trivially the file names need to be prefixed by _unsupported_, since the now in the _main_ (Lucene 11) branch. See https://github.com/apache/lucene/commit/0494c824e0ac8049b757582f60d085932a890800

**Comment by dweiss** [comment]
Thank you, @ChrisHegarty . I admit this isn't something I'm familiar with (those bwc tests), I noticed the tests failing because I'm subscribed to those nightly smoketester checks.

**Comment by ChrisHegarty** [comment]
No problem. I appreciate you raising this. I'll keep an eye on the nightly smokertester.
