### ISSUE TITLE
Using a searcher with an executor service does not work from within a Callable called by that same executor service [LUCENE-3803]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#4876]
The test case I'm about to attach creates an executor service uses invokeAll to run things from it. The 'things' (Callable) that it runs in turn run Lucene searchers using a searcher that has the very same executor service. This turns out to hit some sort of deadlock related to the executor service queue. 

I won't be terribly surprised if this is really a matter of a fundamental limitation of the executor service, but if nothing else this JIRA might provoke a warning in the javadoc. Or, what do I know, maybe there's a way Lucene could interact with the executor service that gets along with this?

---
Migrated from [LUCENE-3803](https://issues.apache.org/jira/browse/LUCENE-3803) by Benson Margulies (@bimargulies-google)
Attachments: [lucene-tc.tgz](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-3803/lucene-tc.tgz)

**Comment by javanna** [comment]
I stumbled upon this issue by coincidence, and I believe it has been addressed by https://github.com/apache/lucene/pull/12569 . There are real situations where this can happen now as we parallelize createWeight, see for instance `TopFieldCollector#populateScores`.
