### ISSUE TITLE
TestNRTManager hangs with IBM JRE [LUCENE-3928]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#5001]
(note, only triggered on 4.0, possibly could affect 3.x too, no idea)

---
Migrated from [LUCENE-3928](https://issues.apache.org/jira/browse/LUCENE-3928) by Robert Muir (@rmuir), updated Oct 15 2015
Attachments: [javacore.20120327.055021.4057.0001.txt](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-3928/javacore.20120327.055021.4057.0001.txt)

**Comment by uschindler** [comment]
This test now passes with IBM Semeru / OpenJ9
