### ISSUE TITLE
Upgrade ant requirement to 1.9 in trunk (6.0) [LUCENE-6739]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#7797]
In trunk, I think we should upgrade the ant requirement to 1.9, both for the main build and for the smoketester.  Ant 1.9 was released two years ago and the ant version packaged with Ubuntu 14 is 1.9.3.  I'm not sure what comes with recent versions of Redhat systems and their derivatives, but the way that Redhat packages ant is completely incompatible with our build system anyway, requiring a manual install.

---
Migrated from [LUCENE-6739](https://issues.apache.org/jira/browse/LUCENE-6739) by Shawn Heisey (@elyograg), updated May 09 2016
Attachments: [LUCENE-6739.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-6739/LUCENE-6739.patch)

**Comment by slow-J** [comment]
I think we can close this one since Ant support was removed from trunk in https://issues.apache.org/jira/browse/LUCENE-9433 :D
