### ISSUE TITLE
Refactoring: Rename Levenstein to Levenshtein [LUCENE-7370]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#8424]
In suggest module, Levenshtein edit distance is named as Levenstein. To protect conventions it would be good to rename it as suggested in this issue.

---
Migrated from [LUCENE-7370](https://issues.apache.org/jira/browse/LUCENE-7370) by Heval Azizoglu
Attachments: [LUCENE-7370.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-7370/LUCENE-7370.patch)

**Comment by shaikhu** [comment]
Can this be closed? It looks like the typo was corrected with this [commit](70b36666d49d1207aa9776eaa859c69278933515).

**Comment by shaikhu** [comment]
@mikemccand I think this can be closed now 😉

**Comment by mikemccand** [comment]
Great, thanks @shaikhu!
