### ISSUE TITLE
Wildcard query parser of MultiFieldQueryParser should support boosts [LUCENE-7917]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#8966]
https://stackoverflow.com/questions/45454710/getwildcardquery-method-of-multifieldqueryparser-doesnt-process-boosts-map-as-g
For some reason getWildcardQuery of MultiFieldQueryParser doesn't handle boosts map as getFieldQuery does. But it'd be great if getWildcardQuery does it as well.

The patch in attachments. Please, check it.

---
Migrated from [LUCENE-7917](https://issues.apache.org/jira/browse/LUCENE-7917) by Yegor Dovganich, updated Aug 09 2017
Attachments: [LUCENE-7919.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-7917/LUCENE-7919.patch)

**Comment by jasirkt** [comment]
Apart from wildcard query, this issue also applies to fuzzy, prefix, range and regexp queries
