### ISSUE TITLE
HyphenationCompoundWordTokenFilter creates overlapping tokens with onlyLongestMatch enabled [LUCENE-8183]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#9231]
The HyphenationCompoundWordTokenFilter creates overlapping tokens even if onlyLongestMatch is enabled. 

Example:

Dictionary: `gesellschaft`, `schaft`
 Hyphenator: `de_DR.xml` //from Apche Offo
 onlyLongestMatch: true

 

|text|gesellschaft|gesellschaft|schaft|
|-|-|-|-|
|raw_bytes|[67 65 73 65 6c 6c 73 63 68 61 66 74]|[67 65 73 65 6c 6c 73 63 68 61 66 74]|[73 63 68 61 66 74]|
|start|0|0|0|
|end|12|12|12|
|positionLength|1|1|1|
|type|word|word|word|
|position|1|1|1|

IMHO this includes 2 unexpected Tokens
1. the 2nd 'gesellschaft' as it duplicates the original token
1. the 'schaft' as it is a sub-token 'gesellschaft' that is present in the dictionary

---
Migrated from [LUCENE-8183](https://issues.apache.org/jira/browse/LUCENE-8183) by Rupert Westenthaler, 1 vote, updated Jan 14 2021
Environment:
```
Configuration of the analyzer:

<tokenizer class="solr.WhitespaceTokenizerFactory"/>
<filter class="solr.LowerCaseFilterFactory"/>
<filter class="solr.HyphenationCompoundWordTokenFilterFactory" 
        hyphenator="lang/hyph_de_DR.xml" encoding="iso-8859-1"
         dictionary="lang/wordlist_de.txt" 
        onlyLongestMatch="true"/>

 
```

Attachments: [LUCENE-8183_20180223_rwesten.diff](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-8183/LUCENE-8183_20180223_rwesten.diff), [LUCENE-8183_20180227_rwesten.diff](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-8183/LUCENE-8183_20180227_rwesten.diff), [lucene-8183.zip](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-8183/lucene-8183.zip)
Linked issues:
 - #4096

**Comment by AlmostFamiliar** [comment]
Are there still plans to merge this? 

I would also be very interested in this feature.

**Comment by MartinDemberger** [comment]
Hi @uschindler,
I have adopted my PR for this repository.

**Comment by uschindler** [comment]
Does this also fix #4096 ?

**Comment by MartinDemberger** [comment]
> Does this also fix #4096 ?

I'm sorry but no. #4096 notifies DictionaryCompoundWordTokenFilter but this one is about HyphenationCompoundWordTokenFilter
Maybe the change can be adopted but currently I don't have time and knowlege to do this. Maybe I have a look on it in a few weeks.

**Comment by uschindler** [comment]
> > Does this also fix #4096 ?
> 
> I'm sorry but no. #4096 notifies DictionaryCompoundWordTokenFilter but this one is about HyphenationCompoundWordTokenFilter Maybe the change can be adopted but currently I don't have time and knowlege to do this. Maybe I have a look on it in a few weeks.

You're right. I did not notice that this is the dictionary one. I have just seen that this issue was linked to the other one and did not read the whole issue.

**Comment by uschindler** [comment]
Hi,
i backported (cherry-picked) the PR also to Lucene 9.8.

Would it be possible that you maybe give a PR for the german-decompounder with an updated configuration in README.txt.
We should also open an issue at Elasticsearch/Opensearch that the new ctor parameters / factory are recognized in their code. Otherwise the new features cannot be used in ES/OS.

Solr should not be an issue, maybe some documentation fixes there, too.

**Comment by MartinDemberger** [comment]
Hi,
thank you very much. My company is waiting for this fix for several years.

I will create the ES/OS issue and try to update the README in the next days.
