### ISSUE TITLE
Upgrade OpenNLP to 1.9.1 [LUCENE-8659]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#9705]
Since Apache OpenNLP 1.9.1 has been released it would be nice to upgrade Lucene/Solr to use that.

---
Migrated from [LUCENE-8659](https://issues.apache.org/jira/browse/LUCENE-8659) by Tommaso Teofili (@tteofili), updated Dec 08 2021

**Comment by cpoerschke** [comment]
Thanks @hurutoriya for re-surfacing this issue!

Closing as superseded by #11277 upgrading to 1.9.4 version.
