### ISSUE TITLE
Raise a fake issue !Do not raise a real issue in GitHub until the official announcement is sent!

### ISSUE THREAD

**Issue by mocobeta** [apache/lucene#993]
It's a test issue.
Please do not use GitHub issues until the migration will have done; Issues should be raised in [Jira](https://issues.apache.org/jira/projects/LUCENE/).

**Comment by mocobeta** [comment]
Verified that external contributors cannot modify labels.

**Comment by LuXugang** [comment]
A new start, Thanks for your great work 😊

**Comment by mocobeta** [comment]
Thanks @LuXugang for noticing this.

To devs,
I will keep issues enabled for a while, please feel free to test and play around it.

**Comment by ats1999** [comment]
Isn’t there any good first issue?

**Comment by ats1999** [comment]
Just checking!

**Comment by mocobeta** [comment]
@ats1999 There's a label "good first issue" but it doesn't seem to be used.
